package reports

import (
	"fmt"

	"github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/props"
)

// PDFRenderer renders a ReportData as a PDF document.
type PDFRenderer struct{}

// pdfColor converts a hex color string to a maroto props.Color.
func pdfColor(hex string) *props.Color {
	r, g, b := hexToRGB(hex)
	return &props.Color{Red: r, Green: g, Blue: b}
}

// hexToRGB parses a hex color like "#e53e3e" into RGB ints.
func hexToRGB(hex string) (int, int, int) {
	if len(hex) == 7 && hex[0] == '#' {
		var r, g, b int
		_, _ = fmt.Sscanf(hex[1:], "%02x%02x%02x", &r, &g, &b)
		return r, g, b
	}
	return 113, 128, 150 // gray fallback
}

// statBoxColor maps a color name to a hex value for stat boxes.
func statBoxColor(name string) string {
	switch name {
	case "green":
		return "#38a169"
	case "red":
		return "#e53e3e"
	case "orange":
		return "#dd6b20"
	case "blue":
		return "#3182ce"
	case "gray":
		return "#718096"
	default:
		return "#718096"
	}
}

// Render produces a PDF byte slice from data.
func (r *PDFRenderer) Render(data *ReportData) ([]byte, error) {
	cfg := config.NewBuilder().
		WithLeftMargin(10).
		WithRightMargin(10).
		WithTopMargin(10).
		WithPageNumber(props.PageNumber{
			Pattern: "Page {current} of {total}",
			Place:   props.RightBottom,
			Size:    8,
		}).
		Build()

	m := maroto.New(cfg)

	// -- Header --
	headerRows := []interface { // core.Row
	}{}
	_ = headerRows

	if err := m.RegisterHeader(
		row.New(10).Add(
			col.New(12).Add(text.New(data.Meta.Title, props.Text{
				Size:  18,
				Style: fontstyle.Bold,
				Align: align.Left,
			})),
		),
		row.New(6).Add(
			col.New(12).Add(text.New(
				fmt.Sprintf("Tenant: %s | %s to %s | Generated: %s",
					data.Meta.TenantName,
					data.Meta.DateFrom.In(IST).Format("2006-01-02"),
					data.Meta.DateTo.In(IST).Format("2006-01-02"),
					data.Meta.GeneratedAt.In(IST).Format("2006-01-02 15:04:05 MST"),
				),
				props.Text{Size: 9, Style: fontstyle.Normal, Align: align.Left},
			)),
		),
	); err != nil {
		return nil, fmt.Errorf("pdf render: register header: %w", err)
	}

	// -- Footer --
	if err := m.RegisterFooter(
		row.New(8).Add(
			col.New(6).Add(text.New("Generated by PatchIQ", props.Text{
				Size:  7,
				Style: fontstyle.Italic,
				Align: align.Left,
				Color: pdfColor("#718096"),
			})),
			col.New(6), // page number handled by WithPageNumber config
		),
	); err != nil {
		return nil, fmt.Errorf("pdf render: register footer: %w", err)
	}

	// -- Subtitle if present --
	if data.Meta.Subtitle != "" {
		m.AddRows(row.New(7).Add(
			col.New(12).Add(text.New(data.Meta.Subtitle, props.Text{
				Size:  12,
				Style: fontstyle.BoldItalic,
				Align: align.Left,
			})),
		))
	}

	// -- Summary stat boxes --
	if len(data.Summary) > 0 {
		m.AddRows(row.New(3)) // spacer

		colSize := 12 / max(len(data.Summary), 1)
		if colSize < 1 {
			colSize = 1
		}

		// Labels row.
		labelCols := make([]interface{}, 0, len(data.Summary))
		_ = labelCols
		labelRow := row.New(6)
		valueRow := row.New(8)
		for _, stat := range data.Summary {
			bgColor := pdfColor(statBoxColor(stat.Color))
			labelRow = labelRow.Add(
				col.New(colSize).Add(text.New(stat.Label, props.Text{
					Size:  8,
					Style: fontstyle.Bold,
					Align: align.Center,
				})),
			)
			valueRow = valueRow.Add(
				col.New(colSize).WithStyle(&props.Cell{
					BackgroundColor: bgColor,
				}).Add(text.New(stat.Value, props.Text{
					Size:  11,
					Style: fontstyle.Bold,
					Align: align.Center,
					Color: &props.WhiteColor,
				})),
			)
		}
		m.AddRows(labelRow, valueRow)
		m.AddRows(row.New(4)) // spacer
	}

	// TODO(PIQ-reports): embed chart PNGs when charts.go is implemented

	// -- Breakdown tables --
	grayBg := pdfColor("#f7fafc")
	for _, bt := range data.Breakdowns {
		// Title.
		m.AddRows(row.New(8).Add(
			col.New(12).Add(text.New(bt.Title, props.Text{
				Size:  12,
				Style: fontstyle.Bold,
				Align: align.Left,
			})),
		))

		// Header row.
		hdrRow := row.New(7).WithStyle(&props.Cell{BackgroundColor: grayBg})
		hdrColSize := 12 / max(len(bt.Columns), 1)
		for _, c := range bt.Columns {
			hdrRow = hdrRow.Add(col.New(hdrColSize).Add(text.New(c, props.Text{
				Size:  9,
				Style: fontstyle.Bold,
				Align: align.Left,
			})))
		}
		m.AddRows(hdrRow)

		// Data rows.
		for ri, dataRow := range bt.Rows {
			dr := row.New(6)
			if ri < len(bt.RowColors) && bt.RowColors[ri] != "" {
				dr = dr.WithStyle(&props.Cell{BackgroundColor: pdfColor(bt.RowColors[ri])})
			}
			for _, val := range dataRow {
				dr = dr.Add(col.New(hdrColSize).Add(text.New(val, props.Text{
					Size:  8,
					Align: align.Left,
				})))
			}
			m.AddRows(dr)
		}

		m.AddRows(row.New(4)) // spacer
	}

	// -- Highlights section --
	for _, hl := range data.Highlights {
		m.AddRows(row.New(8).Add(
			col.New(12).Add(text.New(hl.Title, props.Text{
				Size:  12,
				Style: fontstyle.Bold,
				Align: align.Left,
				Color: pdfColor("#e53e3e"),
			})),
		))
		if hl.Description != "" {
			m.AddRows(row.New(5).Add(
				col.New(12).Add(text.New(hl.Description, props.Text{
					Size:  8,
					Align: align.Left,
				})),
			))
		}

		hlColSize := 12 / max(len(hl.Columns), 1)
		hlHdr := row.New(7).WithStyle(&props.Cell{BackgroundColor: grayBg})
		for _, c := range hl.Columns {
			hlHdr = hlHdr.Add(col.New(hlColSize).Add(text.New(c, props.Text{
				Size:  9,
				Style: fontstyle.Bold,
				Align: align.Left,
			})))
		}
		m.AddRows(hlHdr)

		for ri, dataRow := range hl.Rows {
			dr := row.New(6)
			if ri < len(hl.RowColors) && hl.RowColors[ri] != "" {
				dr = dr.WithStyle(&props.Cell{BackgroundColor: pdfColor(hl.RowColors[ri])})
			}
			for _, val := range dataRow {
				dr = dr.Add(col.New(hlColSize).Add(text.New(val, props.Text{
					Size:  8,
					Align: align.Left,
				})))
			}
			m.AddRows(dr)
		}
		m.AddRows(row.New(4)) // spacer
	}

	// -- Detail table --
	if len(data.Detail.Columns) > 0 {
		m.AddRows(row.New(8).Add(
			col.New(12).Add(text.New("Detail", props.Text{
				Size:  14,
				Style: fontstyle.Bold,
				Align: align.Left,
			})),
		))

		detColSize := 12 / max(len(data.Detail.Columns), 1)
		if detColSize < 1 {
			detColSize = 1
		}

		// Header.
		detHdr := row.New(7).WithStyle(&props.Cell{BackgroundColor: grayBg})
		for _, c := range data.Detail.Columns {
			detHdr = detHdr.Add(col.New(detColSize).Add(text.New(c, props.Text{
				Size:  8,
				Style: fontstyle.Bold,
				Align: align.Left,
			})))
		}
		m.AddRows(detHdr)

		// Rows (capped at MaxPDFRows).
		maxRows := data.Detail.MaxPDFRows
		if maxRows <= 0 {
			maxRows = 500
		}
		rowCount := len(data.Detail.Rows)
		if rowCount > maxRows {
			rowCount = maxRows
		}

		for ri := 0; ri < rowCount; ri++ {
			dr := row.New(6)
			if ri < len(data.Detail.RowColors) && data.Detail.RowColors[ri] != "" {
				dr = dr.WithStyle(&props.Cell{BackgroundColor: pdfColor(data.Detail.RowColors[ri])})
			}
			for _, val := range data.Detail.Rows[ri] {
				dr = dr.Add(col.New(detColSize).Add(text.New(val, props.Text{
					Size:  8,
					Align: align.Left,
				})))
			}
			m.AddRows(dr)
		}

		// Truncation note.
		totalRows := data.Detail.TotalRows
		if totalRows == 0 {
			totalRows = len(data.Detail.Rows)
		}
		if totalRows > maxRows {
			m.AddRows(row.New(7).Add(
				col.New(12).Add(text.New(
					fmt.Sprintf("Showing %d of %d rows. Download CSV or XLSX for complete data.", maxRows, totalRows),
					props.Text{
						Size:  8,
						Style: fontstyle.Italic,
						Align: align.Center,
						Color: pdfColor("#718096"),
					},
				)),
			))
		}
	}

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("pdf render: generate: %w", err)
	}

	return doc.GetBytes(), nil
}

// ContentType returns the MIME type for PDF.
func (r *PDFRenderer) ContentType() string {
	return "application/pdf"
}

// FileExtension returns "pdf".
func (r *PDFRenderer) FileExtension() string {
	return "pdf"
}
