// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_registrations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRegistration = `-- name: ClaimRegistration :one
UPDATE agent_registrations
SET status = 'registered', endpoint_id = $3, registered_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'pending'
RETURNING id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at
`

type ClaimRegistrationParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) ClaimRegistration(ctx context.Context, arg ClaimRegistrationParams) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, claimRegistration, arg.ID, arg.TenantID, arg.EndpointID)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO agent_registrations (tenant_id, registration_token, expires_at)
VALUES ($1, $2, COALESCE($3::timestamptz, now() + INTERVAL '7 days'))
RETURNING id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at
`

type CreateRegistrationParams struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	RegistrationToken string             `json:"registration_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, createRegistration, arg.TenantID, arg.RegistrationToken, arg.ExpiresAt)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRegistrationByID = `-- name: GetRegistrationByID :one
SELECT id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at FROM agent_registrations WHERE id = $1 AND tenant_id = $2
`

type GetRegistrationByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRegistrationByID(ctx context.Context, arg GetRegistrationByIDParams) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByID, arg.ID, arg.TenantID)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRegistrationByToken = `-- name: GetRegistrationByToken :one
SELECT id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at FROM agent_registrations WHERE registration_token = $1 AND tenant_id = $2
`

type GetRegistrationByTokenParams struct {
	RegistrationToken string      `json:"registration_token"`
	TenantID          pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRegistrationByToken(ctx context.Context, arg GetRegistrationByTokenParams) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByToken, arg.RegistrationToken, arg.TenantID)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listRegistrationsByTenant = `-- name: ListRegistrationsByTenant :many
SELECT id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at FROM agent_registrations WHERE tenant_id = $1 ORDER BY created_at DESC
LIMIT 1000
`

func (q *Queries) ListRegistrationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]AgentRegistration, error) {
	rows, err := q.db.Query(ctx, listRegistrationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRegistration{}
	for rows.Next() {
		var i AgentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.RegistrationToken,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupRegistrationByToken = `-- name: LookupRegistrationByToken :one
SELECT id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at FROM agent_registrations WHERE registration_token = $1
`

func (q *Queries) LookupRegistrationByToken(ctx context.Context, registrationToken string) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, lookupRegistrationByToken, registrationToken)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeRegistration = `-- name: RevokeRegistration :one
UPDATE agent_registrations
SET status = 'revoked'
WHERE id = $1 AND tenant_id = $2 AND status != 'revoked'
RETURNING id, tenant_id, endpoint_id, registration_token, status, registered_at, created_at, expires_at
`

type RevokeRegistrationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeRegistration(ctx context.Context, arg RevokeRegistrationParams) (AgentRegistration, error) {
	row := q.db.QueryRow(ctx, revokeRegistration, arg.ID, arg.TenantID)
	var i AgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.RegistrationToken,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
