// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCommandsByDeployment = `-- name: CancelCommandsByDeployment :exec
UPDATE commands
SET status = 'cancelled'
WHERE deployment_id = $1 AND tenant_id = $2
  AND status IN ('pending', 'delivered')
`

type CancelCommandsByDeploymentParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CancelCommandsByDeployment(ctx context.Context, arg CancelCommandsByDeploymentParams) error {
	_, err := q.db.Exec(ctx, cancelCommandsByDeployment, arg.DeploymentID, arg.TenantID)
	return err
}

const countPendingCommandsByAgent = `-- name: CountPendingCommandsByAgent :one
SELECT count(*) FROM commands
WHERE agent_id = $1 AND tenant_id = $2 AND status = 'pending'
`

type CountPendingCommandsByAgentParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CountPendingCommandsByAgent(ctx context.Context, arg CountPendingCommandsByAgentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCommandsByAgent, arg.AgentID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message
`

type CreateCommandParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	Type         string             `json:"type"`
	Payload      []byte             `json:"payload"`
	Priority     int32              `json:"priority"`
	Status       string             `json:"status"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.TenantID,
		arg.AgentID,
		arg.DeploymentID,
		arg.TargetID,
		arg.Type,
		arg.Payload,
		arg.Priority,
		arg.Status,
		arg.Deadline,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.DeploymentID,
		&i.TargetID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getActiveRunScanByAgent = `-- name: GetActiveRunScanByAgent :one
SELECT id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message FROM commands
WHERE agent_id = $1 AND tenant_id = $2
  AND type = 'run_scan'
  AND status IN ('pending', 'delivered')
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveRunScanByAgentParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetActiveRunScanByAgent(ctx context.Context, arg GetActiveRunScanByAgentParams) (Command, error) {
	row := q.db.QueryRow(ctx, getActiveRunScanByAgent, arg.AgentID, arg.TenantID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.DeploymentID,
		&i.TargetID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getCommandByID = `-- name: GetCommandByID :one
SELECT id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message FROM commands WHERE id = $1 AND tenant_id = $2
`

type GetCommandByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCommandByID(ctx context.Context, arg GetCommandByIDParams) (Command, error) {
	row := q.db.QueryRow(ctx, getCommandByID, arg.ID, arg.TenantID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.DeploymentID,
		&i.TargetID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const listActiveEndpointsByTenant = `-- name: ListActiveEndpointsByTenant :many
SELECT id, tenant_id, hostname, os_family, os_version, agent_version, status, last_seen, created_at, updated_at, ip_address, arch, kernel_version, maintenance_window, cpu_model, cpu_cores, memory_total_mb, memory_used_mb, disk_total_gb, disk_used_gb, gpu_model, uptime_seconds, enrolled_at, last_heartbeat, cert_expiry, hardware_details, software_summary, cpu_usage_percent, config_pushed_at FROM endpoints
WHERE tenant_id = $1 AND status = 'online'
ORDER BY hostname
LIMIT 1000
`

func (q *Queries) ListActiveEndpointsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listActiveEndpointsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Hostname,
			&i.OsFamily,
			&i.OsVersion,
			&i.AgentVersion,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.Arch,
			&i.KernelVersion,
			&i.MaintenanceWindow,
			&i.CpuModel,
			&i.CpuCores,
			&i.MemoryTotalMb,
			&i.MemoryUsedMb,
			&i.DiskTotalGb,
			&i.DiskUsedGb,
			&i.GpuModel,
			&i.UptimeSeconds,
			&i.EnrolledAt,
			&i.LastHeartbeat,
			&i.CertExpiry,
			&i.HardwareDetails,
			&i.SoftwareSummary,
			&i.CpuUsagePercent,
			&i.ConfigPushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchesForPolicyFilters = `-- name: ListPatchesForPolicyFilters :many
SELECT id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id FROM patches
WHERE tenant_id = $1
  AND (coalesce(cardinality($2::text[]), 0) = 0
       OR severity = ANY($2::text[]))
  AND os_family = ANY($3::text[])
  AND status = 'available'
ORDER BY name, version
LIMIT 1000
`

type ListPatchesForPolicyFiltersParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	SeverityFilter []string    `json:"severity_filter"`
	OsFamilies     []string    `json:"os_families"`
}

// Used by deployment evaluator: find patches matching severity + OS families.
func (q *Queries) ListPatchesForPolicyFilters(ctx context.Context, arg ListPatchesForPolicyFiltersParams) ([]Patch, error) {
	rows, err := q.db.Query(ctx, listPatchesForPolicyFilters, arg.TenantID, arg.SeverityFilter, arg.OsFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsDistribution,
			&i.PackageUrl,
			&i.ChecksumSha256,
			&i.SourceRepo,
			&i.Description,
			&i.ReleasedAt,
			&i.PackageName,
			&i.InstallerType,
			&i.SilentArgs,
			&i.DeletedAt,
			&i.HubCatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCommandsByAgent = `-- name: ListPendingCommandsByAgent :many
SELECT id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message FROM commands
WHERE agent_id = $1 AND tenant_id = $2 AND status = 'pending'
ORDER BY priority DESC, created_at ASC
LIMIT 1000
`

type ListPendingCommandsByAgentParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListPendingCommandsByAgent(ctx context.Context, arg ListPendingCommandsByAgentParams) ([]Command, error) {
	rows, err := q.db.Query(ctx, listPendingCommandsByAgent, arg.AgentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentID,
			&i.DeploymentID,
			&i.TargetID,
			&i.Type,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.Deadline,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedOutCommands = `-- name: ListTimedOutCommands :many
SELECT id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message FROM commands
WHERE status IN ('pending', 'delivered')
  AND deadline IS NOT NULL
  AND deadline < now()
LIMIT 100
`

// Cross-tenant system sweep: must run via Pool() (bypasses RLS).
func (q *Queries) ListTimedOutCommands(ctx context.Context) ([]Command, error) {
	rows, err := q.db.Query(ctx, listTimedOutCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentID,
			&i.DeploymentID,
			&i.TargetID,
			&i.Type,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.Deadline,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommandDelivered = `-- name: MarkCommandDelivered :one
UPDATE commands
SET status = 'delivered', delivered_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'pending'
RETURNING id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message
`

type MarkCommandDeliveredParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) MarkCommandDelivered(ctx context.Context, arg MarkCommandDeliveredParams) (Command, error) {
	row := q.db.QueryRow(ctx, markCommandDelivered, arg.ID, arg.TenantID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.DeploymentID,
		&i.TargetID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const updateCommandStatus = `-- name: UpdateCommandStatus :one
UPDATE commands
SET status = $2, completed_at = $3, error_message = $4
WHERE id = $1 AND tenant_id = $5
RETURNING id, tenant_id, agent_id, deployment_id, target_id, type, payload, priority, status, deadline, created_at, delivered_at, completed_at, error_message
`

type UpdateCommandStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateCommandStatus(ctx context.Context, arg UpdateCommandStatusParams) (Command, error) {
	row := q.db.QueryRow(ctx, updateCommandStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.TenantID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentID,
		&i.DeploymentID,
		&i.TargetID,
		&i.Type,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}
