// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveEndpoints = `-- name: CountActiveEndpoints :one

SELECT COUNT(*) FROM endpoints
WHERE tenant_id = $1 AND status != 'decommissioned'
`

// ------------------------------------------------------------
// Data queries for Tier 1 control evaluators
// ------------------------------------------------------------
func (q *Queries) CountActiveEndpoints(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEndpoints, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsScannedForCVEs = `-- name: CountEndpointsScannedForCVEs :one
SELECT COUNT(DISTINCT ec.endpoint_id) FROM endpoint_cves ec
WHERE ec.tenant_id = $1
`

func (q *Queries) CountEndpointsScannedForCVEs(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsScannedForCVEs, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithHardwareInfo = `-- name: CountEndpointsWithHardwareInfo :one
SELECT COUNT(*) FROM endpoints
WHERE tenant_id = $1 AND status != 'decommissioned'
  AND cpu_model IS NOT NULL AND memory_total_mb > 0
`

func (q *Queries) CountEndpointsWithHardwareInfo(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithHardwareInfo, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithKEVVulnerabilities = `-- name: CountEndpointsWithKEVVulnerabilities :one
SELECT COUNT(DISTINCT ec.endpoint_id) FROM endpoint_cves ec
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1 AND ec.status = 'affected'
  AND c.cisa_kev_due_date IS NOT NULL
`

func (q *Queries) CountEndpointsWithKEVVulnerabilities(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithKEVVulnerabilities, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithRecentHeartbeat = `-- name: CountEndpointsWithRecentHeartbeat :one
SELECT COUNT(*) FROM endpoints
WHERE tenant_id = $1 AND status != 'decommissioned'
  AND last_heartbeat > $2
`

type CountEndpointsWithRecentHeartbeatParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountEndpointsWithRecentHeartbeat(ctx context.Context, arg CountEndpointsWithRecentHeartbeatParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithRecentHeartbeat, arg.TenantID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithRecentInventory = `-- name: CountEndpointsWithRecentInventory :one
SELECT COUNT(DISTINCT e.id) FROM endpoints e
JOIN endpoint_inventories ei ON ei.endpoint_id = e.id AND ei.tenant_id = e.tenant_id
WHERE e.tenant_id = $1 AND e.status != 'decommissioned'
  AND ei.scanned_at > $2
`

type CountEndpointsWithRecentInventoryParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountEndpointsWithRecentInventory(ctx context.Context, arg CountEndpointsWithRecentInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithRecentInventory, arg.TenantID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithStaleCriticalCVEs = `-- name: CountEndpointsWithStaleCriticalCVEs :one
SELECT COUNT(DISTINCT ec.endpoint_id) FROM endpoint_cves ec
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1 AND ec.status = 'affected'
  AND c.severity IN ('critical', 'high')
  AND ec.detected_at < $2
`

type CountEndpointsWithStaleCriticalCVEsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	MaxAge   pgtype.Timestamptz `json:"max_age"`
}

func (q *Queries) CountEndpointsWithStaleCriticalCVEs(ctx context.Context, arg CountEndpointsWithStaleCriticalCVEsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithStaleCriticalCVEs, arg.TenantID, arg.MaxAge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpointsWithStaleCriticalOnlyCVEs = `-- name: CountEndpointsWithStaleCriticalOnlyCVEs :one
SELECT COUNT(DISTINCT ec.endpoint_id) FROM endpoint_cves ec
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1 AND ec.status = 'affected'
  AND c.severity = 'critical'
  AND ec.detected_at < $2
`

type CountEndpointsWithStaleCriticalOnlyCVEsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	MaxAge   pgtype.Timestamptz `json:"max_age"`
}

func (q *Queries) CountEndpointsWithStaleCriticalOnlyCVEs(ctx context.Context, arg CountEndpointsWithStaleCriticalOnlyCVEsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsWithStaleCriticalOnlyCVEs, arg.TenantID, arg.MaxAge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvaluationsByState = `-- name: CountEvaluationsByState :many
SELECT ce.state, count(*)::bigint AS count
FROM compliance_evaluations ce
WHERE ce.tenant_id = $1
  AND ce.framework_id = $2
  AND ce.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_evaluations sub
      WHERE sub.tenant_id = $1
        AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
GROUP BY ce.state
`

type CountEvaluationsByStateParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

type CountEvaluationsByStateRow struct {
	State string `json:"state"`
	Count int64  `json:"count"`
}

func (q *Queries) CountEvaluationsByState(ctx context.Context, arg CountEvaluationsByStateParams) ([]CountEvaluationsByStateRow, error) {
	rows, err := q.db.Query(ctx, countEvaluationsByState, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEvaluationsByStateRow{}
	for rows.Next() {
		var i CountEvaluationsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTenantFramework = `-- name: CreateTenantFramework :one


INSERT INTO compliance_tenant_frameworks (tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at
`

type CreateTenantFrameworkParams struct {
	TenantID        pgtype.UUID    `json:"tenant_id"`
	FrameworkID     string         `json:"framework_id"`
	Enabled         bool           `json:"enabled"`
	SlaOverrides    []byte         `json:"sla_overrides"`
	ScoringMethod   string         `json:"scoring_method"`
	AtRiskThreshold pgtype.Numeric `json:"at_risk_threshold"`
}

// ============================================================
// Compliance engine queries (#176)
// ============================================================
// ------------------------------------------------------------
// Tenant Frameworks
// ------------------------------------------------------------
func (q *Queries) CreateTenantFramework(ctx context.Context, arg CreateTenantFrameworkParams) (ComplianceTenantFramework, error) {
	row := q.db.QueryRow(ctx, createTenantFramework,
		arg.TenantID,
		arg.FrameworkID,
		arg.Enabled,
		arg.SlaOverrides,
		arg.ScoringMethod,
		arg.AtRiskThreshold,
	)
	var i ComplianceTenantFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.Enabled,
		&i.SlaOverrides,
		&i.ScoringMethod,
		&i.AtRiskThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteControlResultsByFramework = `-- name: DeleteControlResultsByFramework :exec
DELETE FROM compliance_control_results
WHERE tenant_id = $1 AND framework_id = $2
  AND evaluation_run_id != $3
`

type DeleteControlResultsByFrameworkParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	FrameworkID  string      `json:"framework_id"`
	CurrentRunID pgtype.UUID `json:"current_run_id"`
}

func (q *Queries) DeleteControlResultsByFramework(ctx context.Context, arg DeleteControlResultsByFrameworkParams) error {
	_, err := q.db.Exec(ctx, deleteControlResultsByFramework, arg.TenantID, arg.FrameworkID, arg.CurrentRunID)
	return err
}

const deleteOldControlResults = `-- name: DeleteOldControlResults :exec
DELETE FROM compliance_control_results
WHERE tenant_id = $1
  AND evaluated_at < $2
`

type DeleteOldControlResultsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Before   pgtype.Timestamptz `json:"before"`
}

func (q *Queries) DeleteOldControlResults(ctx context.Context, arg DeleteOldControlResultsParams) error {
	_, err := q.db.Exec(ctx, deleteOldControlResults, arg.TenantID, arg.Before)
	return err
}

const deleteOldEvaluations = `-- name: DeleteOldEvaluations :exec
DELETE FROM compliance_evaluations
WHERE tenant_id = $1
  AND evaluated_at < $2
`

type DeleteOldEvaluationsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Before   pgtype.Timestamptz `json:"before"`
}

func (q *Queries) DeleteOldEvaluations(ctx context.Context, arg DeleteOldEvaluationsParams) error {
	_, err := q.db.Exec(ctx, deleteOldEvaluations, arg.TenantID, arg.Before)
	return err
}

const deleteOldScores = `-- name: DeleteOldScores :exec
DELETE FROM compliance_scores
WHERE tenant_id = $1
  AND evaluated_at < $2
`

type DeleteOldScoresParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Before   pgtype.Timestamptz `json:"before"`
}

func (q *Queries) DeleteOldScores(ctx context.Context, arg DeleteOldScoresParams) error {
	_, err := q.db.Exec(ctx, deleteOldScores, arg.TenantID, arg.Before)
	return err
}

const deleteTenantFramework = `-- name: DeleteTenantFramework :exec
DELETE FROM compliance_tenant_frameworks
WHERE id = $1 AND tenant_id = $2
`

type DeleteTenantFrameworkParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTenantFramework(ctx context.Context, arg DeleteTenantFrameworkParams) error {
	_, err := q.db.Exec(ctx, deleteTenantFramework, arg.ID, arg.TenantID)
	return err
}

const getCompliantEndpointCountsByFramework = `-- name: GetCompliantEndpointCountsByFramework :many
WITH latest_runs AS (
    SELECT DISTINCT ON (framework_id) framework_id, evaluation_run_id
    FROM compliance_scores WHERE tenant_id = $1 AND scope_type = 'endpoint'
    ORDER BY framework_id, evaluated_at DESC
)
SELECT
    cs.framework_id,
    COUNT(*) FILTER (WHERE cs.score >= 95)::integer AS endpoints_compliant,
    COUNT(*)::integer AS total_endpoints
FROM compliance_scores cs
JOIN latest_runs lr ON cs.framework_id = lr.framework_id AND cs.evaluation_run_id = lr.evaluation_run_id
JOIN compliance_tenant_frameworks ctf ON cs.framework_id = ctf.framework_id AND cs.tenant_id = ctf.tenant_id
WHERE cs.tenant_id = $1
  AND cs.scope_type = 'endpoint'
  AND ctf.enabled = true
GROUP BY cs.framework_id
`

type GetCompliantEndpointCountsByFrameworkRow struct {
	FrameworkID        string `json:"framework_id"`
	EndpointsCompliant int32  `json:"endpoints_compliant"`
	TotalEndpoints     int32  `json:"total_endpoints"`
}

func (q *Queries) GetCompliantEndpointCountsByFramework(ctx context.Context, tenantID pgtype.UUID) ([]GetCompliantEndpointCountsByFrameworkRow, error) {
	rows, err := q.db.Query(ctx, getCompliantEndpointCountsByFramework, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompliantEndpointCountsByFrameworkRow{}
	for rows.Next() {
		var i GetCompliantEndpointCountsByFrameworkRow
		if err := rows.Scan(&i.FrameworkID, &i.EndpointsCompliant, &i.TotalEndpoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getControlCountsByFramework = `-- name: GetControlCountsByFramework :many
WITH latest_runs AS (
    SELECT DISTINCT ON (framework_id) framework_id, evaluation_run_id
    FROM compliance_control_results WHERE tenant_id = $1
    ORDER BY framework_id, evaluated_at DESC
)
SELECT
    ccr.framework_id,
    COUNT(*) FILTER (WHERE ccr.status = 'pass')::integer AS passing_controls,
    COUNT(*) FILTER (WHERE ccr.status = 'fail')::integer AS failing_controls,
    COUNT(*) FILTER (WHERE ccr.status = 'partial')::integer AS partial_controls,
    COUNT(*) FILTER (WHERE ccr.status = 'na')::integer AS na_controls,
    COUNT(*)::integer AS total_controls,
    COUNT(*) FILTER (WHERE ccr.status IN ('fail', 'partial') AND ccr.sla_deadline_at IS NOT NULL AND ccr.sla_deadline_at < now())::integer AS overdue_count,
    COALESCE(MAX(ccr.total_endpoints), 0)::integer AS max_total_endpoints
FROM compliance_control_results ccr
JOIN latest_runs lr ON ccr.framework_id = lr.framework_id AND ccr.evaluation_run_id = lr.evaluation_run_id
WHERE ccr.tenant_id = $1
GROUP BY ccr.framework_id
`

type GetControlCountsByFrameworkRow struct {
	FrameworkID       string `json:"framework_id"`
	PassingControls   int32  `json:"passing_controls"`
	FailingControls   int32  `json:"failing_controls"`
	PartialControls   int32  `json:"partial_controls"`
	NaControls        int32  `json:"na_controls"`
	TotalControls     int32  `json:"total_controls"`
	OverdueCount      int32  `json:"overdue_count"`
	MaxTotalEndpoints int32  `json:"max_total_endpoints"`
}

func (q *Queries) GetControlCountsByFramework(ctx context.Context, tenantID pgtype.UUID) ([]GetControlCountsByFrameworkRow, error) {
	rows, err := q.db.Query(ctx, getControlCountsByFramework, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetControlCountsByFrameworkRow{}
	for rows.Next() {
		var i GetControlCountsByFrameworkRow
		if err := rows.Scan(
			&i.FrameworkID,
			&i.PassingControls,
			&i.FailingControls,
			&i.PartialControls,
			&i.NaControls,
			&i.TotalControls,
			&i.OverdueCount,
			&i.MaxTotalEndpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrameworkScoreSummary = `-- name: GetFrameworkScoreSummary :many
SELECT ctf.framework_id, COALESCE(cs.score, 0)::numeric(5,2) AS score
FROM compliance_tenant_frameworks ctf
LEFT JOIN LATERAL (
    SELECT cs2.score
    FROM compliance_scores cs2
    WHERE cs2.tenant_id = ctf.tenant_id
      AND cs2.framework_id = ctf.framework_id
      AND cs2.scope_type = 'tenant'
    ORDER BY cs2.evaluated_at DESC
    LIMIT 1
) cs ON true
WHERE ctf.tenant_id = $1
  AND ctf.enabled = true
`

type GetFrameworkScoreSummaryRow struct {
	FrameworkID string         `json:"framework_id"`
	Score       pgtype.Numeric `json:"score"`
}

func (q *Queries) GetFrameworkScoreSummary(ctx context.Context, tenantID pgtype.UUID) ([]GetFrameworkScoreSummaryRow, error) {
	rows, err := q.db.Query(ctx, getFrameworkScoreSummary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFrameworkScoreSummaryRow{}
	for rows.Next() {
		var i GetFrameworkScoreSummaryRow
		if err := rows.Scan(&i.FrameworkID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastEvaluationTime = `-- name: GetLastEvaluationTime :one
SELECT MAX(evaluated_at)::timestamptz AS last_evaluated_at
FROM compliance_scores
WHERE tenant_id = $1
`

func (q *Queries) GetLastEvaluationTime(ctx context.Context, tenantID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastEvaluationTime, tenantID)
	var last_evaluated_at pgtype.Timestamptz
	err := row.Scan(&last_evaluated_at)
	return last_evaluated_at, err
}

const getLatestFrameworkScore = `-- name: GetLatestFrameworkScore :one
SELECT id, tenant_id, evaluation_run_id, framework_id, scope_type, scope_id, score, total_cves, compliant_cves, at_risk_cves, non_compliant_cves, late_remediation_cves, evaluated_at FROM compliance_scores cs
WHERE cs.tenant_id = $1
  AND cs.framework_id = $2
  AND cs.scope_type = 'tenant'
  AND cs.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_scores sub
      WHERE sub.tenant_id = $1 AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
`

type GetLatestFrameworkScoreParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) GetLatestFrameworkScore(ctx context.Context, arg GetLatestFrameworkScoreParams) (ComplianceScore, error) {
	row := q.db.QueryRow(ctx, getLatestFrameworkScore, arg.TenantID, arg.FrameworkID)
	var i ComplianceScore
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvaluationRunID,
		&i.FrameworkID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Score,
		&i.TotalCves,
		&i.CompliantCves,
		&i.AtRiskCves,
		&i.NonCompliantCves,
		&i.LateRemediationCves,
		&i.EvaluatedAt,
	)
	return i, err
}

const getLatestScoresByFramework = `-- name: GetLatestScoresByFramework :many
SELECT id, tenant_id, evaluation_run_id, framework_id, scope_type, scope_id, score, total_cves, compliant_cves, at_risk_cves, non_compliant_cves, late_remediation_cves, evaluated_at FROM compliance_scores cs
WHERE cs.tenant_id = $1
  AND cs.framework_id = $2
  AND cs.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_scores sub
      WHERE sub.tenant_id = $1 AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY cs.scope_type, cs.scope_id
`

type GetLatestScoresByFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) GetLatestScoresByFramework(ctx context.Context, arg GetLatestScoresByFrameworkParams) ([]ComplianceScore, error) {
	rows, err := q.db.Query(ctx, getLatestScoresByFramework, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceScore{}
	for rows.Next() {
		var i ComplianceScore
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.FrameworkID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Score,
			&i.TotalCves,
			&i.CompliantCves,
			&i.AtRiskCves,
			&i.NonCompliantCves,
			&i.LateRemediationCves,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallComplianceScore = `-- name: GetOverallComplianceScore :one
SELECT
    COALESCE(AVG(sub.score), 0.00)::numeric(5,2) AS overall_score,
    COALESCE(SUM(sub.total_cves), 0)::bigint AS total_cves,
    COALESCE(SUM(sub.compliant_cves), 0)::bigint AS compliant_cves,
    COALESCE(SUM(sub.at_risk_cves), 0)::bigint AS at_risk_cves,
    COALESCE(SUM(sub.non_compliant_cves), 0)::bigint AS non_compliant_cves,
    COUNT(*)::bigint AS framework_count
FROM (
    SELECT
        COALESCE(latest.score, 0.00) AS score,
        COALESCE(latest.total_cves, 0) AS total_cves,
        COALESCE(latest.compliant_cves, 0) AS compliant_cves,
        COALESCE(latest.at_risk_cves, 0) AS at_risk_cves,
        COALESCE(latest.non_compliant_cves, 0) AS non_compliant_cves
    FROM compliance_tenant_frameworks ctf
    LEFT JOIN LATERAL (
        SELECT cs.score, cs.total_cves, cs.compliant_cves, cs.at_risk_cves, cs.non_compliant_cves
        FROM compliance_scores cs
        WHERE cs.framework_id = ctf.framework_id
          AND cs.tenant_id = ctf.tenant_id
          AND cs.scope_type = 'tenant'
        ORDER BY cs.evaluated_at DESC
        LIMIT 1
    ) latest ON true
    WHERE ctf.tenant_id = $1 AND ctf.enabled = true
) sub
`

type GetOverallComplianceScoreRow struct {
	OverallScore     pgtype.Numeric `json:"overall_score"`
	TotalCves        int64          `json:"total_cves"`
	CompliantCves    int64          `json:"compliant_cves"`
	AtRiskCves       int64          `json:"at_risk_cves"`
	NonCompliantCves int64          `json:"non_compliant_cves"`
	FrameworkCount   int64          `json:"framework_count"`
}

func (q *Queries) GetOverallComplianceScore(ctx context.Context, tenantID pgtype.UUID) (GetOverallComplianceScoreRow, error) {
	row := q.db.QueryRow(ctx, getOverallComplianceScore, tenantID)
	var i GetOverallComplianceScoreRow
	err := row.Scan(
		&i.OverallScore,
		&i.TotalCves,
		&i.CompliantCves,
		&i.AtRiskCves,
		&i.NonCompliantCves,
		&i.FrameworkCount,
	)
	return i, err
}

const getRecentDeploymentStats = `-- name: GetRecentDeploymentStats :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE status IN ('completed', 'success'))::bigint AS succeeded,
  COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed
FROM deployments
WHERE tenant_id = $1 AND created_at > $2
`

type GetRecentDeploymentStatsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

type GetRecentDeploymentStatsRow struct {
	Total     int64 `json:"total"`
	Succeeded int64 `json:"succeeded"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) GetRecentDeploymentStats(ctx context.Context, arg GetRecentDeploymentStatsParams) (GetRecentDeploymentStatsRow, error) {
	row := q.db.QueryRow(ctx, getRecentDeploymentStats, arg.TenantID, arg.Since)
	var i GetRecentDeploymentStatsRow
	err := row.Scan(&i.Total, &i.Succeeded, &i.Failed)
	return i, err
}

const getTenantFramework = `-- name: GetTenantFramework :one
SELECT id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at FROM compliance_tenant_frameworks
WHERE tenant_id = $1 AND framework_id = $2
`

type GetTenantFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) GetTenantFramework(ctx context.Context, arg GetTenantFrameworkParams) (ComplianceTenantFramework, error) {
	row := q.db.QueryRow(ctx, getTenantFramework, arg.TenantID, arg.FrameworkID)
	var i ComplianceTenantFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.Enabled,
		&i.SlaOverrides,
		&i.ScoringMethod,
		&i.AtRiskThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantFrameworkByID = `-- name: GetTenantFrameworkByID :one
SELECT id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at FROM compliance_tenant_frameworks
WHERE id = $1 AND tenant_id = $2
`

type GetTenantFrameworkByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetTenantFrameworkByID(ctx context.Context, arg GetTenantFrameworkByIDParams) (ComplianceTenantFramework, error) {
	row := q.db.QueryRow(ctx, getTenantFrameworkByID, arg.ID, arg.TenantID)
	var i ComplianceTenantFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.Enabled,
		&i.SlaOverrides,
		&i.ScoringMethod,
		&i.AtRiskThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertControlResult = `-- name: InsertControlResult :one

INSERT INTO compliance_control_results (
    tenant_id, evaluation_run_id, framework_id, control_id,
    category, status, passing_endpoints, total_endpoints,
    remediation_hint, sla_deadline_at, days_overdue, evaluated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, evaluation_run_id, framework_id, control_id, category, status, passing_endpoints, total_endpoints, remediation_hint, sla_deadline_at, days_overdue, evaluated_at
`

type InsertControlResultParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	EvaluationRunID  pgtype.UUID        `json:"evaluation_run_id"`
	FrameworkID      string             `json:"framework_id"`
	ControlID        string             `json:"control_id"`
	Category         string             `json:"category"`
	Status           string             `json:"status"`
	PassingEndpoints int32              `json:"passing_endpoints"`
	TotalEndpoints   int32              `json:"total_endpoints"`
	RemediationHint  pgtype.Text        `json:"remediation_hint"`
	SlaDeadlineAt    pgtype.Timestamptz `json:"sla_deadline_at"`
	DaysOverdue      pgtype.Int4        `json:"days_overdue"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
}

// ------------------------------------------------------------
// Control Results
// ------------------------------------------------------------
func (q *Queries) InsertControlResult(ctx context.Context, arg InsertControlResultParams) (ComplianceControlResult, error) {
	row := q.db.QueryRow(ctx, insertControlResult,
		arg.TenantID,
		arg.EvaluationRunID,
		arg.FrameworkID,
		arg.ControlID,
		arg.Category,
		arg.Status,
		arg.PassingEndpoints,
		arg.TotalEndpoints,
		arg.RemediationHint,
		arg.SlaDeadlineAt,
		arg.DaysOverdue,
		arg.EvaluatedAt,
	)
	var i ComplianceControlResult
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvaluationRunID,
		&i.FrameworkID,
		&i.ControlID,
		&i.Category,
		&i.Status,
		&i.PassingEndpoints,
		&i.TotalEndpoints,
		&i.RemediationHint,
		&i.SlaDeadlineAt,
		&i.DaysOverdue,
		&i.EvaluatedAt,
	)
	return i, err
}

const insertEvaluation = `-- name: InsertEvaluation :one

INSERT INTO compliance_evaluations (
    tenant_id, evaluation_run_id, endpoint_id, cve_id,
    framework_id, control_id, state, sla_deadline_at,
    remediated_at, days_remaining, evaluated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, tenant_id, evaluation_run_id, endpoint_id, cve_id, framework_id, control_id, state, sla_deadline_at, remediated_at, days_remaining, evaluated_at
`

type InsertEvaluationParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	EvaluationRunID pgtype.UUID        `json:"evaluation_run_id"`
	EndpointID      pgtype.UUID        `json:"endpoint_id"`
	CveID           string             `json:"cve_id"`
	FrameworkID     string             `json:"framework_id"`
	ControlID       string             `json:"control_id"`
	State           string             `json:"state"`
	SlaDeadlineAt   pgtype.Timestamptz `json:"sla_deadline_at"`
	RemediatedAt    pgtype.Timestamptz `json:"remediated_at"`
	DaysRemaining   pgtype.Int4        `json:"days_remaining"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
}

// ------------------------------------------------------------
// Evaluations
// ------------------------------------------------------------
func (q *Queries) InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (ComplianceEvaluation, error) {
	row := q.db.QueryRow(ctx, insertEvaluation,
		arg.TenantID,
		arg.EvaluationRunID,
		arg.EndpointID,
		arg.CveID,
		arg.FrameworkID,
		arg.ControlID,
		arg.State,
		arg.SlaDeadlineAt,
		arg.RemediatedAt,
		arg.DaysRemaining,
		arg.EvaluatedAt,
	)
	var i ComplianceEvaluation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvaluationRunID,
		&i.EndpointID,
		&i.CveID,
		&i.FrameworkID,
		&i.ControlID,
		&i.State,
		&i.SlaDeadlineAt,
		&i.RemediatedAt,
		&i.DaysRemaining,
		&i.EvaluatedAt,
	)
	return i, err
}

const insertScore = `-- name: InsertScore :one

INSERT INTO compliance_scores (
    tenant_id, evaluation_run_id, framework_id, scope_type,
    scope_id, score, total_cves, compliant_cves, at_risk_cves,
    non_compliant_cves, late_remediation_cves, evaluated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12
)
RETURNING id, tenant_id, evaluation_run_id, framework_id, scope_type, scope_id, score, total_cves, compliant_cves, at_risk_cves, non_compliant_cves, late_remediation_cves, evaluated_at
`

type InsertScoreParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	EvaluationRunID     pgtype.UUID        `json:"evaluation_run_id"`
	FrameworkID         string             `json:"framework_id"`
	ScopeType           string             `json:"scope_type"`
	ScopeID             pgtype.UUID        `json:"scope_id"`
	Score               pgtype.Numeric     `json:"score"`
	TotalCves           int32              `json:"total_cves"`
	CompliantCves       int32              `json:"compliant_cves"`
	AtRiskCves          int32              `json:"at_risk_cves"`
	NonCompliantCves    int32              `json:"non_compliant_cves"`
	LateRemediationCves int32              `json:"late_remediation_cves"`
	EvaluatedAt         pgtype.Timestamptz `json:"evaluated_at"`
}

// ------------------------------------------------------------
// Scores
// ------------------------------------------------------------
func (q *Queries) InsertScore(ctx context.Context, arg InsertScoreParams) (ComplianceScore, error) {
	row := q.db.QueryRow(ctx, insertScore,
		arg.TenantID,
		arg.EvaluationRunID,
		arg.FrameworkID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Score,
		arg.TotalCves,
		arg.CompliantCves,
		arg.AtRiskCves,
		arg.NonCompliantCves,
		arg.LateRemediationCves,
		arg.EvaluatedAt,
	)
	var i ComplianceScore
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvaluationRunID,
		&i.FrameworkID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Score,
		&i.TotalCves,
		&i.CompliantCves,
		&i.AtRiskCves,
		&i.NonCompliantCves,
		&i.LateRemediationCves,
		&i.EvaluatedAt,
	)
	return i, err
}

const listAffectedEndpointCVEs = `-- name: ListAffectedEndpointCVEs :many

SELECT
    ec.id AS endpoint_cve_id,
    ec.endpoint_id,
    ec.cve_id AS cve_ref_id,
    ec.status,
    ec.detected_at,
    ec.resolved_at,
    ec.risk_score,
    c.cve_id AS cve_identifier,
    c.severity,
    c.cvss_v3_score,
    c.published_at,
    e.hostname,
    e.os_family
FROM endpoint_cves ec
JOIN cves c ON ec.cve_id = c.id AND ec.tenant_id = c.tenant_id
JOIN endpoints e ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
WHERE ec.tenant_id = $1
  AND ec.status = 'affected'
ORDER BY ec.endpoint_id, c.cvss_v3_score DESC NULLS LAST
LIMIT 50000
`

type ListAffectedEndpointCVEsRow struct {
	EndpointCveID pgtype.UUID        `json:"endpoint_cve_id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	CveRefID      pgtype.UUID        `json:"cve_ref_id"`
	Status        string             `json:"status"`
	DetectedAt    pgtype.Timestamptz `json:"detected_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	RiskScore     pgtype.Numeric     `json:"risk_score"`
	CveIdentifier string             `json:"cve_identifier"`
	Severity      string             `json:"severity"`
	CvssV3Score   pgtype.Numeric     `json:"cvss_v3_score"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Hostname      string             `json:"hostname"`
	OsFamily      string             `json:"os_family"`
}

// ------------------------------------------------------------
// Data needed by evaluator (joins across existing tables)
// ------------------------------------------------------------
func (q *Queries) ListAffectedEndpointCVEs(ctx context.Context, tenantID pgtype.UUID) ([]ListAffectedEndpointCVEsRow, error) {
	rows, err := q.db.Query(ctx, listAffectedEndpointCVEs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedEndpointCVEsRow{}
	for rows.Next() {
		var i ListAffectedEndpointCVEsRow
		if err := rows.Scan(
			&i.EndpointCveID,
			&i.EndpointID,
			&i.CveRefID,
			&i.Status,
			&i.DetectedAt,
			&i.ResolvedAt,
			&i.RiskScore,
			&i.CveIdentifier,
			&i.Severity,
			&i.CvssV3Score,
			&i.PublishedAt,
			&i.Hostname,
			&i.OsFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTenantIDs = `-- name: ListAllTenantIDs :many
SELECT id FROM tenants
LIMIT 10000
`

func (q *Queries) ListAllTenantIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllTenantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlResultsByFramework = `-- name: ListControlResultsByFramework :many
SELECT id, tenant_id, evaluation_run_id, framework_id, control_id, category, status, passing_endpoints, total_endpoints, remediation_hint, sla_deadline_at, days_overdue, evaluated_at FROM compliance_control_results ccr
WHERE ccr.tenant_id = $1
  AND ccr.framework_id = $2
  AND ccr.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_control_results sub
      WHERE sub.tenant_id = $1 AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY ccr.category, ccr.control_id
`

type ListControlResultsByFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) ListControlResultsByFramework(ctx context.Context, arg ListControlResultsByFrameworkParams) ([]ComplianceControlResult, error) {
	rows, err := q.db.Query(ctx, listControlResultsByFramework, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceControlResult{}
	for rows.Next() {
		var i ComplianceControlResult
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.FrameworkID,
			&i.ControlID,
			&i.Category,
			&i.Status,
			&i.PassingEndpoints,
			&i.TotalEndpoints,
			&i.RemediationHint,
			&i.SlaDeadlineAt,
			&i.DaysOverdue,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTenantFrameworks = `-- name: ListEnabledTenantFrameworks :many
SELECT id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at FROM compliance_tenant_frameworks
WHERE tenant_id = $1 AND enabled = true
ORDER BY framework_id
LIMIT 100
`

func (q *Queries) ListEnabledTenantFrameworks(ctx context.Context, tenantID pgtype.UUID) ([]ComplianceTenantFramework, error) {
	rows, err := q.db.Query(ctx, listEnabledTenantFrameworks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceTenantFramework{}
	for rows.Next() {
		var i ComplianceTenantFramework
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FrameworkID,
			&i.Enabled,
			&i.SlaOverrides,
			&i.ScoringMethod,
			&i.AtRiskThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointComplianceFlags = `-- name: ListEndpointComplianceFlags :many
SELECT
  e.id AS endpoint_id,
  -- asset_inventory: has hardware data
  (e.cpu_model IS NOT NULL AND e.memory_total_mb > 0)::boolean AS has_hardware,
  -- asset_inventory / agent_monitoring: recent heartbeat
  (e.last_heartbeat IS NOT NULL AND e.last_heartbeat > $1)::boolean AS has_recent_heartbeat,
  -- software_inventory: recent inventory scan
  EXISTS(
    SELECT 1 FROM endpoint_inventories ei
    WHERE ei.endpoint_id = e.id AND ei.tenant_id = e.tenant_id
      AND ei.scanned_at > $2
  )::boolean AS has_recent_scan,
  -- vuln_scanning: has CVE scan data
  EXISTS(
    SELECT 1 FROM endpoint_cves ec
    WHERE ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
  )::boolean AS has_cve_data,
  -- kev_compliance: no CISA KEV vulnerabilities
  NOT EXISTS(
    SELECT 1 FROM endpoint_cves ec
    JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
    WHERE ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
      AND ec.status = 'affected' AND c.cisa_kev_due_date IS NOT NULL
  )::boolean AS kev_clean,
  -- critical_vuln_remediation: no stale critical/high CVEs
  NOT EXISTS(
    SELECT 1 FROM endpoint_cves ec
    JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
    WHERE ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
      AND ec.status = 'affected' AND c.severity IN ('critical', 'high')
      AND ec.detected_at < $3
  )::boolean AS no_stale_critical
FROM endpoints e
WHERE e.tenant_id = $4 AND e.status != 'decommissioned'
ORDER BY e.hostname
LIMIT 10000
`

type ListEndpointComplianceFlagsParams struct {
	HeartbeatSince pgtype.Timestamptz `json:"heartbeat_since"`
	ScanSince      pgtype.Timestamptz `json:"scan_since"`
	CveMaxAge      pgtype.Timestamptz `json:"cve_max_age"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
}

type ListEndpointComplianceFlagsRow struct {
	EndpointID         pgtype.UUID `json:"endpoint_id"`
	HasHardware        bool        `json:"has_hardware"`
	HasRecentHeartbeat bool        `json:"has_recent_heartbeat"`
	HasRecentScan      bool        `json:"has_recent_scan"`
	HasCveData         bool        `json:"has_cve_data"`
	KevClean           pgtype.Bool `json:"kev_clean"`
	NoStaleCritical    pgtype.Bool `json:"no_stale_critical"`
}

// Returns per-endpoint boolean flags for each check type.
// Used to compute individual endpoint compliance scores.
func (q *Queries) ListEndpointComplianceFlags(ctx context.Context, arg ListEndpointComplianceFlagsParams) ([]ListEndpointComplianceFlagsRow, error) {
	rows, err := q.db.Query(ctx, listEndpointComplianceFlags,
		arg.HeartbeatSince,
		arg.ScanSince,
		arg.CveMaxAge,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointComplianceFlagsRow{}
	for rows.Next() {
		var i ListEndpointComplianceFlagsRow
		if err := rows.Scan(
			&i.EndpointID,
			&i.HasHardware,
			&i.HasRecentHeartbeat,
			&i.HasRecentScan,
			&i.HasCveData,
			&i.KevClean,
			&i.NoStaleCritical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointScoresByFramework = `-- name: ListEndpointScoresByFramework :many
SELECT id, tenant_id, evaluation_run_id, framework_id, scope_type, scope_id, score, total_cves, compliant_cves, at_risk_cves, non_compliant_cves, late_remediation_cves, evaluated_at FROM compliance_scores cs
WHERE cs.tenant_id = $1
  AND cs.framework_id = $2
  AND cs.scope_type = 'endpoint'
  AND cs.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_scores sub
      WHERE sub.tenant_id = $1 AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY cs.score ASC
`

type ListEndpointScoresByFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) ListEndpointScoresByFramework(ctx context.Context, arg ListEndpointScoresByFrameworkParams) ([]ComplianceScore, error) {
	rows, err := q.db.Query(ctx, listEndpointScoresByFramework, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceScore{}
	for rows.Next() {
		var i ComplianceScore
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.FrameworkID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Score,
			&i.TotalCves,
			&i.CompliantCves,
			&i.AtRiskCves,
			&i.NonCompliantCves,
			&i.LateRemediationCves,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationsByEndpoint = `-- name: ListEvaluationsByEndpoint :many
SELECT id, tenant_id, evaluation_run_id, endpoint_id, cve_id, framework_id, control_id, state, sla_deadline_at, remediated_at, days_remaining, evaluated_at FROM compliance_evaluations ce
WHERE ce.tenant_id = $1
  AND ce.endpoint_id = $2
  AND ce.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_evaluations sub
      WHERE sub.tenant_id = $1
        AND sub.framework_id = ce.framework_id
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY ce.framework_id, ce.control_id
`

type ListEvaluationsByEndpointParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) ListEvaluationsByEndpoint(ctx context.Context, arg ListEvaluationsByEndpointParams) ([]ComplianceEvaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluationsByEndpoint, arg.TenantID, arg.EndpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceEvaluation{}
	for rows.Next() {
		var i ComplianceEvaluation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.EndpointID,
			&i.CveID,
			&i.FrameworkID,
			&i.ControlID,
			&i.State,
			&i.SlaDeadlineAt,
			&i.RemediatedAt,
			&i.DaysRemaining,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationsByFramework = `-- name: ListEvaluationsByFramework :many
SELECT id, tenant_id, evaluation_run_id, endpoint_id, cve_id, framework_id, control_id, state, sla_deadline_at, remediated_at, days_remaining, evaluated_at FROM compliance_evaluations ce
WHERE ce.tenant_id = $1
  AND ce.framework_id = $2
  AND ce.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_evaluations sub
      WHERE sub.tenant_id = $1
        AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY ce.endpoint_id, ce.control_id
`

type ListEvaluationsByFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) ListEvaluationsByFramework(ctx context.Context, arg ListEvaluationsByFrameworkParams) ([]ComplianceEvaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluationsByFramework, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceEvaluation{}
	for rows.Next() {
		var i ComplianceEvaluation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.EndpointID,
			&i.CveID,
			&i.FrameworkID,
			&i.ControlID,
			&i.State,
			&i.SlaDeadlineAt,
			&i.RemediatedAt,
			&i.DaysRemaining,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonCompliantEndpointsByFramework = `-- name: ListNonCompliantEndpointsByFramework :many
SELECT cs.scope_id AS endpoint_id, cs.score, cs.total_cves, cs.compliant_cves,
       cs.at_risk_cves, cs.non_compliant_cves, cs.late_remediation_cves,
       e.hostname, e.os_family
FROM compliance_scores cs
JOIN endpoints e ON cs.scope_id = e.id AND cs.tenant_id = e.tenant_id
WHERE cs.tenant_id = $1
  AND cs.framework_id = $2
  AND cs.scope_type = 'endpoint'
  AND cs.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_scores sub
      WHERE sub.tenant_id = $1 AND sub.framework_id = $2
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY cs.score ASC
LIMIT 100
`

type ListNonCompliantEndpointsByFrameworkParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

type ListNonCompliantEndpointsByFrameworkRow struct {
	EndpointID          pgtype.UUID    `json:"endpoint_id"`
	Score               pgtype.Numeric `json:"score"`
	TotalCves           int32          `json:"total_cves"`
	CompliantCves       int32          `json:"compliant_cves"`
	AtRiskCves          int32          `json:"at_risk_cves"`
	NonCompliantCves    int32          `json:"non_compliant_cves"`
	LateRemediationCves int32          `json:"late_remediation_cves"`
	Hostname            string         `json:"hostname"`
	OsFamily            string         `json:"os_family"`
}

func (q *Queries) ListNonCompliantEndpointsByFramework(ctx context.Context, arg ListNonCompliantEndpointsByFrameworkParams) ([]ListNonCompliantEndpointsByFrameworkRow, error) {
	rows, err := q.db.Query(ctx, listNonCompliantEndpointsByFramework, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonCompliantEndpointsByFrameworkRow{}
	for rows.Next() {
		var i ListNonCompliantEndpointsByFrameworkRow
		if err := rows.Scan(
			&i.EndpointID,
			&i.Score,
			&i.TotalCves,
			&i.CompliantCves,
			&i.AtRiskCves,
			&i.NonCompliantCves,
			&i.LateRemediationCves,
			&i.Hostname,
			&i.OsFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonDecommissionedEndpointIDs = `-- name: ListNonDecommissionedEndpointIDs :many
SELECT id FROM endpoints
WHERE tenant_id = $1 AND status != 'decommissioned'
ORDER BY hostname
LIMIT 10000
`

func (q *Queries) ListNonDecommissionedEndpointIDs(ctx context.Context, tenantID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNonDecommissionedEndpointIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueControls = `-- name: ListOverdueControls :many
WITH latest_runs AS (
    SELECT DISTINCT ON (framework_id) framework_id, evaluation_run_id
    FROM compliance_control_results WHERE tenant_id = $1
    ORDER BY framework_id, evaluated_at DESC
)
SELECT ccr.id, ccr.tenant_id, ccr.evaluation_run_id, ccr.framework_id, ccr.control_id, ccr.category, ccr.status, ccr.passing_endpoints, ccr.total_endpoints, ccr.remediation_hint, ccr.sla_deadline_at, ccr.days_overdue, ccr.evaluated_at FROM compliance_control_results ccr
JOIN latest_runs lr ON ccr.framework_id = lr.framework_id AND ccr.evaluation_run_id = lr.evaluation_run_id
JOIN compliance_tenant_frameworks ctf ON ctf.tenant_id = ccr.tenant_id AND ctf.framework_id = ccr.framework_id AND ctf.enabled = true
WHERE ccr.tenant_id = $1
  AND ccr.status IN ('fail', 'partial')
  AND ccr.sla_deadline_at IS NOT NULL
  AND ccr.sla_deadline_at < now()
ORDER BY ccr.days_overdue DESC NULLS LAST
LIMIT $3::int OFFSET $2::int
`

type ListOverdueControlsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

func (q *Queries) ListOverdueControls(ctx context.Context, arg ListOverdueControlsParams) ([]ComplianceControlResult, error) {
	rows, err := q.db.Query(ctx, listOverdueControls, arg.TenantID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceControlResult{}
	for rows.Next() {
		var i ComplianceControlResult
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.FrameworkID,
			&i.ControlID,
			&i.Category,
			&i.Status,
			&i.PassingEndpoints,
			&i.TotalEndpoints,
			&i.RemediationHint,
			&i.SlaDeadlineAt,
			&i.DaysOverdue,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLADeadlinesApproaching = `-- name: ListSLADeadlinesApproaching :many
SELECT id, tenant_id, evaluation_run_id, endpoint_id, cve_id, framework_id, control_id, state, sla_deadline_at, remediated_at, days_remaining, evaluated_at FROM compliance_evaluations ce
WHERE ce.tenant_id = $1
  AND ce.state IN ('AT_RISK', 'NON_COMPLIANT')
  AND ce.sla_deadline_at IS NOT NULL
  AND ce.sla_deadline_at <= $2
  AND ce.evaluation_run_id = (
      SELECT sub.evaluation_run_id FROM compliance_evaluations sub
      WHERE sub.tenant_id = $1
        AND sub.framework_id = ce.framework_id
      ORDER BY sub.evaluated_at DESC
      LIMIT 1
  )
ORDER BY ce.sla_deadline_at ASC
`

type ListSLADeadlinesApproachingParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DeadlineBefore pgtype.Timestamptz `json:"deadline_before"`
}

func (q *Queries) ListSLADeadlinesApproaching(ctx context.Context, arg ListSLADeadlinesApproachingParams) ([]ComplianceEvaluation, error) {
	rows, err := q.db.Query(ctx, listSLADeadlinesApproaching, arg.TenantID, arg.DeadlineBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceEvaluation{}
	for rows.Next() {
		var i ComplianceEvaluation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.EndpointID,
			&i.CveID,
			&i.FrameworkID,
			&i.ControlID,
			&i.State,
			&i.SlaDeadlineAt,
			&i.RemediatedAt,
			&i.DaysRemaining,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreTrend = `-- name: ListScoreTrend :many
SELECT id, tenant_id, evaluation_run_id, framework_id, scope_type, scope_id, score, total_cves, compliant_cves, at_risk_cves, non_compliant_cves, late_remediation_cves, evaluated_at FROM (
    SELECT DISTINCT ON (cs.evaluation_run_id)
        cs.id, cs.tenant_id, cs.evaluation_run_id, cs.framework_id,
        cs.scope_type, cs.scope_id, cs.score, cs.total_cves, cs.compliant_cves,
        cs.at_risk_cves, cs.non_compliant_cves, cs.late_remediation_cves, cs.evaluated_at
    FROM compliance_scores cs
    WHERE cs.tenant_id = $1
      AND cs.framework_id = $2
      AND cs.scope_type = 'tenant'
    ORDER BY cs.evaluation_run_id, cs.evaluated_at DESC
) sub
ORDER BY sub.evaluated_at ASC
`

type ListScoreTrendParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID string      `json:"framework_id"`
}

func (q *Queries) ListScoreTrend(ctx context.Context, arg ListScoreTrendParams) ([]ComplianceScore, error) {
	rows, err := q.db.Query(ctx, listScoreTrend, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceScore{}
	for rows.Next() {
		var i ComplianceScore
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EvaluationRunID,
			&i.FrameworkID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Score,
			&i.TotalCves,
			&i.CompliantCves,
			&i.AtRiskCves,
			&i.NonCompliantCves,
			&i.LateRemediationCves,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantFrameworks = `-- name: ListTenantFrameworks :many
SELECT id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at FROM compliance_tenant_frameworks
WHERE tenant_id = $1
ORDER BY framework_id
LIMIT 100
`

func (q *Queries) ListTenantFrameworks(ctx context.Context, tenantID pgtype.UUID) ([]ComplianceTenantFramework, error) {
	rows, err := q.db.Query(ctx, listTenantFrameworks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceTenantFramework{}
	for rows.Next() {
		var i ComplianceTenantFramework
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FrameworkID,
			&i.Enabled,
			&i.SlaOverrides,
			&i.ScoringMethod,
			&i.AtRiskThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpointScoreByID = `-- name: UpdateEndpointScoreByID :exec
UPDATE compliance_scores
SET score = $1
WHERE tenant_id = $2
  AND evaluation_run_id = $3
  AND framework_id = $4
  AND scope_type = 'endpoint'
  AND scope_id = $5
`

type UpdateEndpointScoreByIDParams struct {
	Score           pgtype.Numeric `json:"score"`
	TenantID        pgtype.UUID    `json:"tenant_id"`
	EvaluationRunID pgtype.UUID    `json:"evaluation_run_id"`
	FrameworkID     string         `json:"framework_id"`
	ScopeID         pgtype.UUID    `json:"scope_id"`
}

func (q *Queries) UpdateEndpointScoreByID(ctx context.Context, arg UpdateEndpointScoreByIDParams) error {
	_, err := q.db.Exec(ctx, updateEndpointScoreByID,
		arg.Score,
		arg.TenantID,
		arg.EvaluationRunID,
		arg.FrameworkID,
		arg.ScopeID,
	)
	return err
}

const updateEndpointScoresForRun = `-- name: UpdateEndpointScoresForRun :exec
UPDATE compliance_scores
SET score = $1
WHERE tenant_id = $2
  AND evaluation_run_id = $3
  AND framework_id = $4
  AND scope_type = 'endpoint'
`

type UpdateEndpointScoresForRunParams struct {
	Score           pgtype.Numeric `json:"score"`
	TenantID        pgtype.UUID    `json:"tenant_id"`
	EvaluationRunID pgtype.UUID    `json:"evaluation_run_id"`
	FrameworkID     string         `json:"framework_id"`
}

func (q *Queries) UpdateEndpointScoresForRun(ctx context.Context, arg UpdateEndpointScoresForRunParams) error {
	_, err := q.db.Exec(ctx, updateEndpointScoresForRun,
		arg.Score,
		arg.TenantID,
		arg.EvaluationRunID,
		arg.FrameworkID,
	)
	return err
}

const updateTenantFramework = `-- name: UpdateTenantFramework :one
UPDATE compliance_tenant_frameworks
SET enabled = $1,
    sla_overrides = $2,
    scoring_method = $3,
    at_risk_threshold = $4,
    updated_at = now()
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, framework_id, enabled, sla_overrides, scoring_method, at_risk_threshold, created_at, updated_at
`

type UpdateTenantFrameworkParams struct {
	Enabled         bool           `json:"enabled"`
	SlaOverrides    []byte         `json:"sla_overrides"`
	ScoringMethod   string         `json:"scoring_method"`
	AtRiskThreshold pgtype.Numeric `json:"at_risk_threshold"`
	ID              pgtype.UUID    `json:"id"`
	TenantID        pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateTenantFramework(ctx context.Context, arg UpdateTenantFrameworkParams) (ComplianceTenantFramework, error) {
	row := q.db.QueryRow(ctx, updateTenantFramework,
		arg.Enabled,
		arg.SlaOverrides,
		arg.ScoringMethod,
		arg.AtRiskThreshold,
		arg.ID,
		arg.TenantID,
	)
	var i ComplianceTenantFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.Enabled,
		&i.SlaOverrides,
		&i.ScoringMethod,
		&i.AtRiskThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
