// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConfigOverride = `-- name: DeleteConfigOverride :exec
DELETE FROM config_overrides
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3 AND module = $4
`

type DeleteConfigOverrideParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Module    string      `json:"module"`
}

func (q *Queries) DeleteConfigOverride(ctx context.Context, arg DeleteConfigOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteConfigOverride,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Module,
	)
	return err
}

const getCommsConfigForEndpoint = `-- name: GetCommsConfigForEndpoint :one
SELECT id, tenant_id, scope_type, scope_id, module, config, updated_by, updated_at FROM config_overrides
WHERE tenant_id = $1 AND scope_type = 'endpoint' AND scope_id = $2 AND module = 'comms'
  AND ($3::timestamptz IS NULL OR updated_at > $3)
`

type GetCommsConfigForEndpointParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	UpdatedAfter pgtype.Timestamptz `json:"updated_after"`
}

// Returns the comms config override for a specific endpoint, if it was updated
// after the given timestamp (used for config push via heartbeat).
func (q *Queries) GetCommsConfigForEndpoint(ctx context.Context, arg GetCommsConfigForEndpointParams) (ConfigOverride, error) {
	row := q.db.QueryRow(ctx, getCommsConfigForEndpoint, arg.TenantID, arg.ScopeID, arg.UpdatedAfter)
	var i ConfigOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Module,
		&i.Config,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigOverride = `-- name: GetConfigOverride :one
SELECT id, tenant_id, scope_type, scope_id, module, config, updated_by, updated_at FROM config_overrides
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3 AND module = $4
`

type GetConfigOverrideParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Module    string      `json:"module"`
}

func (q *Queries) GetConfigOverride(ctx context.Context, arg GetConfigOverrideParams) (ConfigOverride, error) {
	row := q.db.QueryRow(ctx, getConfigOverride,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Module,
	)
	var i ConfigOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Module,
		&i.Config,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigOverridesByScope = `-- name: ListConfigOverridesByScope :many
SELECT id, tenant_id, scope_type, scope_id, module, config, updated_by, updated_at FROM config_overrides
WHERE tenant_id = $1 AND scope_type = $2 AND scope_id = $3
ORDER BY module
LIMIT 100
`

type ListConfigOverridesByScopeParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
}

func (q *Queries) ListConfigOverridesByScope(ctx context.Context, arg ListConfigOverridesByScopeParams) ([]ConfigOverride, error) {
	rows, err := q.db.Query(ctx, listConfigOverridesByScope, arg.TenantID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigOverride{}
	for rows.Next() {
		var i ConfigOverride
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Module,
			&i.Config,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigOverridesByTenant = `-- name: ListConfigOverridesByTenant :many
SELECT id, tenant_id, scope_type, scope_id, module, config, updated_by, updated_at FROM config_overrides
WHERE tenant_id = $1
ORDER BY scope_type, module
LIMIT 100
`

func (q *Queries) ListConfigOverridesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ConfigOverride, error) {
	rows, err := q.db.Query(ctx, listConfigOverridesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigOverride{}
	for rows.Next() {
		var i ConfigOverride
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Module,
			&i.Config,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigOverride = `-- name: UpsertConfigOverride :one
INSERT INTO config_overrides (tenant_id, scope_type, scope_id, module, config, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, scope_type, scope_id, module)
DO UPDATE SET config = EXCLUDED.config, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING id, tenant_id, scope_type, scope_id, module, config, updated_by, updated_at
`

type UpsertConfigOverrideParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	Module    string      `json:"module"`
	Config    []byte      `json:"config"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertConfigOverride(ctx context.Context, arg UpsertConfigOverrideParams) (ConfigOverride, error) {
	row := q.db.QueryRow(ctx, upsertConfigOverride,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Module,
		arg.Config,
		arg.UpdatedBy,
	)
	var i ConfigOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Module,
		&i.Config,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
