// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForBulkCreateDeploymentTargets implements pgx.CopyFromSource.
type iteratorForBulkCreateDeploymentTargets struct {
	rows                 []BulkCreateDeploymentTargetsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateDeploymentTargets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateDeploymentTargets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TenantID,
		r.rows[0].DeploymentID,
		r.rows[0].EndpointID,
		r.rows[0].PatchID,
		r.rows[0].Status,
		r.rows[0].WaveID,
	}, nil
}

func (r iteratorForBulkCreateDeploymentTargets) Err() error {
	return nil
}

func (q *Queries) BulkCreateDeploymentTargets(ctx context.Context, arg []BulkCreateDeploymentTargetsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"deployment_targets"}, []string{"tenant_id", "deployment_id", "endpoint_id", "patch_id", "status", "wave_id"}, &iteratorForBulkCreateDeploymentTargets{rows: arg})
}
