// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_compliance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomControl = `-- name: CreateCustomControl :one

INSERT INTO custom_compliance_controls (tenant_id, framework_id, control_id, name, description, category, remediation_hint, sla_tiers, check_type, check_config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, framework_id, control_id, name, description, category, remediation_hint, sla_tiers, created_at, check_type, check_config
`

type CreateCustomControlParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	FrameworkID     pgtype.UUID `json:"framework_id"`
	ControlID       string      `json:"control_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Category        string      `json:"category"`
	RemediationHint pgtype.Text `json:"remediation_hint"`
	SlaTiers        []byte      `json:"sla_tiers"`
	CheckType       string      `json:"check_type"`
	CheckConfig     []byte      `json:"check_config"`
}

// ------------------------------------------------------------
// Custom Controls
// ------------------------------------------------------------
func (q *Queries) CreateCustomControl(ctx context.Context, arg CreateCustomControlParams) (CustomComplianceControl, error) {
	row := q.db.QueryRow(ctx, createCustomControl,
		arg.TenantID,
		arg.FrameworkID,
		arg.ControlID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.RemediationHint,
		arg.SlaTiers,
		arg.CheckType,
		arg.CheckConfig,
	)
	var i CustomComplianceControl
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.ControlID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.RemediationHint,
		&i.SlaTiers,
		&i.CreatedAt,
		&i.CheckType,
		&i.CheckConfig,
	)
	return i, err
}

const createCustomFramework = `-- name: CreateCustomFramework :one


INSERT INTO custom_compliance_frameworks (tenant_id, name, version, description, scoring_method)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, version, description, scoring_method, created_at, updated_at
`

type CreateCustomFrameworkParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          string      `json:"name"`
	Version       string      `json:"version"`
	Description   pgtype.Text `json:"description"`
	ScoringMethod string      `json:"scoring_method"`
}

// ============================================================
// Custom Compliance Framework queries
// ============================================================
// ------------------------------------------------------------
// Custom Frameworks
// ------------------------------------------------------------
func (q *Queries) CreateCustomFramework(ctx context.Context, arg CreateCustomFrameworkParams) (CustomComplianceFramework, error) {
	row := q.db.QueryRow(ctx, createCustomFramework,
		arg.TenantID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.ScoringMethod,
	)
	var i CustomComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.ScoringMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomControls = `-- name: DeleteCustomControls :exec
DELETE FROM custom_compliance_controls
WHERE tenant_id = $1 AND framework_id = $2
`

type DeleteCustomControlsParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID pgtype.UUID `json:"framework_id"`
}

func (q *Queries) DeleteCustomControls(ctx context.Context, arg DeleteCustomControlsParams) error {
	_, err := q.db.Exec(ctx, deleteCustomControls, arg.TenantID, arg.FrameworkID)
	return err
}

const deleteCustomFramework = `-- name: DeleteCustomFramework :exec
DELETE FROM custom_compliance_frameworks
WHERE id = $1 AND tenant_id = $2
`

type DeleteCustomFrameworkParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCustomFramework(ctx context.Context, arg DeleteCustomFrameworkParams) error {
	_, err := q.db.Exec(ctx, deleteCustomFramework, arg.ID, arg.TenantID)
	return err
}

const getCustomFramework = `-- name: GetCustomFramework :one
SELECT id, tenant_id, name, version, description, scoring_method, created_at, updated_at FROM custom_compliance_frameworks
WHERE id = $1 AND tenant_id = $2
`

type GetCustomFrameworkParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCustomFramework(ctx context.Context, arg GetCustomFrameworkParams) (CustomComplianceFramework, error) {
	row := q.db.QueryRow(ctx, getCustomFramework, arg.ID, arg.TenantID)
	var i CustomComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.ScoringMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomControls = `-- name: ListCustomControls :many
SELECT id, tenant_id, framework_id, control_id, name, description, category, remediation_hint, sla_tiers, created_at, check_type, check_config FROM custom_compliance_controls
WHERE tenant_id = $1 AND framework_id = $2
ORDER BY category ASC, control_id ASC
LIMIT 1000
`

type ListCustomControlsParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	FrameworkID pgtype.UUID `json:"framework_id"`
}

func (q *Queries) ListCustomControls(ctx context.Context, arg ListCustomControlsParams) ([]CustomComplianceControl, error) {
	rows, err := q.db.Query(ctx, listCustomControls, arg.TenantID, arg.FrameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomComplianceControl{}
	for rows.Next() {
		var i CustomComplianceControl
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FrameworkID,
			&i.ControlID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.RemediationHint,
			&i.SlaTiers,
			&i.CreatedAt,
			&i.CheckType,
			&i.CheckConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFrameworks = `-- name: ListCustomFrameworks :many
SELECT cf.id, cf.tenant_id, cf.name, cf.version, cf.description, cf.scoring_method, cf.created_at, cf.updated_at,
  (SELECT COUNT(*) FROM custom_compliance_controls cc
   WHERE cc.framework_id = cf.id AND cc.tenant_id = cf.tenant_id)::bigint AS control_count
FROM custom_compliance_frameworks cf
WHERE cf.tenant_id = $1
ORDER BY cf.created_at DESC
LIMIT 100
`

type ListCustomFrameworksRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	Version       string             `json:"version"`
	Description   pgtype.Text        `json:"description"`
	ScoringMethod string             `json:"scoring_method"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ControlCount  int64              `json:"control_count"`
}

func (q *Queries) ListCustomFrameworks(ctx context.Context, tenantID pgtype.UUID) ([]ListCustomFrameworksRow, error) {
	rows, err := q.db.Query(ctx, listCustomFrameworks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomFrameworksRow{}
	for rows.Next() {
		var i ListCustomFrameworksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.ScoringMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ControlCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFramework = `-- name: UpdateCustomFramework :one
UPDATE custom_compliance_frameworks
SET name           = $1,
    version        = $2,
    description    = $3,
    scoring_method = $4,
    updated_at     = now()
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, name, version, description, scoring_method, created_at, updated_at
`

type UpdateCustomFrameworkParams struct {
	Name          string      `json:"name"`
	Version       string      `json:"version"`
	Description   pgtype.Text `json:"description"`
	ScoringMethod string      `json:"scoring_method"`
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateCustomFramework(ctx context.Context, arg UpdateCustomFrameworkParams) (CustomComplianceFramework, error) {
	row := q.db.QueryRow(ctx, updateCustomFramework,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.ScoringMethod,
		arg.ID,
		arg.TenantID,
	)
	var i CustomComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.ScoringMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
