// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cve_sync.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCVEDBIDsByCVEIDs = `-- name: GetCVEDBIDsByCVEIDs :many
SELECT id, cve_id FROM cves
WHERE tenant_id = $1 AND cve_id = ANY($2::text[])
`

type GetCVEDBIDsByCVEIDsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	CveIds   []string    `json:"cve_ids"`
}

type GetCVEDBIDsByCVEIDsRow struct {
	ID    pgtype.UUID `json:"id"`
	CveID string      `json:"cve_id"`
}

func (q *Queries) GetCVEDBIDsByCVEIDs(ctx context.Context, arg GetCVEDBIDsByCVEIDsParams) ([]GetCVEDBIDsByCVEIDsRow, error) {
	rows, err := q.db.Query(ctx, getCVEDBIDsByCVEIDs, arg.TenantID, arg.CveIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCVEDBIDsByCVEIDsRow{}
	for rows.Next() {
		var i GetCVEDBIDsByCVEIDsRow
		if err := rows.Scan(&i.ID, &i.CveID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVESyncCursor = `-- name: GetCVESyncCursor :one
SELECT id, tenant_id, source, last_synced, created_at, updated_at FROM cve_sync_cursors
WHERE tenant_id = $1 AND source = $2
`

type GetCVESyncCursorParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Source   string      `json:"source"`
}

func (q *Queries) GetCVESyncCursor(ctx context.Context, arg GetCVESyncCursorParams) (CveSyncCursor, error) {
	row := q.db.QueryRow(ctx, getCVESyncCursor, arg.TenantID, arg.Source)
	var i CveSyncCursor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCVEsByOsFamily = `-- name: ListCVEsByOsFamily :many
SELECT c.id, c.cve_id, c.severity, c.cvss_v3_score, c.cisa_kev_due_date,
       c.exploit_available, c.published_at, '' AS version_end_excluding, '' AS version_end_including
FROM cves c
WHERE c.tenant_id = $1
  AND c.description ILIKE '%' || $2 || '%'
LIMIT 1000
`

type ListCVEsByOsFamilyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  pgtype.Text `json:"column_2"`
}

type ListCVEsByOsFamilyRow struct {
	ID                  pgtype.UUID        `json:"id"`
	CveID               string             `json:"cve_id"`
	Severity            string             `json:"severity"`
	CvssV3Score         pgtype.Numeric     `json:"cvss_v3_score"`
	CisaKevDueDate      pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable    bool               `json:"exploit_available"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	VersionEndExcluding string             `json:"version_end_excluding"`
	VersionEndIncluding string             `json:"version_end_including"`
}

func (q *Queries) ListCVEsByOsFamily(ctx context.Context, arg ListCVEsByOsFamilyParams) ([]ListCVEsByOsFamilyRow, error) {
	rows, err := q.db.Query(ctx, listCVEsByOsFamily, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVEsByOsFamilyRow{}
	for rows.Next() {
		var i ListCVEsByOsFamilyRow
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.CvssV3Score,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.PublishedAt,
			&i.VersionEndExcluding,
			&i.VersionEndIncluding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEsByPackageName = `-- name: ListCVEsByPackageName :many
SELECT c.id, c.tenant_id, c.cve_id, c.severity, c.description, c.published_at, c.created_at, c.updated_at, c.cvss_v3_score, c.cvss_v3_vector, c.cisa_kev_due_date, c.exploit_available, c.nvd_last_modified, c.attack_vector, c.external_references, c.cwe_id, c.source,
       pc.version_end_excluding,
       pc.version_end_including
FROM cves c
JOIN patch_cves pc ON c.id = pc.cve_id AND c.tenant_id = pc.tenant_id
JOIN patches p ON pc.patch_id = p.id AND pc.tenant_id = p.tenant_id
WHERE p.package_name = $1 AND p.tenant_id = $2
LIMIT 1000
`

type ListCVEsByPackageNameParams struct {
	PackageName string      `json:"package_name"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

type ListCVEsByPackageNameRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	CveID               string             `json:"cve_id"`
	Severity            string             `json:"severity"`
	Description         pgtype.Text        `json:"description"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CvssV3Score         pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector        pgtype.Text        `json:"cvss_v3_vector"`
	CisaKevDueDate      pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable    bool               `json:"exploit_available"`
	NvdLastModified     pgtype.Timestamptz `json:"nvd_last_modified"`
	AttackVector        pgtype.Text        `json:"attack_vector"`
	ExternalReferences  []byte             `json:"external_references"`
	CweID               pgtype.Text        `json:"cwe_id"`
	Source              string             `json:"source"`
	VersionEndExcluding string             `json:"version_end_excluding"`
	VersionEndIncluding string             `json:"version_end_including"`
}

func (q *Queries) ListCVEsByPackageName(ctx context.Context, arg ListCVEsByPackageNameParams) ([]ListCVEsByPackageNameRow, error) {
	rows, err := q.db.Query(ctx, listCVEsByPackageName, arg.PackageName, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVEsByPackageNameRow{}
	for rows.Next() {
		var i ListCVEsByPackageNameRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.NvdLastModified,
			&i.AttackVector,
			&i.ExternalReferences,
			&i.CweID,
			&i.Source,
			&i.VersionEndExcluding,
			&i.VersionEndIncluding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchesByName = `-- name: ListPatchesByName :many
SELECT id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id FROM patches
WHERE package_name = $1 AND tenant_id = $2
LIMIT 1000
`

type ListPatchesByNameParams struct {
	PackageName string      `json:"package_name"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListPatchesByName(ctx context.Context, arg ListPatchesByNameParams) ([]Patch, error) {
	rows, err := q.db.Query(ctx, listPatchesByName, arg.PackageName, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsDistribution,
			&i.PackageUrl,
			&i.ChecksumSha256,
			&i.SourceRepo,
			&i.Description,
			&i.ReleasedAt,
			&i.PackageName,
			&i.InstallerType,
			&i.SilentArgs,
			&i.DeletedAt,
			&i.HubCatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCVESyncCursor = `-- name: UpsertCVESyncCursor :one
INSERT INTO cve_sync_cursors (tenant_id, source, last_synced)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, source)
DO UPDATE SET last_synced = EXCLUDED.last_synced, updated_at = now()
RETURNING id, tenant_id, source, last_synced, created_at, updated_at
`

type UpsertCVESyncCursorParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Source     string             `json:"source"`
	LastSynced pgtype.Timestamptz `json:"last_synced"`
}

func (q *Queries) UpsertCVESyncCursor(ctx context.Context, arg UpsertCVESyncCursorParams) (CveSyncCursor, error) {
	row := q.db.QueryRow(ctx, upsertCVESyncCursor, arg.TenantID, arg.Source, arg.LastSynced)
	var i CveSyncCursor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
