// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDeployments = `-- name: GetActiveDeployments :many
SELECT
  d.id,
  p.name AS policy_name,
  d.status,
  CASE WHEN d.total_targets > 0
    THEN (d.completed_count * 100 / d.total_targets)::int
    ELSE 0
  END AS progress_pct
FROM deployments d
LEFT JOIN policies p ON p.id = d.policy_id AND p.tenant_id = d.tenant_id
WHERE d.tenant_id = $1
  AND d.status IN ('created', 'running')
ORDER BY d.created_at DESC
LIMIT 5
`

type GetActiveDeploymentsRow struct {
	ID          pgtype.UUID `json:"id"`
	PolicyName  pgtype.Text `json:"policy_name"`
	Status      string      `json:"status"`
	ProgressPct int32       `json:"progress_pct"`
}

func (q *Queries) GetActiveDeployments(ctx context.Context, tenantID pgtype.UUID) ([]GetActiveDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, getActiveDeployments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveDeploymentsRow{}
	for rows.Next() {
		var i GetActiveDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyName,
			&i.Status,
			&i.ProgressPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttackPaths = `-- name: GetAttackPaths :many
WITH risky_endpoints AS (
  SELECT e.id, e.hostname, e.os_family,
    count(ec.id) FILTER (WHERE c.severity = 'critical')::int AS critical_count,
    count(ec.id) FILTER (WHERE c.severity = 'high')::int AS high_count,
    bool_or(e.status = 'online') AS is_online
  FROM endpoints e
  JOIN endpoint_cves ec ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id AND ec.status = 'affected'
  JOIN cves c ON c.id = ec.cve_id
  WHERE e.tenant_id = $1 AND e.status != 'decommissioned'
  GROUP BY e.id
  HAVING count(ec.id) FILTER (WHERE c.severity IN ('critical', 'high')) > 0
  ORDER BY critical_count DESC, high_count DESC
  LIMIT 50
),
shared_cves AS (
  SELECT ec1.endpoint_id AS source_id, ec2.endpoint_id AS target_id, count(*)::int AS shared_count
  FROM endpoint_cves ec1
  JOIN endpoint_cves ec2 ON ec1.cve_id = ec2.cve_id AND ec1.tenant_id = ec2.tenant_id
    AND ec1.endpoint_id < ec2.endpoint_id
  WHERE ec1.tenant_id = $1
    AND ec1.endpoint_id IN (SELECT id FROM risky_endpoints)
    AND ec2.endpoint_id IN (SELECT id FROM risky_endpoints)
    AND ec1.status = 'affected' AND ec2.status = 'affected'
  GROUP BY ec1.endpoint_id, ec2.endpoint_id
  HAVING count(*) >= 2
)
SELECT 'node' AS row_type,
  re.id::text AS id, re.hostname AS label, re.os_family AS os,
  re.critical_count, re.high_count, re.is_online,
  ''::text AS source_id, ''::text AS target_id, 0 AS shared_count
FROM risky_endpoints re
UNION ALL
SELECT 'edge' AS row_type,
  ''::text AS id, ''::text AS label, ''::text AS os,
  0 AS critical_count, 0 AS high_count, false AS is_online,
  sc.source_id::text, sc.target_id::text, sc.shared_count
FROM shared_cves sc
`

type GetAttackPathsRow struct {
	RowType       string `json:"row_type"`
	ID            string `json:"id"`
	Label         string `json:"label"`
	Os            string `json:"os"`
	CriticalCount int32  `json:"critical_count"`
	HighCount     int32  `json:"high_count"`
	IsOnline      bool   `json:"is_online"`
	SourceID      string `json:"source_id"`
	TargetID      string `json:"target_id"`
	SharedCount   int32  `json:"shared_count"`
}

func (q *Queries) GetAttackPaths(ctx context.Context, tenantID pgtype.UUID) ([]GetAttackPathsRow, error) {
	rows, err := q.db.Query(ctx, getAttackPaths, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttackPathsRow{}
	for rows.Next() {
		var i GetAttackPathsRow
		if err := rows.Scan(
			&i.RowType,
			&i.ID,
			&i.Label,
			&i.Os,
			&i.CriticalCount,
			&i.HighCount,
			&i.IsOnline,
			&i.SourceID,
			&i.TargetID,
			&i.SharedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlastRadiusGroups = `-- name: GetBlastRadiusGroups :many
SELECT
  COALESCE(t.key || '=' || t.value, '')::text AS name,
  e.os_family AS os,
  count(DISTINCT e.id)::int AS host_count
FROM endpoint_cves ec
JOIN endpoints e ON e.id = ec.endpoint_id AND e.tenant_id = ec.tenant_id
LEFT JOIN endpoint_tags et ON et.endpoint_id = e.id AND et.tenant_id = e.tenant_id
LEFT JOIN tags t ON t.id = et.tag_id AND t.tenant_id = e.tenant_id
WHERE ec.cve_id = $1 AND ec.tenant_id = $2 AND ec.status = 'affected'
GROUP BY t.key, t.value, e.os_family
ORDER BY host_count DESC
LIMIT 100
`

type GetBlastRadiusGroupsParams struct {
	CveID    pgtype.UUID `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetBlastRadiusGroupsRow struct {
	Name      string `json:"name"`
	Os        string `json:"os"`
	HostCount int32  `json:"host_count"`
}

// Blast radius broken down by tag value, replacing the legacy groups
// version. `name` now reports "key=value" so the response shape stays
// stable for the dashboard consumer.
func (q *Queries) GetBlastRadiusGroups(ctx context.Context, arg GetBlastRadiusGroupsParams) ([]GetBlastRadiusGroupsRow, error) {
	rows, err := q.db.Query(ctx, getBlastRadiusGroups, arg.CveID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlastRadiusGroupsRow{}
	for rows.Next() {
		var i GetBlastRadiusGroupsRow
		if err := rows.Scan(&i.Name, &i.Os, &i.HostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVEByUUID = `-- name: GetCVEByUUID :one
SELECT c.id, c.cve_id, c.severity,
  COALESCE(c.cvss_v3_score, 0)::float AS cvss_score,
  count(ec.id)::int AS affected_count
FROM cves c
LEFT JOIN endpoint_cves ec ON ec.cve_id = c.id AND ec.tenant_id = c.tenant_id AND ec.status = 'affected'
WHERE c.id = $1 AND c.tenant_id = $2
GROUP BY c.id
`

type GetCVEByUUIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetCVEByUUIDRow struct {
	ID            pgtype.UUID `json:"id"`
	CveID         string      `json:"cve_id"`
	Severity      string      `json:"severity"`
	CvssScore     float64     `json:"cvss_score"`
	AffectedCount int32       `json:"affected_count"`
}

func (q *Queries) GetCVEByUUID(ctx context.Context, arg GetCVEByUUIDParams) (GetCVEByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCVEByUUID, arg.ID, arg.TenantID)
	var i GetCVEByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.CvssScore,
		&i.AffectedCount,
	)
	return i, err
}

const getDashboardActivity = `-- name: GetDashboardActivity :many
SELECT
  d.id,
  'deployment' AS type,
  p.name AS title,
  d.status,
  d.total_targets,
  d.completed_count,
  d.failed_count,
  d.created_at AS timestamp
FROM deployments d
LEFT JOIN policies p ON p.id = d.policy_id AND p.tenant_id = d.tenant_id
WHERE d.tenant_id = $1
ORDER BY d.updated_at DESC
LIMIT 20
`

type GetDashboardActivityRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	Title          pgtype.Text        `json:"title"`
	Status         string             `json:"status"`
	TotalTargets   int32              `json:"total_targets"`
	CompletedCount int32              `json:"completed_count"`
	FailedCount    int32              `json:"failed_count"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) GetDashboardActivity(ctx context.Context, tenantID pgtype.UUID) ([]GetDashboardActivityRow, error) {
	rows, err := q.db.Query(ctx, getDashboardActivity, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardActivityRow{}
	for rows.Next() {
		var i GetDashboardActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Status,
			&i.TotalTargets,
			&i.CompletedCount,
			&i.FailedCount,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
  (SELECT count(*) FROM endpoints e WHERE e.tenant_id = $1 AND e.status != 'decommissioned')::int AS endpoints_total,
  (SELECT count(*) FROM endpoints e WHERE e.tenant_id = $1 AND e.status = 'online')::int AS endpoints_online,
  (SELECT count(*) FROM patches p WHERE p.tenant_id = $1 AND p.status = 'available')::int AS patches_available,
  (SELECT count(*) FROM patches p WHERE p.tenant_id = $1 AND p.status = 'available' AND p.severity = 'critical')::int AS patches_critical,
  (SELECT count(*) FROM patches p WHERE p.tenant_id = $1 AND p.status = 'available' AND p.severity = 'high')::int AS patches_high,
  (SELECT count(*) FROM endpoint_cves ec WHERE ec.tenant_id = $1)::int AS cves_total,
  (SELECT count(*) FROM endpoint_cves ec WHERE ec.tenant_id = $1 AND ec.status != 'patched')::int AS cves_unpatched,
  (SELECT count(*) FROM endpoint_cves ecv JOIN cves cv ON ecv.cve_id = cv.id AND ecv.tenant_id = cv.tenant_id WHERE ecv.tenant_id = $1 AND ecv.status != 'patched' AND cv.severity = 'critical')::int AS cves_critical,
  (SELECT count(*) FROM deployments d WHERE d.tenant_id = $1 AND d.status IN ('created', 'running'))::int AS deployments_running,
  (SELECT count(*) FROM deployments d WHERE d.tenant_id = $1 AND d.status = 'completed' AND d.completed_at >= CURRENT_DATE)::int AS deployments_completed_today,
  (SELECT count(*) FROM endpoints e WHERE e.tenant_id = $1 AND e.status = 'degraded')::int AS endpoints_degraded,
  (SELECT count(*) FROM patches p2 WHERE p2.tenant_id = $1 AND p2.status = 'available' AND p2.severity = 'medium')::int AS patches_medium,
  (SELECT count(*) FROM patches p3 WHERE p3.tenant_id = $1 AND p3.status = 'available' AND p3.severity = 'low')::int AS patches_low,
  (SELECT count(*) FROM deployments d WHERE d.tenant_id = $1 AND d.status = 'failed')::int AS failed_deployments_count,
  (SELECT count(*) FROM deployments d WHERE d.tenant_id = $1 AND d.status IN ('created', 'running') AND d.created_at < now() - interval '24 hours')::int AS overdue_sla_count,
  COALESCE((SELECT count(DISTINCT ec.endpoint_id) FILTER (WHERE ec.status = 'patched') * 100.0 / NULLIF(count(DISTINCT ec.endpoint_id), 0) FROM endpoint_cves ec WHERE ec.tenant_id = $1), 100.0)::float AS compliance_pct,
  (SELECT count(*) FROM compliance_tenant_frameworks ctf WHERE ctf.tenant_id = $1 AND ctf.enabled = true)::int AS frameworks_enabled
`

type GetDashboardSummaryRow struct {
	EndpointsTotal            int32   `json:"endpoints_total"`
	EndpointsOnline           int32   `json:"endpoints_online"`
	PatchesAvailable          int32   `json:"patches_available"`
	PatchesCritical           int32   `json:"patches_critical"`
	PatchesHigh               int32   `json:"patches_high"`
	CvesTotal                 int32   `json:"cves_total"`
	CvesUnpatched             int32   `json:"cves_unpatched"`
	CvesCritical              int32   `json:"cves_critical"`
	DeploymentsRunning        int32   `json:"deployments_running"`
	DeploymentsCompletedToday int32   `json:"deployments_completed_today"`
	EndpointsDegraded         int32   `json:"endpoints_degraded"`
	PatchesMedium             int32   `json:"patches_medium"`
	PatchesLow                int32   `json:"patches_low"`
	FailedDeploymentsCount    int32   `json:"failed_deployments_count"`
	OverdueSlaCount           int32   `json:"overdue_sla_count"`
	CompliancePct             float64 `json:"compliance_pct"`
	FrameworksEnabled         int32   `json:"frameworks_enabled"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, tenantID pgtype.UUID) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, tenantID)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.EndpointsTotal,
		&i.EndpointsOnline,
		&i.PatchesAvailable,
		&i.PatchesCritical,
		&i.PatchesHigh,
		&i.CvesTotal,
		&i.CvesUnpatched,
		&i.CvesCritical,
		&i.DeploymentsRunning,
		&i.DeploymentsCompletedToday,
		&i.EndpointsDegraded,
		&i.PatchesMedium,
		&i.PatchesLow,
		&i.FailedDeploymentsCount,
		&i.OverdueSlaCount,
		&i.CompliancePct,
		&i.FrameworksEnabled,
	)
	return i, err
}

const getExposureWindows = `-- name: GetExposureWindows :many
SELECT c.id, c.cve_id, c.severity,
  COALESCE(c.cvss_v3_score, 0)::float AS cvss_score,
  count(DISTINCT ec.endpoint_id)::int AS affected_count,
  min(ec.created_at) AS first_seen,
  max(CASE WHEN ec.status = 'patched' THEN ec.updated_at END) AS patched_at
FROM cves c
JOIN endpoint_cves ec ON ec.cve_id = c.id AND ec.tenant_id = c.tenant_id
WHERE c.tenant_id = $1
  AND c.severity IN ('critical', 'high')
  AND ec.created_at >= now() - interval '90 days'
GROUP BY c.id
ORDER BY min(ec.created_at) ASC
LIMIT 15
`

type GetExposureWindowsRow struct {
	ID            pgtype.UUID `json:"id"`
	CveID         string      `json:"cve_id"`
	Severity      string      `json:"severity"`
	CvssScore     float64     `json:"cvss_score"`
	AffectedCount int32       `json:"affected_count"`
	FirstSeen     interface{} `json:"first_seen"`
	PatchedAt     interface{} `json:"patched_at"`
}

func (q *Queries) GetExposureWindows(ctx context.Context, tenantID pgtype.UUID) ([]GetExposureWindowsRow, error) {
	rows, err := q.db.Query(ctx, getExposureWindows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExposureWindowsRow{}
	for rows.Next() {
		var i GetExposureWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.CvssScore,
			&i.AffectedCount,
			&i.FirstSeen,
			&i.PatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedDeploymentTrend7d = `-- name: GetFailedDeploymentTrend7d :many
SELECT
  d.date::date AS day,
  COALESCE(cnt, 0)::int AS count
FROM generate_series(
  CURRENT_DATE - INTERVAL '6 days',
  CURRENT_DATE,
  '1 day'
) AS d(date)
LEFT JOIN (
  SELECT completed_at::date AS day, count(*)::int AS cnt
  FROM deployments
  WHERE tenant_id = $1
    AND status = 'failed'
    AND completed_at >= CURRENT_DATE - INTERVAL '6 days'
  GROUP BY completed_at::date
) sub ON sub.day = d.date::date
ORDER BY d.date
`

type GetFailedDeploymentTrend7dRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) GetFailedDeploymentTrend7d(ctx context.Context, tenantID pgtype.UUID) ([]GetFailedDeploymentTrend7dRow, error) {
	rows, err := q.db.Query(ctx, getFailedDeploymentTrend7d, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailedDeploymentTrend7dRow{}
	for rows.Next() {
		var i GetFailedDeploymentTrend7dRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestUnpatchedCVE = `-- name: GetHighestUnpatchedCVE :one
SELECT c.id, c.cve_id, c.severity,
  COALESCE(c.cvss_v3_score, 0)::float AS cvss_score,
  count(ec.id)::int AS affected_count
FROM cves c
JOIN endpoint_cves ec ON ec.cve_id = c.id AND ec.tenant_id = c.tenant_id
WHERE c.tenant_id = $1 AND ec.status = 'affected'
GROUP BY c.id
ORDER BY COALESCE(c.cvss_v3_score, 0) DESC
LIMIT 1
`

type GetHighestUnpatchedCVERow struct {
	ID            pgtype.UUID `json:"id"`
	CveID         string      `json:"cve_id"`
	Severity      string      `json:"severity"`
	CvssScore     float64     `json:"cvss_score"`
	AffectedCount int32       `json:"affected_count"`
}

func (q *Queries) GetHighestUnpatchedCVE(ctx context.Context, tenantID pgtype.UUID) (GetHighestUnpatchedCVERow, error) {
	row := q.db.QueryRow(ctx, getHighestUnpatchedCVE, tenantID)
	var i GetHighestUnpatchedCVERow
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.CvssScore,
		&i.AffectedCount,
	)
	return i, err
}

const getMTTR = `-- name: GetMTTR :many
SELECT
  date_trunc('week', ec.updated_at)::date AS week,
  c.severity,
  avg(EXTRACT(EPOCH FROM (ec.updated_at - ec.created_at)) / 3600)::float AS avg_hours
FROM endpoint_cves ec
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1
  AND ec.status = 'patched'
  AND ec.updated_at >= now() - interval '26 weeks'
GROUP BY date_trunc('week', ec.updated_at)::date, c.severity
ORDER BY week
`

type GetMTTRRow struct {
	Week     pgtype.Date `json:"week"`
	Severity string      `json:"severity"`
	AvgHours float64     `json:"avg_hours"`
}

func (q *Queries) GetMTTR(ctx context.Context, tenantID pgtype.UUID) ([]GetMTTRRow, error) {
	rows, err := q.db.Query(ctx, getMTTR, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMTTRRow{}
	for rows.Next() {
		var i GetMTTRRow
		if err := rows.Scan(&i.Week, &i.Severity, &i.AvgHours); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyDrift = `-- name: GetPolicyDrift :many
SELECT e.id, e.hostname, e.os_family,
  count(ec.id) FILTER (WHERE ec.status = 'affected')::int AS unpatched_count,
  count(ec.id)::int AS total_cve_count,
  CASE WHEN count(ec.id) > 0
    THEN (count(ec.id) FILTER (WHERE ec.status = 'affected') * 100 / count(ec.id))::int
    ELSE 0
  END AS drift_score,
  max(CASE WHEN ec.status = 'patched' THEN ec.updated_at END) AS last_compliant_at
FROM endpoints e
LEFT JOIN endpoint_cves ec ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
WHERE e.tenant_id = $1 AND e.status != 'decommissioned'
GROUP BY e.id, e.hostname, e.os_family
HAVING count(ec.id) FILTER (WHERE ec.status = 'affected') > 0
ORDER BY drift_score DESC
LIMIT 50
`

type GetPolicyDriftRow struct {
	ID              pgtype.UUID `json:"id"`
	Hostname        string      `json:"hostname"`
	OsFamily        string      `json:"os_family"`
	UnpatchedCount  int32       `json:"unpatched_count"`
	TotalCveCount   int32       `json:"total_cve_count"`
	DriftScore      int32       `json:"drift_score"`
	LastCompliantAt interface{} `json:"last_compliant_at"`
}

func (q *Queries) GetPolicyDrift(ctx context.Context, tenantID pgtype.UUID) ([]GetPolicyDriftRow, error) {
	rows, err := q.db.Query(ctx, getPolicyDrift, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPolicyDriftRow{}
	for rows.Next() {
		var i GetPolicyDriftRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.OsFamily,
			&i.UnpatchedCount,
			&i.TotalCveCount,
			&i.DriftScore,
			&i.LastCompliantAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskProjectionData = `-- name: GetRiskProjectionData :one
SELECT
  (SELECT count(*) FILTER (WHERE ec.status = 'affected') * 100.0 / NULLIF(count(*), 0) FROM endpoint_cves ec WHERE ec.tenant_id = $1)::float AS current_risk_pct,
  (SELECT avg(cnt)::float FROM (
    SELECT date_trunc('day', ec.updated_at)::date, count(*)::float AS cnt
    FROM endpoint_cves ec WHERE ec.tenant_id = $1 AND ec.status = 'patched' AND ec.updated_at >= now() - interval '30 days'
    GROUP BY date_trunc('day', ec.updated_at)::date
  ) daily_patches) AS avg_daily_patches,
  (SELECT avg(cnt)::float FROM (
    SELECT date_trunc('day', ec.created_at)::date, count(*)::float AS cnt
    FROM endpoint_cves ec WHERE ec.tenant_id = $1 AND ec.created_at >= now() - interval '30 days'
    GROUP BY date_trunc('day', ec.created_at)::date
  ) daily_new) AS avg_daily_new_cves,
  (SELECT count(*) FROM endpoint_cves ec WHERE ec.tenant_id = $1 AND ec.status = 'affected')::int AS total_affected,
  (SELECT count(*) FROM endpoint_cves ec WHERE ec.tenant_id = $1)::int AS total_cves
`

type GetRiskProjectionDataRow struct {
	CurrentRiskPct  float64 `json:"current_risk_pct"`
	AvgDailyPatches float64 `json:"avg_daily_patches"`
	AvgDailyNewCves float64 `json:"avg_daily_new_cves"`
	TotalAffected   int32   `json:"total_affected"`
	TotalCves       int32   `json:"total_cves"`
}

func (q *Queries) GetRiskProjectionData(ctx context.Context, tenantID pgtype.UUID) (GetRiskProjectionDataRow, error) {
	row := q.db.QueryRow(ctx, getRiskProjectionData, tenantID)
	var i GetRiskProjectionDataRow
	err := row.Scan(
		&i.CurrentRiskPct,
		&i.AvgDailyPatches,
		&i.AvgDailyNewCves,
		&i.TotalAffected,
		&i.TotalCves,
	)
	return i, err
}

const getRunningWorkflows = `-- name: GetRunningWorkflows :many
SELECT
  we.id,
  w.name,
  COALESCE(we.current_node_id::text, '') AS current_stage
FROM workflow_executions we
JOIN workflows w ON w.id = we.workflow_id AND w.tenant_id = we.tenant_id
WHERE we.tenant_id = $1
  AND we.status IN ('pending', 'running')
ORDER BY we.created_at DESC
LIMIT 5
`

type GetRunningWorkflowsRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	CurrentStage interface{} `json:"current_stage"`
}

func (q *Queries) GetRunningWorkflows(ctx context.Context, tenantID pgtype.UUID) ([]GetRunningWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, getRunningWorkflows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRunningWorkflowsRow{}
	for rows.Next() {
		var i GetRunningWorkflowsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CurrentStage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLADeadlines = `-- name: GetSLADeadlines :many
SELECT e.id AS endpoint_id, e.hostname,
  c.severity,
  c.cve_id AS patch_name,
  EXTRACT(EPOCH FROM (
    ec.created_at + CASE c.severity
      WHEN 'critical' THEN interval '24 hours'
      WHEN 'high' THEN interval '72 hours'
      WHEN 'medium' THEN interval '7 days'
      ELSE interval '30 days'
    END - now()
  ))::int AS remaining_seconds
FROM endpoint_cves ec
JOIN endpoints e ON e.id = ec.endpoint_id AND e.tenant_id = ec.tenant_id
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1
  AND ec.status = 'affected'
  AND e.status != 'decommissioned'
ORDER BY remaining_seconds ASC
LIMIT 10
`

type GetSLADeadlinesRow struct {
	EndpointID       pgtype.UUID `json:"endpoint_id"`
	Hostname         string      `json:"hostname"`
	Severity         string      `json:"severity"`
	PatchName        string      `json:"patch_name"`
	RemainingSeconds int32       `json:"remaining_seconds"`
}

func (q *Queries) GetSLADeadlines(ctx context.Context, tenantID pgtype.UUID) ([]GetSLADeadlinesRow, error) {
	rows, err := q.db.Query(ctx, getSLADeadlines, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSLADeadlinesRow{}
	for rows.Next() {
		var i GetSLADeadlinesRow
		if err := rows.Scan(
			&i.EndpointID,
			&i.Hostname,
			&i.Severity,
			&i.PatchName,
			&i.RemainingSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLAForecast = `-- name: GetSLAForecast :many
SELECT e.id, e.hostname,
  c.severity,
  min(ec.created_at) AS oldest_open_since,
  CASE c.severity
    WHEN 'critical' THEN 24
    WHEN 'high' THEN 72
    WHEN 'medium' THEN 168
    ELSE 720
  END AS sla_window_hours,
  EXTRACT(EPOCH FROM (
    min(ec.created_at) + CASE c.severity
      WHEN 'critical' THEN interval '24 hours'
      WHEN 'high' THEN interval '72 hours'
      WHEN 'medium' THEN interval '7 days'
      ELSE interval '30 days'
    END - now()
  ))::int AS remaining_seconds
FROM endpoints e
JOIN endpoint_cves ec ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id AND ec.status = 'affected'
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE e.tenant_id = $1 AND e.status != 'decommissioned'
GROUP BY e.id, e.hostname, c.severity
HAVING min(ec.created_at) + CASE c.severity
    WHEN 'critical' THEN interval '24 hours'
    WHEN 'high' THEN interval '72 hours'
    WHEN 'medium' THEN interval '7 days'
    ELSE interval '30 days'
  END > now() - interval '48 hours'
ORDER BY remaining_seconds ASC
LIMIT 20
`

type GetSLAForecastRow struct {
	ID               pgtype.UUID `json:"id"`
	Hostname         string      `json:"hostname"`
	Severity         string      `json:"severity"`
	OldestOpenSince  interface{} `json:"oldest_open_since"`
	SlaWindowHours   int32       `json:"sla_window_hours"`
	RemainingSeconds int32       `json:"remaining_seconds"`
}

func (q *Queries) GetSLAForecast(ctx context.Context, tenantID pgtype.UUID) ([]GetSLAForecastRow, error) {
	rows, err := q.db.Query(ctx, getSLAForecast, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSLAForecastRow{}
	for rows.Next() {
		var i GetSLAForecastRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Severity,
			&i.OldestOpenSince,
			&i.SlaWindowHours,
			&i.RemainingSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLATiers = `-- name: GetSLATiers :many
SELECT
  c.severity,
  count(*)::int AS total,
  count(*) FILTER (WHERE ec.created_at + CASE c.severity
    WHEN 'critical' THEN interval '24 hours'
    WHEN 'high' THEN interval '72 hours'
    WHEN 'medium' THEN interval '7 days'
    ELSE interval '30 days'
  END < now())::int AS overdue
FROM endpoint_cves ec
JOIN cves c ON c.id = ec.cve_id AND c.tenant_id = ec.tenant_id
WHERE ec.tenant_id = $1 AND ec.status = 'affected'
GROUP BY c.severity
ORDER BY CASE c.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END
`

type GetSLATiersRow struct {
	Severity string `json:"severity"`
	Total    int32  `json:"total"`
	Overdue  int32  `json:"overdue"`
}

func (q *Queries) GetSLATiers(ctx context.Context, tenantID pgtype.UUID) ([]GetSLATiersRow, error) {
	rows, err := q.db.Query(ctx, getSLATiers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSLATiersRow{}
	for rows.Next() {
		var i GetSLATiersRow
		if err := rows.Scan(&i.Severity, &i.Total, &i.Overdue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopEndpointsByRisk = `-- name: GetTopEndpointsByRisk :many
SELECT
  e.hostname,
  count(ec.id)::int AS cve_count,
  LEAST(10, (count(ec.id) FILTER (WHERE c.severity = 'critical') * 3
   + count(ec.id) FILTER (WHERE c.severity = 'high') * 2
   + count(ec.id) FILTER (WHERE c.severity = 'medium')) / 10)::int AS risk_score
FROM endpoints e
LEFT JOIN endpoint_cves ec ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id AND ec.status = 'affected'
LEFT JOIN cves c ON c.id = ec.cve_id
WHERE e.tenant_id = $1 AND e.status != 'decommissioned'
GROUP BY e.id, e.hostname
ORDER BY risk_score DESC
LIMIT 30
`

type GetTopEndpointsByRiskRow struct {
	Hostname  string `json:"hostname"`
	CveCount  int32  `json:"cve_count"`
	RiskScore int32  `json:"risk_score"`
}

func (q *Queries) GetTopEndpointsByRisk(ctx context.Context, tenantID pgtype.UUID) ([]GetTopEndpointsByRiskRow, error) {
	rows, err := q.db.Query(ctx, getTopEndpointsByRisk, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopEndpointsByRiskRow{}
	for rows.Next() {
		var i GetTopEndpointsByRiskRow
		if err := rows.Scan(&i.Hostname, &i.CveCount, &i.RiskScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
