// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hub_sync.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHubSyncState = `-- name: GetHubSyncState :one
SELECT id, tenant_id, hub_url, api_key, last_sync_at, next_sync_at, sync_interval, entries_received, last_entry_count, last_error, status, created_at, updated_at FROM hub_sync_state WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetHubSyncState(ctx context.Context, tenantID pgtype.UUID) (HubSyncState, error) {
	row := q.db.QueryRow(ctx, getHubSyncState, tenantID)
	var i HubSyncState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.HubUrl,
		&i.ApiKey,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.SyncInterval,
		&i.EntriesReceived,
		&i.LastEntryCount,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllHubSyncStates = `-- name: ListAllHubSyncStates :many
SELECT id, tenant_id, hub_url, api_key, last_sync_at, next_sync_at, sync_interval, entries_received, last_entry_count, last_error, status, created_at, updated_at FROM hub_sync_state WHERE status != 'disabled' ORDER BY created_at
LIMIT 100
`

func (q *Queries) ListAllHubSyncStates(ctx context.Context) ([]HubSyncState, error) {
	rows, err := q.db.Query(ctx, listAllHubSyncStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubSyncState{}
	for rows.Next() {
		var i HubSyncState
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.HubUrl,
			&i.ApiKey,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.SyncInterval,
			&i.EntriesReceived,
			&i.LastEntryCount,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHubCVESyncCompleted = `-- name: UpdateHubCVESyncCompleted :exec
UPDATE hub_sync_state
SET last_cve_sync_at = now(), updated_at = now()
WHERE tenant_id = $1
`

func (q *Queries) UpdateHubCVESyncCompleted(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHubCVESyncCompleted, tenantID)
	return err
}

const updateHubCVESyncFailed = `-- name: UpdateHubCVESyncFailed :exec
UPDATE hub_sync_state
SET last_error = $1, updated_at = now()
WHERE tenant_id = $2
`

type UpdateHubCVESyncFailedParams struct {
	LastError pgtype.Text `json:"last_error"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateHubCVESyncFailed(ctx context.Context, arg UpdateHubCVESyncFailedParams) error {
	_, err := q.db.Exec(ctx, updateHubCVESyncFailed, arg.LastError, arg.TenantID)
	return err
}

const updateHubSyncCompleted = `-- name: UpdateHubSyncCompleted :exec
UPDATE hub_sync_state
SET status = 'idle',
    last_sync_at = now(),
    next_sync_at = $1,
    entries_received = entries_received + $2,
    last_entry_count = $2,
    last_error = NULL,
    updated_at = now()
WHERE tenant_id = $3
`

type UpdateHubSyncCompletedParams struct {
	NextSyncAt pgtype.Timestamptz `json:"next_sync_at"`
	EntryCount int32              `json:"entry_count"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateHubSyncCompleted(ctx context.Context, arg UpdateHubSyncCompletedParams) error {
	_, err := q.db.Exec(ctx, updateHubSyncCompleted, arg.NextSyncAt, arg.EntryCount, arg.TenantID)
	return err
}

const updateHubSyncFailed = `-- name: UpdateHubSyncFailed :exec
UPDATE hub_sync_state
SET status = 'error',
    last_error = $1,
    updated_at = now()
WHERE tenant_id = $2
`

type UpdateHubSyncFailedParams struct {
	ErrorMessage pgtype.Text `json:"error_message"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateHubSyncFailed(ctx context.Context, arg UpdateHubSyncFailedParams) error {
	_, err := q.db.Exec(ctx, updateHubSyncFailed, arg.ErrorMessage, arg.TenantID)
	return err
}

const updateHubSyncStarted = `-- name: UpdateHubSyncStarted :exec
UPDATE hub_sync_state
SET status = 'syncing', updated_at = now()
WHERE tenant_id = $1
`

func (q *Queries) UpdateHubSyncStarted(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHubSyncStarted, tenantID)
	return err
}

const upsertHubSyncState = `-- name: UpsertHubSyncState :one
INSERT INTO hub_sync_state (tenant_id, hub_url, api_key, sync_interval)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO UPDATE
SET hub_url = EXCLUDED.hub_url,
    api_key = EXCLUDED.api_key,
    sync_interval = EXCLUDED.sync_interval,
    updated_at = now()
RETURNING id, tenant_id, hub_url, api_key, last_sync_at, next_sync_at, sync_interval, entries_received, last_entry_count, last_error, status, created_at, updated_at
`

type UpsertHubSyncStateParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	HubUrl       string      `json:"hub_url"`
	ApiKey       string      `json:"api_key"`
	SyncInterval int32       `json:"sync_interval"`
}

func (q *Queries) UpsertHubSyncState(ctx context.Context, arg UpsertHubSyncStateParams) (HubSyncState, error) {
	row := q.db.QueryRow(ctx, upsertHubSyncState,
		arg.TenantID,
		arg.HubUrl,
		arg.ApiKey,
		arg.SyncInterval,
	)
	var i HubSyncState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.HubUrl,
		&i.ApiKey,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.SyncInterval,
		&i.EntriesReceived,
		&i.LastEntryCount,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
