// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpointInventory = `-- name: CreateEndpointInventory :one
INSERT INTO endpoint_inventories (tenant_id, endpoint_id, scanned_at, package_count, collection_errors)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, endpoint_id, scanned_at, package_count, created_at, collection_errors
`

type CreateEndpointInventoryParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	ScannedAt        pgtype.Timestamptz `json:"scanned_at"`
	PackageCount     int32              `json:"package_count"`
	CollectionErrors []byte             `json:"collection_errors"`
}

func (q *Queries) CreateEndpointInventory(ctx context.Context, arg CreateEndpointInventoryParams) (EndpointInventory, error) {
	row := q.db.QueryRow(ctx, createEndpointInventory,
		arg.TenantID,
		arg.EndpointID,
		arg.ScannedAt,
		arg.PackageCount,
		arg.CollectionErrors,
	)
	var i EndpointInventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.ScannedAt,
		&i.PackageCount,
		&i.CreatedAt,
		&i.CollectionErrors,
	)
	return i, err
}

const createEndpointPackage = `-- name: CreateEndpointPackage :one
INSERT INTO endpoint_packages (tenant_id, endpoint_id, inventory_id, package_name, version, arch, source, release, kb_article, severity, install_date, category, publisher)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, endpoint_id, inventory_id, package_name, version, arch, source, created_at, release, kb_article, severity, install_date, category, publisher
`

type CreateEndpointPackageParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EndpointID  pgtype.UUID `json:"endpoint_id"`
	InventoryID pgtype.UUID `json:"inventory_id"`
	PackageName string      `json:"package_name"`
	Version     string      `json:"version"`
	Arch        pgtype.Text `json:"arch"`
	Source      pgtype.Text `json:"source"`
	Release     pgtype.Text `json:"release"`
	KbArticle   pgtype.Text `json:"kb_article"`
	Severity    pgtype.Text `json:"severity"`
	InstallDate pgtype.Text `json:"install_date"`
	Category    pgtype.Text `json:"category"`
	Publisher   pgtype.Text `json:"publisher"`
}

func (q *Queries) CreateEndpointPackage(ctx context.Context, arg CreateEndpointPackageParams) (EndpointPackage, error) {
	row := q.db.QueryRow(ctx, createEndpointPackage,
		arg.TenantID,
		arg.EndpointID,
		arg.InventoryID,
		arg.PackageName,
		arg.Version,
		arg.Arch,
		arg.Source,
		arg.Release,
		arg.KbArticle,
		arg.Severity,
		arg.InstallDate,
		arg.Category,
		arg.Publisher,
	)
	var i EndpointPackage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.InventoryID,
		&i.PackageName,
		&i.Version,
		&i.Arch,
		&i.Source,
		&i.CreatedAt,
		&i.Release,
		&i.KbArticle,
		&i.Severity,
		&i.InstallDate,
		&i.Category,
		&i.Publisher,
	)
	return i, err
}

const getEndpointInventoryByID = `-- name: GetEndpointInventoryByID :one
SELECT id, tenant_id, endpoint_id, scanned_at, package_count, created_at, collection_errors FROM endpoint_inventories WHERE id = $1 AND tenant_id = $2
`

type GetEndpointInventoryByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEndpointInventoryByID(ctx context.Context, arg GetEndpointInventoryByIDParams) (EndpointInventory, error) {
	row := q.db.QueryRow(ctx, getEndpointInventoryByID, arg.ID, arg.TenantID)
	var i EndpointInventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.ScannedAt,
		&i.PackageCount,
		&i.CreatedAt,
		&i.CollectionErrors,
	)
	return i, err
}

const getLatestEndpointInventory = `-- name: GetLatestEndpointInventory :one
SELECT id, tenant_id, endpoint_id, scanned_at, package_count, created_at, collection_errors FROM endpoint_inventories
WHERE endpoint_id = $1 AND tenant_id = $2
ORDER BY scanned_at DESC
LIMIT 1
`

type GetLatestEndpointInventoryParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetLatestEndpointInventory(ctx context.Context, arg GetLatestEndpointInventoryParams) (EndpointInventory, error) {
	row := q.db.QueryRow(ctx, getLatestEndpointInventory, arg.EndpointID, arg.TenantID)
	var i EndpointInventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.ScannedAt,
		&i.PackageCount,
		&i.CreatedAt,
		&i.CollectionErrors,
	)
	return i, err
}

const listEndpointInventories = `-- name: ListEndpointInventories :many
SELECT id, tenant_id, endpoint_id, scanned_at, package_count, created_at, collection_errors FROM endpoint_inventories
WHERE endpoint_id = $1 AND tenant_id = $2
ORDER BY scanned_at DESC
LIMIT 1000
`

type ListEndpointInventoriesParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListEndpointInventories(ctx context.Context, arg ListEndpointInventoriesParams) ([]EndpointInventory, error) {
	rows, err := q.db.Query(ctx, listEndpointInventories, arg.EndpointID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndpointInventory{}
	for rows.Next() {
		var i EndpointInventory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.ScannedAt,
			&i.PackageCount,
			&i.CreatedAt,
			&i.CollectionErrors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointPackages = `-- name: ListEndpointPackages :many
SELECT id, tenant_id, endpoint_id, inventory_id, package_name, version, arch, source, created_at, release, kb_article, severity, install_date, category, publisher FROM endpoint_packages
WHERE inventory_id = $1 AND tenant_id = $2
ORDER BY package_name
LIMIT 5000
`

type ListEndpointPackagesParams struct {
	InventoryID pgtype.UUID `json:"inventory_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListEndpointPackages(ctx context.Context, arg ListEndpointPackagesParams) ([]EndpointPackage, error) {
	rows, err := q.db.Query(ctx, listEndpointPackages, arg.InventoryID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndpointPackage{}
	for rows.Next() {
		var i EndpointPackage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.InventoryID,
			&i.PackageName,
			&i.Version,
			&i.Arch,
			&i.Source,
			&i.CreatedAt,
			&i.Release,
			&i.KbArticle,
			&i.Severity,
			&i.InstallDate,
			&i.Category,
			&i.Publisher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointPackagesByEndpoint = `-- name: ListEndpointPackagesByEndpoint :many
SELECT ep.id, ep.package_name, ep.version, ep.arch, ep.source, ep.release, ep.created_at
FROM endpoint_packages ep
JOIN endpoint_inventories ei ON ep.inventory_id = ei.id
WHERE ep.endpoint_id = $1 AND ep.tenant_id = $2
  AND ei.id = (
    SELECT id FROM endpoint_inventories
    WHERE endpoint_id = $1 AND tenant_id = $2
    ORDER BY scanned_at DESC LIMIT 1
  )
ORDER BY ep.package_name
LIMIT 5000
`

type ListEndpointPackagesByEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

type ListEndpointPackagesByEndpointRow struct {
	ID          pgtype.UUID        `json:"id"`
	PackageName string             `json:"package_name"`
	Version     string             `json:"version"`
	Arch        pgtype.Text        `json:"arch"`
	Source      pgtype.Text        `json:"source"`
	Release     pgtype.Text        `json:"release"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEndpointPackagesByEndpoint(ctx context.Context, arg ListEndpointPackagesByEndpointParams) ([]ListEndpointPackagesByEndpointRow, error) {
	rows, err := q.db.Query(ctx, listEndpointPackagesByEndpoint, arg.EndpointID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointPackagesByEndpointRow{}
	for rows.Next() {
		var i ListEndpointPackagesByEndpointRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageName,
			&i.Version,
			&i.Arch,
			&i.Source,
			&i.Release,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
