// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationHistory = `-- name: CountNotificationHistory :one
SELECT count(*) FROM notification_history
WHERE tenant_id = $1
  AND ($2::TEXT IS NULL OR trigger_type = $2)
  AND ($3::TEXT IS NULL OR status = $3)
  AND ($4::TEXT IS NULL OR channel_type = $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
  AND ($6::TIMESTAMPTZ IS NULL OR created_at <= $6)
`

type CountNotificationHistoryParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	TriggerType pgtype.Text        `json:"trigger_type"`
	Status      pgtype.Text        `json:"status"`
	ChannelType pgtype.Text        `json:"channel_type"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
}

func (q *Queries) CountNotificationHistory(ctx context.Context, arg CountNotificationHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationHistory,
		arg.TenantID,
		arg.TriggerType,
		arg.Status,
		arg.ChannelType,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (tenant_id, name, channel_type, config_encrypted, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, channel_type, config_encrypted, enabled, created_at, updated_at, last_tested_at, last_test_status
`

type CreateNotificationChannelParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Name            string      `json:"name"`
	ChannelType     string      `json:"channel_type"`
	ConfigEncrypted []byte      `json:"config_encrypted"`
	Enabled         bool        `json:"enabled"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.TenantID,
		arg.Name,
		arg.ChannelType,
		arg.ConfigEncrypted,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastTestedAt,
		&i.LastTestStatus,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels
WHERE id = $1 AND tenant_id = $2
`

type DeleteNotificationChannelParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDigestConfig = `-- name: GetDigestConfig :one
SELECT id, tenant_id, frequency, delivery_time, format FROM notification_digest_config
WHERE tenant_id = $1
`

func (q *Queries) GetDigestConfig(ctx context.Context, tenantID pgtype.UUID) (NotificationDigestConfig, error) {
	row := q.db.QueryRow(ctx, getDigestConfig, tenantID)
	var i NotificationDigestConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Frequency,
		&i.DeliveryTime,
		&i.Format,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, tenant_id, name, channel_type, config_encrypted, enabled, created_at, updated_at, last_tested_at, last_test_status FROM notification_channels
WHERE id = $1 AND tenant_id = $2
`

type GetNotificationChannelParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.TenantID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastTestedAt,
		&i.LastTestStatus,
	)
	return i, err
}

const getNotificationChannelByType = `-- name: GetNotificationChannelByType :one
SELECT id, tenant_id, name, channel_type, config_encrypted, enabled, created_at, updated_at, last_tested_at, last_test_status FROM notification_channels
WHERE tenant_id = $1 AND channel_type = $2
LIMIT 1
`

type GetNotificationChannelByTypeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChannelType string      `json:"channel_type"`
}

func (q *Queries) GetNotificationChannelByType(ctx context.Context, arg GetNotificationChannelByTypeParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByType, arg.TenantID, arg.ChannelType)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastTestedAt,
		&i.LastTestStatus,
	)
	return i, err
}

const getNotificationHistoryByID = `-- name: GetNotificationHistoryByID :one
SELECT id, tenant_id, trigger_type, channel_id, user_id, status, payload, error_message, created_at, channel_type, recipient, subject, retry_count FROM notification_history
WHERE id = $1 AND tenant_id = $2
`

type GetNotificationHistoryByIDParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNotificationHistoryByID(ctx context.Context, arg GetNotificationHistoryByIDParams) (NotificationHistory, error) {
	row := q.db.QueryRow(ctx, getNotificationHistoryByID, arg.ID, arg.TenantID)
	var i NotificationHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TriggerType,
		&i.ChannelID,
		&i.UserID,
		&i.Status,
		&i.Payload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ChannelType,
		&i.Recipient,
		&i.Subject,
		&i.RetryCount,
	)
	return i, err
}

const insertNotificationHistory = `-- name: InsertNotificationHistory :exec
INSERT INTO notification_history (id, tenant_id, trigger_type, channel_id, channel_type, recipient, subject, user_id, status, payload, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertNotificationHistoryParams struct {
	ID           string      `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	TriggerType  string      `json:"trigger_type"`
	ChannelID    pgtype.UUID `json:"channel_id"`
	ChannelType  pgtype.Text `json:"channel_type"`
	Recipient    string      `json:"recipient"`
	Subject      string      `json:"subject"`
	UserID       string      `json:"user_id"`
	Status       string      `json:"status"`
	Payload      []byte      `json:"payload"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) InsertNotificationHistory(ctx context.Context, arg InsertNotificationHistoryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationHistory,
		arg.ID,
		arg.TenantID,
		arg.TriggerType,
		arg.ChannelID,
		arg.ChannelType,
		arg.Recipient,
		arg.Subject,
		arg.UserID,
		arg.Status,
		arg.Payload,
		arg.ErrorMessage,
	)
	return err
}

const listEnabledPreferencesForTrigger = `-- name: ListEnabledPreferencesForTrigger :many
SELECT np.id, np.tenant_id, np.user_id, np.trigger_type, np.email_enabled, np.slack_enabled, np.webhook_enabled, np.urgency, nc.config_encrypted, nc.channel_type, nc.name AS channel_name, nc.id AS channel_id
FROM notification_preferences np
JOIN notification_channels nc ON nc.tenant_id = np.tenant_id AND nc.enabled = true
WHERE np.tenant_id = $1
  AND np.trigger_type = $2
  AND (
      (np.email_enabled   AND nc.channel_type = 'email')   OR
      (np.slack_enabled   AND nc.channel_type = 'slack')   OR
      (np.webhook_enabled AND nc.channel_type = 'webhook')
  )
`

type ListEnabledPreferencesForTriggerParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	TriggerType string      `json:"trigger_type"`
}

type ListEnabledPreferencesForTriggerRow struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	UserID          string      `json:"user_id"`
	TriggerType     string      `json:"trigger_type"`
	EmailEnabled    bool        `json:"email_enabled"`
	SlackEnabled    bool        `json:"slack_enabled"`
	WebhookEnabled  bool        `json:"webhook_enabled"`
	Urgency         string      `json:"urgency"`
	ConfigEncrypted []byte      `json:"config_encrypted"`
	ChannelType     string      `json:"channel_type"`
	ChannelName     string      `json:"channel_name"`
	ChannelID       pgtype.UUID `json:"channel_id"`
}

func (q *Queries) ListEnabledPreferencesForTrigger(ctx context.Context, arg ListEnabledPreferencesForTriggerParams) ([]ListEnabledPreferencesForTriggerRow, error) {
	rows, err := q.db.Query(ctx, listEnabledPreferencesForTrigger, arg.TenantID, arg.TriggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledPreferencesForTriggerRow{}
	for rows.Next() {
		var i ListEnabledPreferencesForTriggerRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TriggerType,
			&i.EmailEnabled,
			&i.SlackEnabled,
			&i.WebhookEnabled,
			&i.Urgency,
			&i.ConfigEncrypted,
			&i.ChannelType,
			&i.ChannelName,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, tenant_id, name, channel_type, config_encrypted, enabled, created_at, updated_at, last_tested_at, last_test_status FROM notification_channels
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListNotificationChannels(ctx context.Context, tenantID pgtype.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ChannelType,
			&i.ConfigEncrypted,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastTestedAt,
			&i.LastTestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationHistory = `-- name: ListNotificationHistory :many
SELECT id, tenant_id, trigger_type, channel_id, user_id, status, payload, error_message, created_at, channel_type, recipient, subject, retry_count FROM notification_history
WHERE tenant_id = $1
  AND ($3::TEXT IS NULL OR trigger_type = $3)
  AND ($4::TEXT IS NULL OR status = $4)
  AND ($5::TEXT IS NULL OR channel_type = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR created_at >= $6)
  AND ($7::TIMESTAMPTZ IS NULL OR created_at <= $7)
  AND ($8::TEXT IS NULL OR id < $8)
ORDER BY id DESC
LIMIT $2
`

type ListNotificationHistoryParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Limit       int32              `json:"limit"`
	TriggerType pgtype.Text        `json:"trigger_type"`
	Status      pgtype.Text        `json:"status"`
	ChannelType pgtype.Text        `json:"channel_type"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	CursorID    pgtype.Text        `json:"cursor_id"`
}

func (q *Queries) ListNotificationHistory(ctx context.Context, arg ListNotificationHistoryParams) ([]NotificationHistory, error) {
	rows, err := q.db.Query(ctx, listNotificationHistory,
		arg.TenantID,
		arg.Limit,
		arg.TriggerType,
		arg.Status,
		arg.ChannelType,
		arg.FromDate,
		arg.ToDate,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationHistory{}
	for rows.Next() {
		var i NotificationHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TriggerType,
			&i.ChannelID,
			&i.UserID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.ChannelType,
			&i.Recipient,
			&i.Subject,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT id, tenant_id, user_id, trigger_type, email_enabled, slack_enabled, webhook_enabled, urgency FROM notification_preferences
WHERE tenant_id = $1
ORDER BY trigger_type
LIMIT 100
`

func (q *Queries) ListNotificationPreferences(ctx context.Context, tenantID pgtype.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TriggerType,
			&i.EmailEnabled,
			&i.SlackEnabled,
			&i.WebhookEnabled,
			&i.Urgency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryNotificationHistory = `-- name: RetryNotificationHistory :exec
UPDATE notification_history
SET status = $3, retry_count = retry_count + 1
WHERE id = $1 AND tenant_id = $2
`

type RetryNotificationHistoryParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) RetryNotificationHistory(ctx context.Context, arg RetryNotificationHistoryParams) error {
	_, err := q.db.Exec(ctx, retryNotificationHistory, arg.ID, arg.TenantID, arg.Status)
	return err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $3,
    channel_type = $4,
    config_encrypted = $5,
    enabled = $6,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, channel_type, config_encrypted, enabled, created_at, updated_at, last_tested_at, last_test_status
`

type UpdateNotificationChannelParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	Name            string      `json:"name"`
	ChannelType     string      `json:"channel_type"`
	ConfigEncrypted []byte      `json:"config_encrypted"`
	Enabled         bool        `json:"enabled"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ChannelType,
		arg.ConfigEncrypted,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.ConfigEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastTestedAt,
		&i.LastTestStatus,
	)
	return i, err
}

const updateNotificationChannelTestResult = `-- name: UpdateNotificationChannelTestResult :exec
UPDATE notification_channels
SET last_tested_at = $3, last_test_status = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateNotificationChannelTestResultParams struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	LastTestedAt   pgtype.Timestamptz `json:"last_tested_at"`
	LastTestStatus pgtype.Text        `json:"last_test_status"`
}

func (q *Queries) UpdateNotificationChannelTestResult(ctx context.Context, arg UpdateNotificationChannelTestResultParams) error {
	_, err := q.db.Exec(ctx, updateNotificationChannelTestResult,
		arg.ID,
		arg.TenantID,
		arg.LastTestedAt,
		arg.LastTestStatus,
	)
	return err
}

const updateNotificationHistoryStatus = `-- name: UpdateNotificationHistoryStatus :exec
UPDATE notification_history
SET status = $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateNotificationHistoryStatusParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateNotificationHistoryStatus(ctx context.Context, arg UpdateNotificationHistoryStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationHistoryStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const upsertDigestConfig = `-- name: UpsertDigestConfig :one
INSERT INTO notification_digest_config (tenant_id, frequency, delivery_time, format)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id)
DO UPDATE SET
    frequency     = EXCLUDED.frequency,
    delivery_time = EXCLUDED.delivery_time,
    format        = EXCLUDED.format
RETURNING id, tenant_id, frequency, delivery_time, format
`

type UpsertDigestConfigParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Frequency    string      `json:"frequency"`
	DeliveryTime pgtype.Time `json:"delivery_time"`
	Format       string      `json:"format"`
}

func (q *Queries) UpsertDigestConfig(ctx context.Context, arg UpsertDigestConfigParams) (NotificationDigestConfig, error) {
	row := q.db.QueryRow(ctx, upsertDigestConfig,
		arg.TenantID,
		arg.Frequency,
		arg.DeliveryTime,
		arg.Format,
	)
	var i NotificationDigestConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Frequency,
		&i.DeliveryTime,
		&i.Format,
	)
	return i, err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (tenant_id, user_id, trigger_type, email_enabled, slack_enabled, webhook_enabled, urgency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, user_id, trigger_type)
DO UPDATE SET
    email_enabled   = EXCLUDED.email_enabled,
    slack_enabled   = EXCLUDED.slack_enabled,
    webhook_enabled = EXCLUDED.webhook_enabled,
    urgency         = EXCLUDED.urgency
RETURNING id, tenant_id, user_id, trigger_type, email_enabled, slack_enabled, webhook_enabled, urgency
`

type UpsertNotificationPreferenceParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	UserID         string      `json:"user_id"`
	TriggerType    string      `json:"trigger_type"`
	EmailEnabled   bool        `json:"email_enabled"`
	SlackEnabled   bool        `json:"slack_enabled"`
	WebhookEnabled bool        `json:"webhook_enabled"`
	Urgency        string      `json:"urgency"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.TenantID,
		arg.UserID,
		arg.TriggerType,
		arg.EmailEnabled,
		arg.SlackEnabled,
		arg.WebhookEnabled,
		arg.Urgency,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TriggerType,
		&i.EmailEnabled,
		&i.SlackEnabled,
		&i.WebhookEnabled,
		&i.Urgency,
	)
	return i, err
}
