// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patches.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAffectedEndpointsForCVE = `-- name: CountAffectedEndpointsForCVE :one
SELECT count(*) FROM endpoint_cves
WHERE cve_id = $1 AND tenant_id = $2
`

type CountAffectedEndpointsForCVEParams struct {
	CveID    pgtype.UUID `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CountAffectedEndpointsForCVE(ctx context.Context, arg CountAffectedEndpointsForCVEParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAffectedEndpointsForCVE, arg.CveID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAffectedEndpointsForPatch = `-- name: CountAffectedEndpointsForPatch :one
SELECT count(*) FROM (
  SELECT DISTINCT ec.endpoint_id FROM endpoint_cves ec
  WHERE ec.tenant_id = $1
    AND ec.cve_id IN (
      SELECT pc.cve_id FROM patch_cves pc
      WHERE pc.patch_id = $2 AND pc.tenant_id = $1
    )
) sub
`

type CountAffectedEndpointsForPatchParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PatchID  pgtype.UUID `json:"patch_id"`
}

func (q *Queries) CountAffectedEndpointsForPatch(ctx context.Context, arg CountAffectedEndpointsForPatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAffectedEndpointsForPatch, arg.TenantID, arg.PatchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCVEsBySeverity = `-- name: CountCVEsBySeverity :many
SELECT severity, count(*)::int AS count
FROM cves
WHERE tenant_id = $1
GROUP BY severity
LIMIT 20
`

type CountCVEsBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int32  `json:"count"`
}

func (q *Queries) CountCVEsBySeverity(ctx context.Context, tenantID pgtype.UUID) ([]CountCVEsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countCVEsBySeverity, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCVEsBySeverityRow{}
	for rows.Next() {
		var i CountCVEsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCVEsExploit = `-- name: CountCVEsExploit :one
SELECT count(*)::int AS count
FROM cves
WHERE tenant_id = $1 AND exploit_available = true
`

func (q *Queries) CountCVEsExploit(ctx context.Context, tenantID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCVEsExploit, tenantID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countCVEsFiltered = `-- name: CountCVEsFiltered :one
SELECT count(*) FROM cves c
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.severity = $2)
  AND ($3::text = '' OR c.cisa_kev_due_date IS NOT NULL)
  AND ($4::text = '' OR c.exploit_available = ($4 = 'true'))
  AND ($5::text = '' OR c.attack_vector = $5)
  AND ($6::text = '' OR c.cve_id ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL OR c.published_at >= $7)
  AND ($8::text = '' OR ($8 = 'true' AND EXISTS(SELECT 1 FROM patch_cves pc2 WHERE pc2.cve_id = c.id AND pc2.tenant_id = c.tenant_id)) OR ($8 = 'false' AND NOT EXISTS(SELECT 1 FROM patch_cves pc3 WHERE pc3.cve_id = c.id AND pc3.tenant_id = c.tenant_id)))
`

type CountCVEsFilteredParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Severity         string             `json:"severity"`
	CisaKev          string             `json:"cisa_kev"`
	ExploitAvailable string             `json:"exploit_available"`
	AttackVector     string             `json:"attack_vector"`
	Search           string             `json:"search"`
	PublishedAfter   pgtype.Timestamptz `json:"published_after"`
	HasPatch         string             `json:"has_patch"`
}

func (q *Queries) CountCVEsFiltered(ctx context.Context, arg CountCVEsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCVEsFiltered,
		arg.TenantID,
		arg.Severity,
		arg.CisaKev,
		arg.ExploitAvailable,
		arg.AttackVector,
		arg.Search,
		arg.PublishedAfter,
		arg.HasPatch,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCVEsKEV = `-- name: CountCVEsKEV :one
SELECT count(*)::int AS count
FROM cves
WHERE tenant_id = $1 AND cisa_kev_due_date IS NOT NULL
`

func (q *Queries) CountCVEsKEV(ctx context.Context, tenantID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCVEsKEV, tenantID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPatchesBySeverity = `-- name: CountPatchesBySeverity :many
SELECT p.severity, count(*)::int AS count
FROM patches p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.os_family = $2)
  AND ($3::text = '' OR p.os_distribution = $3)
  AND ($4::text = '' OR p.status = $4)
  AND ($5::text = '' OR p.name ILIKE '%' || $5 || '%')
GROUP BY p.severity
LIMIT 20
`

type CountPatchesBySeverityParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OsFamily       string      `json:"os_family"`
	OsDistribution string      `json:"os_distribution"`
	Status         string      `json:"status"`
	Search         string      `json:"search"`
}

type CountPatchesBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int32  `json:"count"`
}

func (q *Queries) CountPatchesBySeverity(ctx context.Context, arg CountPatchesBySeverityParams) ([]CountPatchesBySeverityRow, error) {
	rows, err := q.db.Query(ctx, countPatchesBySeverity,
		arg.TenantID,
		arg.OsFamily,
		arg.OsDistribution,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPatchesBySeverityRow{}
	for rows.Next() {
		var i CountPatchesBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPatchesFiltered = `-- name: CountPatchesFiltered :one
SELECT count(*) FROM patches p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.severity = $2)
  AND ($3::text = '' OR p.os_family = $3)
  AND ($4::text = '' OR p.os_distribution = $4)
  AND ($5::text = '' OR p.status = $5)
  AND ($6::text = '' OR p.name ILIKE '%' || $6 || '%')
`

type CountPatchesFilteredParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Severity       string      `json:"severity"`
	OsFamily       string      `json:"os_family"`
	OsDistribution string      `json:"os_distribution"`
	Status         string      `json:"status"`
	Search         string      `json:"search"`
}

func (q *Queries) CountPatchesFiltered(ctx context.Context, arg CountPatchesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPatchesFiltered,
		arg.TenantID,
		arg.Severity,
		arg.OsFamily,
		arg.OsDistribution,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCVE = `-- name: CreateCVE :one
INSERT INTO cves (tenant_id, cve_id, severity, description, published_at,
    cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available,
    attack_vector, external_references, cwe_id, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source
`

type CreateCVEParams struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable   bool               `json:"exploit_available"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	ExternalReferences []byte             `json:"external_references"`
	CweID              pgtype.Text        `json:"cwe_id"`
	Source             string             `json:"source"`
}

func (q *Queries) CreateCVE(ctx context.Context, arg CreateCVEParams) (CVE, error) {
	row := q.db.QueryRow(ctx, createCVE,
		arg.TenantID,
		arg.CveID,
		arg.Severity,
		arg.Description,
		arg.PublishedAt,
		arg.CvssV3Score,
		arg.CvssV3Vector,
		arg.CisaKevDueDate,
		arg.ExploitAvailable,
		arg.AttackVector,
		arg.ExternalReferences,
		arg.CweID,
		arg.Source,
	)
	var i CVE
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.CisaKevDueDate,
		&i.ExploitAvailable,
		&i.NvdLastModified,
		&i.AttackVector,
		&i.ExternalReferences,
		&i.CweID,
		&i.Source,
	)
	return i, err
}

const createPatch = `-- name: CreatePatch :one
INSERT INTO patches (tenant_id, name, version, severity, os_family, status,
    os_distribution, package_url, checksum_sha256, source_repo, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id
`

type CreatePatchParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Name           string      `json:"name"`
	Version        string      `json:"version"`
	Severity       string      `json:"severity"`
	OsFamily       string      `json:"os_family"`
	Status         string      `json:"status"`
	OsDistribution pgtype.Text `json:"os_distribution"`
	PackageUrl     pgtype.Text `json:"package_url"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
	SourceRepo     pgtype.Text `json:"source_repo"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreatePatch(ctx context.Context, arg CreatePatchParams) (Patch, error) {
	row := q.db.QueryRow(ctx, createPatch,
		arg.TenantID,
		arg.Name,
		arg.Version,
		arg.Severity,
		arg.OsFamily,
		arg.Status,
		arg.OsDistribution,
		arg.PackageUrl,
		arg.ChecksumSha256,
		arg.SourceRepo,
		arg.Description,
	)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Severity,
		&i.OsFamily,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsDistribution,
		&i.PackageUrl,
		&i.ChecksumSha256,
		&i.SourceRepo,
		&i.Description,
		&i.ReleasedAt,
		&i.PackageName,
		&i.InstallerType,
		&i.SilentArgs,
		&i.DeletedAt,
		&i.HubCatalogID,
	)
	return i, err
}

const getCVEByCVEID = `-- name: GetCVEByCVEID :one
SELECT id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source FROM cves WHERE cve_id = $1 AND tenant_id = $2
`

type GetCVEByCVEIDParams struct {
	CveID    string      `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCVEByCVEID(ctx context.Context, arg GetCVEByCVEIDParams) (CVE, error) {
	row := q.db.QueryRow(ctx, getCVEByCVEID, arg.CveID, arg.TenantID)
	var i CVE
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.CisaKevDueDate,
		&i.ExploitAvailable,
		&i.NvdLastModified,
		&i.AttackVector,
		&i.ExternalReferences,
		&i.CweID,
		&i.Source,
	)
	return i, err
}

const getCVEByID = `-- name: GetCVEByID :one
SELECT id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source FROM cves WHERE id = $1 AND tenant_id = $2
`

type GetCVEByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCVEByID(ctx context.Context, arg GetCVEByIDParams) (CVE, error) {
	row := q.db.QueryRow(ctx, getCVEByID, arg.ID, arg.TenantID)
	var i CVE
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.CisaKevDueDate,
		&i.ExploitAvailable,
		&i.NvdLastModified,
		&i.AttackVector,
		&i.ExternalReferences,
		&i.CweID,
		&i.Source,
	)
	return i, err
}

const getPatchByID = `-- name: GetPatchByID :one
SELECT id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id FROM patches WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetPatchByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPatchByID(ctx context.Context, arg GetPatchByIDParams) (Patch, error) {
	row := q.db.QueryRow(ctx, getPatchByID, arg.ID, arg.TenantID)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Severity,
		&i.OsFamily,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsDistribution,
		&i.PackageUrl,
		&i.ChecksumSha256,
		&i.SourceRepo,
		&i.Description,
		&i.ReleasedAt,
		&i.PackageName,
		&i.InstallerType,
		&i.SilentArgs,
		&i.DeletedAt,
		&i.HubCatalogID,
	)
	return i, err
}

const getPatchHighestCVSS = `-- name: GetPatchHighestCVSS :one
SELECT COALESCE(MAX(c.cvss_v3_score), 0)::float8 AS highest_cvss
FROM cves c
JOIN patch_cves pc ON c.id = pc.cve_id AND c.tenant_id = pc.tenant_id
WHERE pc.patch_id = $1 AND pc.tenant_id = $2
`

type GetPatchHighestCVSSParams struct {
	PatchID  pgtype.UUID `json:"patch_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPatchHighestCVSS(ctx context.Context, arg GetPatchHighestCVSSParams) (float64, error) {
	row := q.db.QueryRow(ctx, getPatchHighestCVSS, arg.PatchID, arg.TenantID)
	var highest_cvss float64
	err := row.Scan(&highest_cvss)
	return highest_cvss, err
}

const getPatchRemediation = `-- name: GetPatchRemediation :one
SELECT
  count(*) FILTER (WHERE ec.status != 'patched')::int AS endpoints_affected,
  count(*) FILTER (WHERE ec.status = 'patched')::int AS endpoints_patched,
  count(*) FILTER (WHERE ec.status NOT IN ('patched', 'mitigated', 'ignored'))::int AS endpoints_pending,
  count(*) FILTER (WHERE ec.status = 'mitigated')::int AS endpoints_failed
FROM endpoint_cves ec
WHERE ec.tenant_id = $1
  AND ec.cve_id IN (
    SELECT pc.cve_id FROM patch_cves pc
    WHERE pc.patch_id = $2 AND pc.tenant_id = $1
  )
`

type GetPatchRemediationParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PatchID  pgtype.UUID `json:"patch_id"`
}

type GetPatchRemediationRow struct {
	EndpointsAffected int32 `json:"endpoints_affected"`
	EndpointsPatched  int32 `json:"endpoints_patched"`
	EndpointsPending  int32 `json:"endpoints_pending"`
	EndpointsFailed   int32 `json:"endpoints_failed"`
}

func (q *Queries) GetPatchRemediation(ctx context.Context, arg GetPatchRemediationParams) (GetPatchRemediationRow, error) {
	row := q.db.QueryRow(ctx, getPatchRemediation, arg.TenantID, arg.PatchID)
	var i GetPatchRemediationRow
	err := row.Scan(
		&i.EndpointsAffected,
		&i.EndpointsPatched,
		&i.EndpointsPending,
		&i.EndpointsFailed,
	)
	return i, err
}

const linkPatchCVE = `-- name: LinkPatchCVE :exec
INSERT INTO patch_cves (tenant_id, patch_id, cve_id, version_end_excluding, version_end_including)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, patch_id, cve_id)
DO UPDATE SET
    version_end_excluding = EXCLUDED.version_end_excluding,
    version_end_including = EXCLUDED.version_end_including
`

type LinkPatchCVEParams struct {
	TenantID            pgtype.UUID `json:"tenant_id"`
	PatchID             pgtype.UUID `json:"patch_id"`
	CveID               pgtype.UUID `json:"cve_id"`
	VersionEndExcluding string      `json:"version_end_excluding"`
	VersionEndIncluding string      `json:"version_end_including"`
}

func (q *Queries) LinkPatchCVE(ctx context.Context, arg LinkPatchCVEParams) error {
	_, err := q.db.Exec(ctx, linkPatchCVE,
		arg.TenantID,
		arg.PatchID,
		arg.CveID,
		arg.VersionEndExcluding,
		arg.VersionEndIncluding,
	)
	return err
}

const listAffectedEndpointsForCVE = `-- name: ListAffectedEndpointsForCVE :many
SELECT e.id, e.hostname, e.os_family, e.os_version, e.ip_address,
       ec.status, ec.detected_at,
       e.agent_version, e.last_seen,
       tg.group_names
FROM endpoint_cves ec
JOIN endpoints e ON ec.endpoint_id = e.id AND ec.tenant_id = e.tenant_id
LEFT JOIN LATERAL (
    SELECT string_agg(t.key || '=' || t.value, ', ' ORDER BY t.key, t.value) AS group_names
    FROM endpoint_tags et
    JOIN tags t ON t.id = et.tag_id AND t.tenant_id = et.tenant_id
    WHERE et.endpoint_id = e.id AND et.tenant_id = e.tenant_id
) tg ON true
WHERE ec.cve_id = $1 AND ec.tenant_id = $2
ORDER BY ec.detected_at DESC
LIMIT 50
`

type ListAffectedEndpointsForCVEParams struct {
	CveID    pgtype.UUID `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListAffectedEndpointsForCVERow struct {
	ID           pgtype.UUID        `json:"id"`
	Hostname     string             `json:"hostname"`
	OsFamily     string             `json:"os_family"`
	OsVersion    string             `json:"os_version"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	Status       string             `json:"status"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	GroupNames   []byte             `json:"group_names"`
}

// group_names was a comma-joined string of group display names; in the
// key=value world we return a comma-joined "key=value" list for the same
// rendering slot. Column name preserved to keep the consumer DTO stable.
func (q *Queries) ListAffectedEndpointsForCVE(ctx context.Context, arg ListAffectedEndpointsForCVEParams) ([]ListAffectedEndpointsForCVERow, error) {
	rows, err := q.db.Query(ctx, listAffectedEndpointsForCVE, arg.CveID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedEndpointsForCVERow{}
	for rows.Next() {
		var i ListAffectedEndpointsForCVERow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.OsFamily,
			&i.OsVersion,
			&i.IpAddress,
			&i.Status,
			&i.DetectedAt,
			&i.AgentVersion,
			&i.LastSeen,
			&i.GroupNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAffectedEndpointsForPatch = `-- name: ListAffectedEndpointsForPatch :many
SELECT DISTINCT
    e.id,
    e.hostname,
    e.os_family,
    e.agent_version,
    e.status,
    e.last_seen,
    (
        SELECT MAX(dt2.completed_at)
        FROM deployment_targets dt2
        JOIN deployments d2 ON dt2.deployment_id = d2.id AND dt2.tenant_id = d2.tenant_id
        WHERE dt2.endpoint_id = e.id
          AND dt2.tenant_id = e.tenant_id
          AND dt2.patch_id = $1
          AND d2.status = 'success'
    ) AS last_deployed_at,
    CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM endpoint_cves ec2
            JOIN patch_cves pc2 ON ec2.cve_id = pc2.cve_id AND ec2.tenant_id = pc2.tenant_id
            WHERE pc2.patch_id = $1 AND ec2.endpoint_id = e.id AND ec2.tenant_id = e.tenant_id
              AND ec2.status != 'patched'
        ) THEN 'deployed'
        WHEN EXISTS (
            SELECT 1 FROM endpoint_cves ec2
            JOIN patch_cves pc2 ON ec2.cve_id = pc2.cve_id AND ec2.tenant_id = pc2.tenant_id
            WHERE pc2.patch_id = $1 AND ec2.endpoint_id = e.id AND ec2.tenant_id = e.tenant_id
              AND ec2.status = 'mitigated'
        ) THEN 'failed'
        ELSE 'pending'
    END AS patch_status
FROM endpoints e
JOIN endpoint_cves ec ON e.id = ec.endpoint_id AND e.tenant_id = ec.tenant_id
JOIN patch_cves pc ON ec.cve_id = pc.cve_id AND ec.tenant_id = pc.tenant_id
WHERE pc.patch_id = $1 AND pc.tenant_id = $2
ORDER BY e.hostname
LIMIT 50
`

type ListAffectedEndpointsForPatchParams struct {
	PatchID  pgtype.UUID `json:"patch_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListAffectedEndpointsForPatchRow struct {
	ID             pgtype.UUID        `json:"id"`
	Hostname       string             `json:"hostname"`
	OsFamily       string             `json:"os_family"`
	AgentVersion   pgtype.Text        `json:"agent_version"`
	Status         string             `json:"status"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
	LastDeployedAt interface{}        `json:"last_deployed_at"`
	PatchStatus    string             `json:"patch_status"`
}

func (q *Queries) ListAffectedEndpointsForPatch(ctx context.Context, arg ListAffectedEndpointsForPatchParams) ([]ListAffectedEndpointsForPatchRow, error) {
	rows, err := q.db.Query(ctx, listAffectedEndpointsForPatch, arg.PatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedEndpointsForPatchRow{}
	for rows.Next() {
		var i ListAffectedEndpointsForPatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.OsFamily,
			&i.AgentVersion,
			&i.Status,
			&i.LastSeen,
			&i.LastDeployedAt,
			&i.PatchStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEsByTenant = `-- name: ListCVEsByTenant :many
SELECT id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source FROM cves WHERE tenant_id = $1 ORDER BY published_at DESC NULLS LAST LIMIT 1000
`

func (q *Queries) ListCVEsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]CVE, error) {
	rows, err := q.db.Query(ctx, listCVEsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CVE{}
	for rows.Next() {
		var i CVE
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.NvdLastModified,
			&i.AttackVector,
			&i.ExternalReferences,
			&i.CweID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEsFiltered = `-- name: ListCVEsFiltered :many
SELECT c.id, c.tenant_id, c.cve_id, c.severity, c.description, c.published_at, c.created_at, c.updated_at, c.cvss_v3_score, c.cvss_v3_vector, c.cisa_kev_due_date, c.exploit_available, c.nvd_last_modified, c.attack_vector, c.external_references, c.cwe_id, c.source,
       (SELECT count(*) FROM endpoint_cves ec WHERE ec.cve_id = c.id AND ec.tenant_id = c.tenant_id)::int AS affected_endpoint_count,
       EXISTS(SELECT 1 FROM patch_cves pc WHERE pc.cve_id = c.id AND pc.tenant_id = c.tenant_id) AS patch_available,
       (SELECT count(*)::int FROM patch_cves pc WHERE pc.cve_id = c.id AND pc.tenant_id = c.tenant_id) AS patch_count
FROM cves c
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.severity = $2)
  AND ($3::text = '' OR c.cisa_kev_due_date IS NOT NULL)
  AND ($4::text = '' OR c.exploit_available = ($4 = 'true'))
  AND ($5::text = '' OR c.attack_vector = $5)
  AND ($6::text = '' OR c.cve_id ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL OR c.published_at >= $7)
  AND ($8::text = '' OR ($8 = 'true' AND EXISTS(SELECT 1 FROM patch_cves pc2 WHERE pc2.cve_id = c.id AND pc2.tenant_id = c.tenant_id)) OR ($8 = 'false' AND NOT EXISTS(SELECT 1 FROM patch_cves pc3 WHERE pc3.cve_id = c.id AND pc3.tenant_id = c.tenant_id)))
  AND (
    $9::timestamptz IS NULL
    OR (c.created_at, c.id) < ($9, $10::uuid)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $11
`

type ListCVEsFilteredParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Severity         string             `json:"severity"`
	CisaKev          string             `json:"cisa_kev"`
	ExploitAvailable string             `json:"exploit_available"`
	AttackVector     string             `json:"attack_vector"`
	Search           string             `json:"search"`
	PublishedAfter   pgtype.Timestamptz `json:"published_after"`
	HasPatch         string             `json:"has_patch"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	PageLimit        int32              `json:"page_limit"`
}

type ListCVEsFilteredRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	CveID                 string             `json:"cve_id"`
	Severity              string             `json:"severity"`
	Description           pgtype.Text        `json:"description"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CvssV3Score           pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector          pgtype.Text        `json:"cvss_v3_vector"`
	CisaKevDueDate        pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable      bool               `json:"exploit_available"`
	NvdLastModified       pgtype.Timestamptz `json:"nvd_last_modified"`
	AttackVector          pgtype.Text        `json:"attack_vector"`
	ExternalReferences    []byte             `json:"external_references"`
	CweID                 pgtype.Text        `json:"cwe_id"`
	Source                string             `json:"source"`
	AffectedEndpointCount int32              `json:"affected_endpoint_count"`
	PatchAvailable        bool               `json:"patch_available"`
	PatchCount            int32              `json:"patch_count"`
}

func (q *Queries) ListCVEsFiltered(ctx context.Context, arg ListCVEsFilteredParams) ([]ListCVEsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listCVEsFiltered,
		arg.TenantID,
		arg.Severity,
		arg.CisaKev,
		arg.ExploitAvailable,
		arg.AttackVector,
		arg.Search,
		arg.PublishedAfter,
		arg.HasPatch,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVEsFilteredRow{}
	for rows.Next() {
		var i ListCVEsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.NvdLastModified,
			&i.AttackVector,
			&i.ExternalReferences,
			&i.CweID,
			&i.Source,
			&i.AffectedEndpointCount,
			&i.PatchAvailable,
			&i.PatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEsForPatch = `-- name: ListCVEsForPatch :many
SELECT c.id, c.tenant_id, c.cve_id, c.severity, c.description, c.published_at, c.created_at, c.updated_at, c.cvss_v3_score, c.cvss_v3_vector, c.cisa_kev_due_date, c.exploit_available, c.nvd_last_modified, c.attack_vector, c.external_references, c.cwe_id, c.source FROM cves c
JOIN patch_cves pc ON c.id = pc.cve_id AND c.tenant_id = pc.tenant_id
WHERE pc.patch_id = $1 AND pc.tenant_id = $2
ORDER BY c.severity
LIMIT 1000
`

type ListCVEsForPatchParams struct {
	PatchID  pgtype.UUID `json:"patch_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListCVEsForPatch(ctx context.Context, arg ListCVEsForPatchParams) ([]CVE, error) {
	rows, err := q.db.Query(ctx, listCVEsForPatch, arg.PatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CVE{}
	for rows.Next() {
		var i CVE
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.NvdLastModified,
			&i.AttackVector,
			&i.ExternalReferences,
			&i.CweID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentHistoryForPatch = `-- name: ListDeploymentHistoryForPatch :many
SELECT DISTINCT
    d.id,
    d.status,
    d.created_by,
    d.started_at,
    d.completed_at,
    d.total_targets,
    d.success_count,
    d.failed_count,
    d.created_at
FROM deployments d
JOIN deployment_targets dt ON d.id = dt.deployment_id AND d.tenant_id = dt.tenant_id
WHERE dt.patch_id = $1 AND dt.tenant_id = $2
ORDER BY d.created_at DESC
LIMIT 20
`

type ListDeploymentHistoryForPatchParams struct {
	PatchID  pgtype.UUID `json:"patch_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListDeploymentHistoryForPatchRow struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	TotalTargets int32              `json:"total_targets"`
	SuccessCount int32              `json:"success_count"`
	FailedCount  int32              `json:"failed_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDeploymentHistoryForPatch(ctx context.Context, arg ListDeploymentHistoryForPatchParams) ([]ListDeploymentHistoryForPatchRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentHistoryForPatch, arg.PatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentHistoryForPatchRow{}
	for rows.Next() {
		var i ListDeploymentHistoryForPatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalTargets,
			&i.SuccessCount,
			&i.FailedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForPatch = `-- name: ListDeploymentsForPatch :many
SELECT DISTINCT d.id, d.status, d.started_at, d.completed_at, d.created_at,
       d.total_targets, d.success_count, d.failed_count
FROM deployments d
JOIN deployment_targets dt ON d.id = dt.deployment_id AND d.tenant_id = dt.tenant_id
WHERE dt.patch_id = $1 AND dt.tenant_id = $2
ORDER BY d.created_at DESC
LIMIT 20
`

type ListDeploymentsForPatchParams struct {
	PatchID  pgtype.UUID `json:"patch_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListDeploymentsForPatchRow struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TotalTargets int32              `json:"total_targets"`
	SuccessCount int32              `json:"success_count"`
	FailedCount  int32              `json:"failed_count"`
}

func (q *Queries) ListDeploymentsForPatch(ctx context.Context, arg ListDeploymentsForPatchParams) ([]ListDeploymentsForPatchRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForPatch, arg.PatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsForPatchRow{}
	for rows.Next() {
		var i ListDeploymentsForPatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.TotalTargets,
			&i.SuccessCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchesByTenant = `-- name: ListPatchesByTenant :many
SELECT id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id FROM patches WHERE tenant_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1000
`

func (q *Queries) ListPatchesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Patch, error) {
	rows, err := q.db.Query(ctx, listPatchesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsDistribution,
			&i.PackageUrl,
			&i.ChecksumSha256,
			&i.SourceRepo,
			&i.Description,
			&i.ReleasedAt,
			&i.PackageName,
			&i.InstallerType,
			&i.SilentArgs,
			&i.DeletedAt,
			&i.HubCatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchesFiltered = `-- name: ListPatchesFiltered :many
WITH patch_cve_stats AS (
    SELECT pc.patch_id,
           count(*)::int AS cve_count,
           COALESCE(MAX(c.cvss_v3_score), 0)::float8 AS highest_cvss_score
    FROM patch_cves pc
    JOIN cves c ON c.id = pc.cve_id AND c.tenant_id = pc.tenant_id
    WHERE pc.tenant_id = $1
    GROUP BY pc.patch_id
),
patch_remediation AS (
    SELECT pc.patch_id,
           CASE WHEN count(*) = 0 THEN 0
                ELSE (count(*) FILTER (WHERE ec.status = 'patched') * 100 / count(*))::int
           END AS remediation_pct,
           count(DISTINCT ec.endpoint_id) FILTER (WHERE ec.status = 'patched')::int AS endpoints_deployed_count,
           count(DISTINCT ec.endpoint_id)::int AS affected_endpoint_count
    FROM patch_cves pc
    JOIN endpoint_cves ec ON ec.cve_id = pc.cve_id AND ec.tenant_id = pc.tenant_id
    WHERE pc.tenant_id = $1
    GROUP BY pc.patch_id
)
SELECT p.id, p.tenant_id, p.name, p.version, p.severity, p.os_family, p.status, p.created_at, p.updated_at, p.os_distribution, p.package_url, p.checksum_sha256, p.source_repo, p.description, p.released_at, p.package_name, p.installer_type, p.silent_args, p.deleted_at, p.hub_catalog_id,
       COALESCE(pcs.cve_count, 0)::int AS cve_count,
       COALESCE(pcs.highest_cvss_score, 0)::float8 AS highest_cvss_score,
       COALESCE(pr.remediation_pct, 0)::int AS remediation_pct,
       COALESCE(pr.endpoints_deployed_count, 0)::int AS endpoints_deployed_count,
       COALESCE(pr.affected_endpoint_count, 0)::int AS affected_endpoint_count
FROM patches p
LEFT JOIN patch_cve_stats pcs ON pcs.patch_id = p.id
LEFT JOIN patch_remediation pr ON pr.patch_id = p.id
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.severity = $2)
  AND ($3::text = '' OR p.os_family = $3)
  AND ($4::text = '' OR p.os_distribution = $4)
  AND ($5::text = '' OR p.status = $5)
  AND ($6::text = '' OR p.name ILIKE '%' || $6 || '%')
  AND (
    $7::timestamptz IS NULL
    OR (p.created_at, p.id) < ($7, $8::uuid)
  )
ORDER BY
  CASE WHEN $9::text = 'name'     AND $10::text = 'asc'  THEN p.name END ASC NULLS LAST,
  CASE WHEN $9::text = 'name'     AND $10::text = 'desc' THEN p.name END DESC NULLS LAST,
  CASE WHEN $9::text = 'severity' AND $10::text = 'asc'  THEN CASE p.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END END ASC,
  CASE WHEN $9::text = 'severity' AND $10::text = 'desc' THEN CASE p.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END END DESC,
  CASE WHEN $9::text = 'cvss'     AND $10::text = 'asc'  THEN COALESCE(pcs.highest_cvss_score, 0) END ASC,
  CASE WHEN $9::text = 'cvss'     AND $10::text = 'desc' THEN COALESCE(pcs.highest_cvss_score, 0) END DESC,
  CASE WHEN $9::text = 'cves'     AND $10::text = 'asc'  THEN COALESCE(pcs.cve_count, 0) END ASC,
  CASE WHEN $9::text = 'cves'     AND $10::text = 'desc' THEN COALESCE(pcs.cve_count, 0) END DESC,
  CASE WHEN $9::text = 'affected' AND $10::text = 'asc'  THEN COALESCE(pr.affected_endpoint_count, 0) END ASC,
  CASE WHEN $9::text = 'affected' AND $10::text = 'desc' THEN COALESCE(pr.affected_endpoint_count, 0) END DESC,
  p.created_at DESC, p.id DESC
LIMIT $11
`

type ListPatchesFilteredParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Severity        string             `json:"severity"`
	OsFamily        string             `json:"os_family"`
	OsDistribution  string             `json:"os_distribution"`
	Status          string             `json:"status"`
	Search          string             `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	SortBy          string             `json:"sort_by"`
	SortDir         string             `json:"sort_dir"`
	PageLimit       int32              `json:"page_limit"`
}

type ListPatchesFilteredRow struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	Name                   string             `json:"name"`
	Version                string             `json:"version"`
	Severity               string             `json:"severity"`
	OsFamily               string             `json:"os_family"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OsDistribution         pgtype.Text        `json:"os_distribution"`
	PackageUrl             pgtype.Text        `json:"package_url"`
	ChecksumSha256         pgtype.Text        `json:"checksum_sha256"`
	SourceRepo             pgtype.Text        `json:"source_repo"`
	Description            pgtype.Text        `json:"description"`
	ReleasedAt             pgtype.Timestamptz `json:"released_at"`
	PackageName            string             `json:"package_name"`
	InstallerType          string             `json:"installer_type"`
	SilentArgs             string             `json:"silent_args"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	HubCatalogID           pgtype.UUID        `json:"hub_catalog_id"`
	CveCount               int32              `json:"cve_count"`
	HighestCvssScore       float64            `json:"highest_cvss_score"`
	RemediationPct         int32              `json:"remediation_pct"`
	EndpointsDeployedCount int32              `json:"endpoints_deployed_count"`
	AffectedEndpointCount  int32              `json:"affected_endpoint_count"`
}

func (q *Queries) ListPatchesFiltered(ctx context.Context, arg ListPatchesFilteredParams) ([]ListPatchesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listPatchesFiltered,
		arg.TenantID,
		arg.Severity,
		arg.OsFamily,
		arg.OsDistribution,
		arg.Status,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.SortBy,
		arg.SortDir,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatchesFilteredRow{}
	for rows.Next() {
		var i ListPatchesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsDistribution,
			&i.PackageUrl,
			&i.ChecksumSha256,
			&i.SourceRepo,
			&i.Description,
			&i.ReleasedAt,
			&i.PackageName,
			&i.InstallerType,
			&i.SilentArgs,
			&i.DeletedAt,
			&i.HubCatalogID,
			&i.CveCount,
			&i.HighestCvssScore,
			&i.RemediationPct,
			&i.EndpointsDeployedCount,
			&i.AffectedEndpointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchesForCVEDetail = `-- name: ListPatchesForCVEDetail :many
WITH patch_stats AS (
    SELECT pc2.patch_id,
           count(DISTINCT ec2.endpoint_id)::int AS endpoints_covered,
           count(DISTINCT ec2.endpoint_id) FILTER (WHERE ec2.status = 'patched')::int AS endpoints_patched
    FROM patch_cves pc2
    JOIN endpoint_cves ec2 ON ec2.cve_id = pc2.cve_id AND ec2.tenant_id = pc2.tenant_id
    WHERE pc2.tenant_id = $2
    GROUP BY pc2.patch_id
)
SELECT p.id, p.name, p.version, p.severity, p.os_family, p.created_at,
       COALESCE(ps.endpoints_covered, 0) AS endpoints_covered,
       COALESCE(ps.endpoints_patched, 0) AS endpoints_patched
FROM patches p
JOIN patch_cves pc ON p.id = pc.patch_id AND p.tenant_id = pc.tenant_id
LEFT JOIN patch_stats ps ON ps.patch_id = p.id
WHERE pc.cve_id = $1 AND pc.tenant_id = $2
  AND p.deleted_at IS NULL
LIMIT 100
`

type ListPatchesForCVEDetailParams struct {
	CveID    pgtype.UUID `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListPatchesForCVEDetailRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Version          string             `json:"version"`
	Severity         string             `json:"severity"`
	OsFamily         string             `json:"os_family"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EndpointsCovered int32              `json:"endpoints_covered"`
	EndpointsPatched int32              `json:"endpoints_patched"`
}

func (q *Queries) ListPatchesForCVEDetail(ctx context.Context, arg ListPatchesForCVEDetailParams) ([]ListPatchesForCVEDetailRow, error) {
	rows, err := q.db.Query(ctx, listPatchesForCVEDetail, arg.CveID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatchesForCVEDetailRow{}
	for rows.Next() {
		var i ListPatchesForCVEDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.CreatedAt,
			&i.EndpointsCovered,
			&i.EndpointsPatched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedCVEsForCVE = `-- name: ListRelatedCVEsForCVE :many
SELECT DISTINCT c.id, c.cve_id, c.severity, c.cvss_v3_score
FROM patch_cves pc1
JOIN patch_cves pc2 ON pc1.patch_id = pc2.patch_id AND pc1.tenant_id = pc2.tenant_id
JOIN cves c ON pc2.cve_id = c.id AND pc2.tenant_id = c.tenant_id
WHERE pc1.cve_id = $1 AND pc1.tenant_id = $2
  AND pc2.cve_id != $1
ORDER BY c.cvss_v3_score DESC NULLS LAST
LIMIT 10
`

type ListRelatedCVEsForCVEParams struct {
	CveID    pgtype.UUID `json:"cve_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListRelatedCVEsForCVERow struct {
	ID          pgtype.UUID    `json:"id"`
	CveID       string         `json:"cve_id"`
	Severity    string         `json:"severity"`
	CvssV3Score pgtype.Numeric `json:"cvss_v3_score"`
}

func (q *Queries) ListRelatedCVEsForCVE(ctx context.Context, arg ListRelatedCVEsForCVEParams) ([]ListRelatedCVEsForCVERow, error) {
	rows, err := q.db.Query(ctx, listRelatedCVEsForCVE, arg.CveID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedCVEsForCVERow{}
	for rows.Next() {
		var i ListRelatedCVEsForCVERow
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.CvssV3Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePatchesByHubIDs = `-- name: SoftDeletePatchesByHubIDs :execrows
UPDATE patches SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1 AND hub_catalog_id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type SoftDeletePatchesByHubIDsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	HubIds   []pgtype.UUID `json:"hub_ids"`
}

func (q *Queries) SoftDeletePatchesByHubIDs(ctx context.Context, arg SoftDeletePatchesByHubIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePatchesByHubIDs, arg.TenantID, arg.HubIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatch = `-- name: UpdatePatch :one
UPDATE patches
SET name = $2, version = $3, severity = $4, status = $5,
    os_distribution = $6, package_url = $7, checksum_sha256 = $8,
    source_repo = $9, description = $10, updated_at = now()
WHERE id = $1 AND tenant_id = $11
RETURNING id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id
`

type UpdatePatchParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Version        string      `json:"version"`
	Severity       string      `json:"severity"`
	Status         string      `json:"status"`
	OsDistribution pgtype.Text `json:"os_distribution"`
	PackageUrl     pgtype.Text `json:"package_url"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
	SourceRepo     pgtype.Text `json:"source_repo"`
	Description    pgtype.Text `json:"description"`
	TenantID       pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdatePatch(ctx context.Context, arg UpdatePatchParams) (Patch, error) {
	row := q.db.QueryRow(ctx, updatePatch,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Severity,
		arg.Status,
		arg.OsDistribution,
		arg.PackageUrl,
		arg.ChecksumSha256,
		arg.SourceRepo,
		arg.Description,
		arg.TenantID,
	)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Severity,
		&i.OsFamily,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsDistribution,
		&i.PackageUrl,
		&i.ChecksumSha256,
		&i.SourceRepo,
		&i.Description,
		&i.ReleasedAt,
		&i.PackageName,
		&i.InstallerType,
		&i.SilentArgs,
		&i.DeletedAt,
		&i.HubCatalogID,
	)
	return i, err
}

const upsertAgentCVE = `-- name: UpsertAgentCVE :one
INSERT INTO cves (tenant_id, cve_id, severity, description, cvss_v3_score, source)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, cve_id)
DO UPDATE SET
    severity = CASE WHEN cves.source = 'nvd' THEN cves.severity ELSE EXCLUDED.severity END,
    description = CASE WHEN COALESCE(cves.description, '') != '' THEN cves.description ELSE EXCLUDED.description END,
    cvss_v3_score = CASE WHEN cves.source = 'nvd' THEN cves.cvss_v3_score ELSE EXCLUDED.cvss_v3_score END,
    source = CASE WHEN cves.source = 'nvd' THEN cves.source ELSE EXCLUDED.source END,
    updated_at = now()
RETURNING id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source
`

type UpsertAgentCVEParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	CveID       string         `json:"cve_id"`
	Severity    string         `json:"severity"`
	Description pgtype.Text    `json:"description"`
	CvssV3Score pgtype.Numeric `json:"cvss_v3_score"`
	Source      string         `json:"source"`
}

func (q *Queries) UpsertAgentCVE(ctx context.Context, arg UpsertAgentCVEParams) (CVE, error) {
	row := q.db.QueryRow(ctx, upsertAgentCVE,
		arg.TenantID,
		arg.CveID,
		arg.Severity,
		arg.Description,
		arg.CvssV3Score,
		arg.Source,
	)
	var i CVE
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.CisaKevDueDate,
		&i.ExploitAvailable,
		&i.NvdLastModified,
		&i.AttackVector,
		&i.ExternalReferences,
		&i.CweID,
		&i.Source,
	)
	return i, err
}

const upsertCVE = `-- name: UpsertCVE :one
INSERT INTO cves (tenant_id, cve_id, severity, description, published_at,
    cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified,
    attack_vector, external_references, cwe_id, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (tenant_id, cve_id)
DO UPDATE SET
    severity = EXCLUDED.severity,
    description = EXCLUDED.description,
    published_at = EXCLUDED.published_at,
    cvss_v3_score = EXCLUDED.cvss_v3_score,
    cvss_v3_vector = EXCLUDED.cvss_v3_vector,
    cisa_kev_due_date = EXCLUDED.cisa_kev_due_date,
    exploit_available = EXCLUDED.exploit_available,
    nvd_last_modified = EXCLUDED.nvd_last_modified,
    attack_vector = EXCLUDED.attack_vector,
    external_references = EXCLUDED.external_references,
    cwe_id = EXCLUDED.cwe_id,
    source = EXCLUDED.source,
    updated_at = now()
RETURNING id, tenant_id, cve_id, severity, description, published_at, created_at, updated_at, cvss_v3_score, cvss_v3_vector, cisa_kev_due_date, exploit_available, nvd_last_modified, attack_vector, external_references, cwe_id, source
`

type UpsertCVEParams struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable   bool               `json:"exploit_available"`
	NvdLastModified    pgtype.Timestamptz `json:"nvd_last_modified"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	ExternalReferences []byte             `json:"external_references"`
	CweID              pgtype.Text        `json:"cwe_id"`
	Source             string             `json:"source"`
}

func (q *Queries) UpsertCVE(ctx context.Context, arg UpsertCVEParams) (CVE, error) {
	row := q.db.QueryRow(ctx, upsertCVE,
		arg.TenantID,
		arg.CveID,
		arg.Severity,
		arg.Description,
		arg.PublishedAt,
		arg.CvssV3Score,
		arg.CvssV3Vector,
		arg.CisaKevDueDate,
		arg.ExploitAvailable,
		arg.NvdLastModified,
		arg.AttackVector,
		arg.ExternalReferences,
		arg.CweID,
		arg.Source,
	)
	var i CVE
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.CisaKevDueDate,
		&i.ExploitAvailable,
		&i.NvdLastModified,
		&i.AttackVector,
		&i.ExternalReferences,
		&i.CweID,
		&i.Source,
	)
	return i, err
}

const upsertDiscoveredPatch = `-- name: UpsertDiscoveredPatch :one
INSERT INTO patches (tenant_id, name, version, severity, os_family, status,
    os_distribution, package_url, checksum_sha256, source_repo, description, package_name,
    released_at, installer_type, silent_args, hub_catalog_id)
VALUES ($1, $2, $3, $4, $5, 'available', $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (tenant_id, name, version, os_family)
DO UPDATE SET
    severity = EXCLUDED.severity,
    os_distribution = EXCLUDED.os_distribution,
    package_url = EXCLUDED.package_url,
    checksum_sha256 = EXCLUDED.checksum_sha256,
    source_repo = EXCLUDED.source_repo,
    description = EXCLUDED.description,
    package_name = EXCLUDED.package_name,
    released_at = EXCLUDED.released_at,
    installer_type = EXCLUDED.installer_type,
    silent_args = EXCLUDED.silent_args,
    hub_catalog_id = EXCLUDED.hub_catalog_id,
    deleted_at = NULL,
    updated_at = now()
RETURNING id, tenant_id, name, version, severity, os_family, status, created_at, updated_at, os_distribution, package_url, checksum_sha256, source_repo, description, released_at, package_name, installer_type, silent_args, deleted_at, hub_catalog_id
`

type UpsertDiscoveredPatchParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
	Severity       string             `json:"severity"`
	OsFamily       string             `json:"os_family"`
	OsDistribution pgtype.Text        `json:"os_distribution"`
	PackageUrl     pgtype.Text        `json:"package_url"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	SourceRepo     pgtype.Text        `json:"source_repo"`
	Description    pgtype.Text        `json:"description"`
	PackageName    string             `json:"package_name"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
	InstallerType  string             `json:"installer_type"`
	SilentArgs     string             `json:"silent_args"`
	HubCatalogID   pgtype.UUID        `json:"hub_catalog_id"`
}

func (q *Queries) UpsertDiscoveredPatch(ctx context.Context, arg UpsertDiscoveredPatchParams) (Patch, error) {
	row := q.db.QueryRow(ctx, upsertDiscoveredPatch,
		arg.TenantID,
		arg.Name,
		arg.Version,
		arg.Severity,
		arg.OsFamily,
		arg.OsDistribution,
		arg.PackageUrl,
		arg.ChecksumSha256,
		arg.SourceRepo,
		arg.Description,
		arg.PackageName,
		arg.ReleasedAt,
		arg.InstallerType,
		arg.SilentArgs,
		arg.HubCatalogID,
	)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Severity,
		&i.OsFamily,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsDistribution,
		&i.PackageUrl,
		&i.ChecksumSha256,
		&i.SourceRepo,
		&i.Description,
		&i.ReleasedAt,
		&i.PackageName,
		&i.InstallerType,
		&i.SilentArgs,
		&i.DeletedAt,
		&i.HubCatalogID,
	)
	return i, err
}
