// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkSoftDeletePolicies = `-- name: BulkSoftDeletePolicies :exec
UPDATE policies SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1 AND id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type BulkSoftDeletePoliciesParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	Ids      []pgtype.UUID `json:"ids"`
}

func (q *Queries) BulkSoftDeletePolicies(ctx context.Context, arg BulkSoftDeletePoliciesParams) error {
	_, err := q.db.Exec(ctx, bulkSoftDeletePolicies, arg.TenantID, arg.Ids)
	return err
}

const bulkUpdatePolicyEnabled = `-- name: BulkUpdatePolicyEnabled :exec
UPDATE policies SET enabled = $1, updated_at = now()
WHERE tenant_id = $2 AND id = ANY($3::uuid[]) AND deleted_at IS NULL
`

type BulkUpdatePolicyEnabledParams struct {
	Enabled  bool          `json:"enabled"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Ids      []pgtype.UUID `json:"ids"`
}

func (q *Queries) BulkUpdatePolicyEnabled(ctx context.Context, arg BulkUpdatePolicyEnabledParams) error {
	_, err := q.db.Exec(ctx, bulkUpdatePolicyEnabled, arg.Enabled, arg.TenantID, arg.Ids)
	return err
}

const countDeploymentsForPolicy = `-- name: CountDeploymentsForPolicy :one
SELECT count(*) FROM deployments
WHERE tenant_id = $1 AND policy_id = $2
`

type CountDeploymentsForPolicyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PolicyID pgtype.UUID `json:"policy_id"`
}

func (q *Queries) CountDeploymentsForPolicy(ctx context.Context, arg CountDeploymentsForPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeploymentsForPolicy, arg.TenantID, arg.PolicyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPolicies = `-- name: CountPolicies :one
SELECT count(*) FROM policies p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.name ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR p.enabled = ($3 = 'true'))
  AND ($4::text = '' OR p.mode = $4)
`

type CountPoliciesParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Search        string      `json:"search"`
	EnabledFilter string      `json:"enabled_filter"`
	ModeFilter    string      `json:"mode_filter"`
}

func (q *Queries) CountPolicies(ctx context.Context, arg CountPoliciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicies,
		arg.TenantID,
		arg.Search,
		arg.EnabledFilter,
		arg.ModeFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoliciesFiltered = `-- name: CountPoliciesFiltered :one
SELECT count(*) FROM policies p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.name ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR p.enabled = ($3 = 'true'))
  AND ($4::text = '' OR p.mode = $4)
  AND ($5::text = '' OR p.policy_type = $5)
`

type CountPoliciesFilteredParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Search        string      `json:"search"`
	EnabledFilter string      `json:"enabled_filter"`
	ModeFilter    string      `json:"mode_filter"`
	TypeFilter    string      `json:"type_filter"`
}

func (q *Queries) CountPoliciesFiltered(ctx context.Context, arg CountPoliciesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesFiltered,
		arg.TenantID,
		arg.Search,
		arg.EnabledFilter,
		arg.ModeFilter,
		arg.TypeFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (
    tenant_id, name, description, enabled, mode,
    selection_mode, min_severity, cve_ids, package_regex, exclude_packages,
    schedule_type, schedule_cron, mw_start, mw_end, deployment_strategy, policy_type, timezone, mw_enabled
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, tenant_id, name, description, enabled, created_at, updated_at, selection_mode, min_severity, cve_ids, package_regex, exclude_packages, schedule_type, schedule_cron, mw_start, mw_end, deployment_strategy, deleted_at, severity_filter, mode, last_evaluated_at, last_eval_pass, last_eval_endpoint_count, last_eval_compliant_count, deployment_config, policy_type, timezone, mw_enabled
`

type CreatePolicyParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Enabled            bool        `json:"enabled"`
	Mode               string      `json:"mode"`
	SelectionMode      string      `json:"selection_mode"`
	MinSeverity        pgtype.Text `json:"min_severity"`
	CveIds             []string    `json:"cve_ids"`
	PackageRegex       pgtype.Text `json:"package_regex"`
	ExcludePackages    []string    `json:"exclude_packages"`
	ScheduleType       string      `json:"schedule_type"`
	ScheduleCron       pgtype.Text `json:"schedule_cron"`
	MwStart            pgtype.Time `json:"mw_start"`
	MwEnd              pgtype.Time `json:"mw_end"`
	DeploymentStrategy string      `json:"deployment_strategy"`
	PolicyType         string      `json:"policy_type"`
	Timezone           string      `json:"timezone"`
	MwEnabled          bool        `json:"mw_enabled"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Mode,
		arg.SelectionMode,
		arg.MinSeverity,
		arg.CveIds,
		arg.PackageRegex,
		arg.ExcludePackages,
		arg.ScheduleType,
		arg.ScheduleCron,
		arg.MwStart,
		arg.MwEnd,
		arg.DeploymentStrategy,
		arg.PolicyType,
		arg.Timezone,
		arg.MwEnabled,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectionMode,
		&i.MinSeverity,
		&i.CveIds,
		&i.PackageRegex,
		&i.ExcludePackages,
		&i.ScheduleType,
		&i.ScheduleCron,
		&i.MwStart,
		&i.MwEnd,
		&i.DeploymentStrategy,
		&i.DeletedAt,
		&i.SeverityFilter,
		&i.Mode,
		&i.LastEvaluatedAt,
		&i.LastEvalPass,
		&i.LastEvalEndpointCount,
		&i.LastEvalCompliantCount,
		&i.DeploymentConfig,
		&i.PolicyType,
		&i.Timezone,
		&i.MwEnabled,
	)
	return i, err
}

const createPolicyEvaluation = `-- name: CreatePolicyEvaluation :one
INSERT INTO policy_evaluations (
    tenant_id, policy_id, matched_patches, in_scope_endpoints,
    compliant_count, non_compliant_count, duration_ms, pass
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
) RETURNING id, tenant_id, policy_id, evaluated_at, matched_patches, in_scope_endpoints, compliant_count, non_compliant_count, duration_ms, pass, created_at
`

type CreatePolicyEvaluationParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	PolicyID          pgtype.UUID `json:"policy_id"`
	MatchedPatches    int32       `json:"matched_patches"`
	InScopeEndpoints  int32       `json:"in_scope_endpoints"`
	CompliantCount    int32       `json:"compliant_count"`
	NonCompliantCount int32       `json:"non_compliant_count"`
	DurationMs        int32       `json:"duration_ms"`
	Pass              bool        `json:"pass"`
}

func (q *Queries) CreatePolicyEvaluation(ctx context.Context, arg CreatePolicyEvaluationParams) (PolicyEvaluation, error) {
	row := q.db.QueryRow(ctx, createPolicyEvaluation,
		arg.TenantID,
		arg.PolicyID,
		arg.MatchedPatches,
		arg.InScopeEndpoints,
		arg.CompliantCount,
		arg.NonCompliantCount,
		arg.DurationMs,
		arg.Pass,
	)
	var i PolicyEvaluation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyID,
		&i.EvaluatedAt,
		&i.MatchedPatches,
		&i.InScopeEndpoints,
		&i.CompliantCount,
		&i.NonCompliantCount,
		&i.DurationMs,
		&i.Pass,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, tenant_id, name, description, enabled, created_at, updated_at, selection_mode, min_severity, cve_ids, package_regex, exclude_packages, schedule_type, schedule_cron, mw_start, mw_end, deployment_strategy, deleted_at, severity_filter, mode, last_evaluated_at, last_eval_pass, last_eval_endpoint_count, last_eval_compliant_count, deployment_config, policy_type, timezone, mw_enabled FROM policies
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetPolicyByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPolicyByID(ctx context.Context, arg GetPolicyByIDParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, arg.ID, arg.TenantID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectionMode,
		&i.MinSeverity,
		&i.CveIds,
		&i.PackageRegex,
		&i.ExcludePackages,
		&i.ScheduleType,
		&i.ScheduleCron,
		&i.MwStart,
		&i.MwEnd,
		&i.DeploymentStrategy,
		&i.DeletedAt,
		&i.SeverityFilter,
		&i.Mode,
		&i.LastEvaluatedAt,
		&i.LastEvalPass,
		&i.LastEvalEndpointCount,
		&i.LastEvalCompliantCount,
		&i.DeploymentConfig,
		&i.PolicyType,
		&i.Timezone,
		&i.MwEnabled,
	)
	return i, err
}

const listAvailablePatchesForEndpoint = `-- name: ListAvailablePatchesForEndpoint :many
SELECT p.id, p.tenant_id, p.name, p.version, p.severity, p.os_family, p.status, p.created_at, p.updated_at, p.os_distribution, p.package_url, p.checksum_sha256, p.source_repo, p.description, p.released_at, p.package_name, p.installer_type, p.silent_args, p.deleted_at, p.hub_catalog_id FROM patches p
WHERE p.tenant_id = $1
  AND p.os_family = $2
  AND p.status = 'available'
ORDER BY p.name, p.version
LIMIT 1000
`

type ListAvailablePatchesForEndpointParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OsFamily string      `json:"os_family"`
}

func (q *Queries) ListAvailablePatchesForEndpoint(ctx context.Context, arg ListAvailablePatchesForEndpointParams) ([]Patch, error) {
	rows, err := q.db.Query(ctx, listAvailablePatchesForEndpoint, arg.TenantID, arg.OsFamily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patch{}
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Severity,
			&i.OsFamily,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsDistribution,
			&i.PackageUrl,
			&i.ChecksumSha256,
			&i.SourceRepo,
			&i.Description,
			&i.ReleasedAt,
			&i.PackageName,
			&i.InstallerType,
			&i.SilentArgs,
			&i.DeletedAt,
			&i.HubCatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEsForPatches = `-- name: ListCVEsForPatches :many
SELECT pc.patch_id, c.id, c.tenant_id, c.cve_id, c.severity, c.description, c.published_at, c.created_at, c.updated_at, c.cvss_v3_score, c.cvss_v3_vector, c.cisa_kev_due_date, c.exploit_available, c.nvd_last_modified, c.attack_vector, c.external_references, c.cwe_id, c.source FROM cves c
JOIN patch_cves pc ON c.id = pc.cve_id AND c.tenant_id = pc.tenant_id
WHERE pc.tenant_id = $1
  AND pc.patch_id = ANY($2::uuid[])
ORDER BY pc.patch_id, c.severity
LIMIT 5000
`

type ListCVEsForPatchesParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	PatchIds []pgtype.UUID `json:"patch_ids"`
}

type ListCVEsForPatchesRow struct {
	PatchID            pgtype.UUID        `json:"patch_id"`
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	ExploitAvailable   bool               `json:"exploit_available"`
	NvdLastModified    pgtype.Timestamptz `json:"nvd_last_modified"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	ExternalReferences []byte             `json:"external_references"`
	CweID              pgtype.Text        `json:"cwe_id"`
	Source             string             `json:"source"`
}

func (q *Queries) ListCVEsForPatches(ctx context.Context, arg ListCVEsForPatchesParams) ([]ListCVEsForPatchesRow, error) {
	rows, err := q.db.Query(ctx, listCVEsForPatches, arg.TenantID, arg.PatchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVEsForPatchesRow{}
	for rows.Next() {
		var i ListCVEsForPatchesRow
		if err := rows.Scan(
			&i.PatchID,
			&i.ID,
			&i.TenantID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.CisaKevDueDate,
			&i.ExploitAvailable,
			&i.NvdLastModified,
			&i.AttackVector,
			&i.ExternalReferences,
			&i.CweID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForPolicy = `-- name: ListDeploymentsForPolicy :many
SELECT id, tenant_id, policy_id, status, created_by, started_at, completed_at, created_at, updated_at, failure_threshold, total_targets, completed_count, success_count, failed_count, wave_config, max_concurrent, scheduled_at, name, patch_id, source_type, target_expression, rollback_config, reboot_config, workflow_template_id FROM deployments
WHERE tenant_id = $1 AND policy_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListDeploymentsForPolicyParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	PolicyID  pgtype.UUID `json:"policy_id"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) ListDeploymentsForPolicy(ctx context.Context, arg ListDeploymentsForPolicyParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForPolicy, arg.TenantID, arg.PolicyID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyID,
			&i.Status,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureThreshold,
			&i.TotalTargets,
			&i.CompletedCount,
			&i.SuccessCount,
			&i.FailedCount,
			&i.WaveConfig,
			&i.MaxConcurrent,
			&i.ScheduledAt,
			&i.Name,
			&i.PatchID,
			&i.SourceType,
			&i.TargetExpression,
			&i.RollbackConfig,
			&i.RebootConfig,
			&i.WorkflowTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT p.id, p.tenant_id, p.name, p.description, p.enabled, p.created_at, p.updated_at, p.selection_mode, p.min_severity, p.cve_ids, p.package_regex, p.exclude_packages, p.schedule_type, p.schedule_cron, p.mw_start, p.mw_end, p.deployment_strategy, p.deleted_at, p.severity_filter, p.mode, p.last_evaluated_at, p.last_eval_pass, p.last_eval_endpoint_count, p.last_eval_compliant_count, p.deployment_config, p.policy_type, p.timezone, p.mw_enabled
FROM policies p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.name ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR p.enabled = ($3 = 'true'))
  AND ($4::text = '' OR p.mode = $4)
  AND (
    $5::timestamptz IS NULL
    OR (p.created_at, p.id) > ($5, $6::uuid)
  )
ORDER BY p.created_at, p.id
LIMIT $7
`

type ListPoliciesParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Search          string             `json:"search"`
	EnabledFilter   string             `json:"enabled_filter"`
	ModeFilter      string             `json:"mode_filter"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies,
		arg.TenantID,
		arg.Search,
		arg.EnabledFilter,
		arg.ModeFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectionMode,
			&i.MinSeverity,
			&i.CveIds,
			&i.PackageRegex,
			&i.ExcludePackages,
			&i.ScheduleType,
			&i.ScheduleCron,
			&i.MwStart,
			&i.MwEnd,
			&i.DeploymentStrategy,
			&i.DeletedAt,
			&i.SeverityFilter,
			&i.Mode,
			&i.LastEvaluatedAt,
			&i.LastEvalPass,
			&i.LastEvalEndpointCount,
			&i.LastEvalCompliantCount,
			&i.DeploymentConfig,
			&i.PolicyType,
			&i.Timezone,
			&i.MwEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesWithStats = `-- name: ListPoliciesWithStats :many
SELECT p.id, p.tenant_id, p.name, p.description, p.enabled, p.created_at, p.updated_at, p.selection_mode, p.min_severity, p.cve_ids, p.package_regex, p.exclude_packages, p.schedule_type, p.schedule_cron, p.mw_start, p.mw_end, p.deployment_strategy, p.deleted_at, p.severity_filter, p.mode, p.last_evaluated_at, p.last_eval_pass, p.last_eval_endpoint_count, p.last_eval_compliant_count, p.deployment_config, p.policy_type, p.timezone, p.mw_enabled,
  0::int AS target_endpoints_count
FROM policies p
WHERE p.tenant_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.name ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR p.enabled = ($3 = 'true'))
  AND ($4::text = '' OR p.mode = $4)
  AND ($5::text = '' OR p.policy_type = $5)
  AND (
    $6::timestamptz IS NULL
    OR (p.created_at, p.id) > ($6, $7::uuid)
  )
ORDER BY p.created_at, p.id
LIMIT $8
`

type ListPoliciesWithStatsParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Search          string             `json:"search"`
	EnabledFilter   string             `json:"enabled_filter"`
	ModeFilter      string             `json:"mode_filter"`
	TypeFilter      string             `json:"type_filter"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListPoliciesWithStatsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	Enabled                bool               `json:"enabled"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	SelectionMode          string             `json:"selection_mode"`
	MinSeverity            pgtype.Text        `json:"min_severity"`
	CveIds                 []string           `json:"cve_ids"`
	PackageRegex           pgtype.Text        `json:"package_regex"`
	ExcludePackages        []string           `json:"exclude_packages"`
	ScheduleType           string             `json:"schedule_type"`
	ScheduleCron           pgtype.Text        `json:"schedule_cron"`
	MwStart                pgtype.Time        `json:"mw_start"`
	MwEnd                  pgtype.Time        `json:"mw_end"`
	DeploymentStrategy     string             `json:"deployment_strategy"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	SeverityFilter         []string           `json:"severity_filter"`
	Mode                   string             `json:"mode"`
	LastEvaluatedAt        pgtype.Timestamptz `json:"last_evaluated_at"`
	LastEvalPass           pgtype.Bool        `json:"last_eval_pass"`
	LastEvalEndpointCount  pgtype.Int4        `json:"last_eval_endpoint_count"`
	LastEvalCompliantCount pgtype.Int4        `json:"last_eval_compliant_count"`
	DeploymentConfig       []byte             `json:"deployment_config"`
	PolicyType             string             `json:"policy_type"`
	Timezone               string             `json:"timezone"`
	MwEnabled              bool               `json:"mw_enabled"`
	TargetEndpointsCount   int32              `json:"target_endpoints_count"`
}

// target_endpoints_count was previously derived from policy_groups; in the
// key=value world the authoritative answer requires evaluating the policy's
// target_selector against endpoint_tags, which is not expressible in a
// single sqlc query. The handler populates this from targeting.Resolver.
// We keep the column in the shape (set to 0 here) so the downstream Go
// type and response DTOs keep their field layout.
func (q *Queries) ListPoliciesWithStats(ctx context.Context, arg ListPoliciesWithStatsParams) ([]ListPoliciesWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesWithStats,
		arg.TenantID,
		arg.Search,
		arg.EnabledFilter,
		arg.ModeFilter,
		arg.TypeFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliciesWithStatsRow{}
	for rows.Next() {
		var i ListPoliciesWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectionMode,
			&i.MinSeverity,
			&i.CveIds,
			&i.PackageRegex,
			&i.ExcludePackages,
			&i.ScheduleType,
			&i.ScheduleCron,
			&i.MwStart,
			&i.MwEnd,
			&i.DeploymentStrategy,
			&i.DeletedAt,
			&i.SeverityFilter,
			&i.Mode,
			&i.LastEvaluatedAt,
			&i.LastEvalPass,
			&i.LastEvalEndpointCount,
			&i.LastEvalCompliantCount,
			&i.DeploymentConfig,
			&i.PolicyType,
			&i.Timezone,
			&i.MwEnabled,
			&i.TargetEndpointsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyEvaluations = `-- name: ListPolicyEvaluations :many
SELECT id, tenant_id, policy_id, evaluated_at, matched_patches, in_scope_endpoints, compliant_count, non_compliant_count, duration_ms, pass, created_at FROM policy_evaluations
WHERE tenant_id = $1 AND policy_id = $2
ORDER BY evaluated_at DESC
LIMIT $3
`

type ListPolicyEvaluationsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	PolicyID  pgtype.UUID `json:"policy_id"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) ListPolicyEvaluations(ctx context.Context, arg ListPolicyEvaluationsParams) ([]PolicyEvaluation, error) {
	rows, err := q.db.Query(ctx, listPolicyEvaluations, arg.TenantID, arg.PolicyID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyEvaluation{}
	for rows.Next() {
		var i PolicyEvaluation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyID,
			&i.EvaluatedAt,
			&i.MatchedPatches,
			&i.InScopeEndpoints,
			&i.CompliantCount,
			&i.NonCompliantCount,
			&i.DurationMs,
			&i.Pass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePolicy = `-- name: SoftDeletePolicy :one
UPDATE policies SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, name, description, enabled, created_at, updated_at, selection_mode, min_severity, cve_ids, package_regex, exclude_packages, schedule_type, schedule_cron, mw_start, mw_end, deployment_strategy, deleted_at, severity_filter, mode, last_evaluated_at, last_eval_pass, last_eval_endpoint_count, last_eval_compliant_count, deployment_config, policy_type, timezone, mw_enabled
`

type SoftDeletePolicyParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeletePolicy(ctx context.Context, arg SoftDeletePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, softDeletePolicy, arg.ID, arg.TenantID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectionMode,
		&i.MinSeverity,
		&i.CveIds,
		&i.PackageRegex,
		&i.ExcludePackages,
		&i.ScheduleType,
		&i.ScheduleCron,
		&i.MwStart,
		&i.MwEnd,
		&i.DeploymentStrategy,
		&i.DeletedAt,
		&i.SeverityFilter,
		&i.Mode,
		&i.LastEvaluatedAt,
		&i.LastEvalPass,
		&i.LastEvalEndpointCount,
		&i.LastEvalCompliantCount,
		&i.DeploymentConfig,
		&i.PolicyType,
		&i.Timezone,
		&i.MwEnabled,
	)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies SET
    name = $1,
    description = $2,
    enabled = $3,
    mode = $4,
    selection_mode = $5,
    min_severity = $6,
    cve_ids = $7,
    package_regex = $8,
    exclude_packages = $9,
    schedule_type = $10,
    schedule_cron = $11,
    mw_start = $12,
    mw_end = $13,
    deployment_strategy = $14,
    policy_type = $15,
    timezone = $16,
    mw_enabled = $17,
    updated_at = now()
WHERE id = $18 AND tenant_id = $19 AND deleted_at IS NULL
RETURNING id, tenant_id, name, description, enabled, created_at, updated_at, selection_mode, min_severity, cve_ids, package_regex, exclude_packages, schedule_type, schedule_cron, mw_start, mw_end, deployment_strategy, deleted_at, severity_filter, mode, last_evaluated_at, last_eval_pass, last_eval_endpoint_count, last_eval_compliant_count, deployment_config, policy_type, timezone, mw_enabled
`

type UpdatePolicyParams struct {
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Enabled            bool        `json:"enabled"`
	Mode               string      `json:"mode"`
	SelectionMode      string      `json:"selection_mode"`
	MinSeverity        pgtype.Text `json:"min_severity"`
	CveIds             []string    `json:"cve_ids"`
	PackageRegex       pgtype.Text `json:"package_regex"`
	ExcludePackages    []string    `json:"exclude_packages"`
	ScheduleType       string      `json:"schedule_type"`
	ScheduleCron       pgtype.Text `json:"schedule_cron"`
	MwStart            pgtype.Time `json:"mw_start"`
	MwEnd              pgtype.Time `json:"mw_end"`
	DeploymentStrategy string      `json:"deployment_strategy"`
	PolicyType         string      `json:"policy_type"`
	Timezone           string      `json:"timezone"`
	MwEnabled          bool        `json:"mw_enabled"`
	ID                 pgtype.UUID `json:"id"`
	TenantID           pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Mode,
		arg.SelectionMode,
		arg.MinSeverity,
		arg.CveIds,
		arg.PackageRegex,
		arg.ExcludePackages,
		arg.ScheduleType,
		arg.ScheduleCron,
		arg.MwStart,
		arg.MwEnd,
		arg.DeploymentStrategy,
		arg.PolicyType,
		arg.Timezone,
		arg.MwEnabled,
		arg.ID,
		arg.TenantID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectionMode,
		&i.MinSeverity,
		&i.CveIds,
		&i.PackageRegex,
		&i.ExcludePackages,
		&i.ScheduleType,
		&i.ScheduleCron,
		&i.MwStart,
		&i.MwEnd,
		&i.DeploymentStrategy,
		&i.DeletedAt,
		&i.SeverityFilter,
		&i.Mode,
		&i.LastEvaluatedAt,
		&i.LastEvalPass,
		&i.LastEvalEndpointCount,
		&i.LastEvalCompliantCount,
		&i.DeploymentConfig,
		&i.PolicyType,
		&i.Timezone,
		&i.MwEnabled,
	)
	return i, err
}

const updatePolicyEvalStats = `-- name: UpdatePolicyEvalStats :exec
UPDATE policies SET
    last_evaluated_at = $1,
    last_eval_pass = $2,
    last_eval_endpoint_count = $3,
    last_eval_compliant_count = $4,
    updated_at = now()
WHERE id = $5 AND tenant_id = $6
`

type UpdatePolicyEvalStatsParams struct {
	LastEvaluatedAt        pgtype.Timestamptz `json:"last_evaluated_at"`
	LastEvalPass           pgtype.Bool        `json:"last_eval_pass"`
	LastEvalEndpointCount  pgtype.Int4        `json:"last_eval_endpoint_count"`
	LastEvalCompliantCount pgtype.Int4        `json:"last_eval_compliant_count"`
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdatePolicyEvalStats(ctx context.Context, arg UpdatePolicyEvalStatsParams) error {
	_, err := q.db.Exec(ctx, updatePolicyEvalStats,
		arg.LastEvaluatedAt,
		arg.LastEvalPass,
		arg.LastEvalEndpointCount,
		arg.LastEvalCompliantCount,
		arg.ID,
		arg.TenantID,
	)
	return err
}
