// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportGenerations = `-- name: CountReportGenerations :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE status = 'completed') AS completed,
    count(*) FILTER (WHERE status = 'generating') AS generating,
    count(*) FILTER (WHERE status = 'failed') AS failed,
    count(*) FILTER (WHERE status = 'pending') AS pending
FROM report_generations
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR report_type = $3)
  AND ($4::text = '' OR format = $4)
`

type CountReportGenerationsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Status     string      `json:"status"`
	ReportType string      `json:"report_type"`
	Format     string      `json:"format"`
}

type CountReportGenerationsRow struct {
	Total      int64 `json:"total"`
	Completed  int64 `json:"completed"`
	Generating int64 `json:"generating"`
	Failed     int64 `json:"failed"`
	Pending    int64 `json:"pending"`
}

func (q *Queries) CountReportGenerations(ctx context.Context, arg CountReportGenerationsParams) (CountReportGenerationsRow, error) {
	row := q.db.QueryRow(ctx, countReportGenerations,
		arg.TenantID,
		arg.Status,
		arg.ReportType,
		arg.Format,
	)
	var i CountReportGenerationsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Generating,
		&i.Failed,
		&i.Pending,
	)
	return i, err
}

const countReportGenerationsToday = `-- name: CountReportGenerationsToday :one
SELECT count(*) FROM report_generations
WHERE tenant_id = $1
  AND created_at >= CURRENT_DATE
`

func (q *Queries) CountReportGenerationsToday(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReportGenerationsToday, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReportGeneration = `-- name: CreateReportGeneration :one
INSERT INTO report_generations (id, tenant_id, report_type, format, name, filters, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8)
RETURNING id, tenant_id, report_type, format, status, name, filters, file_path, file_size_bytes, checksum_sha256, row_count, error_message, created_by, created_at, completed_at, expires_at
`

type CreateReportGenerationParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ReportType string             `json:"report_type"`
	Format     string             `json:"format"`
	Name       string             `json:"name"`
	Filters    []byte             `json:"filters"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateReportGeneration(ctx context.Context, arg CreateReportGenerationParams) (ReportGeneration, error) {
	row := q.db.QueryRow(ctx, createReportGeneration,
		arg.ID,
		arg.TenantID,
		arg.ReportType,
		arg.Format,
		arg.Name,
		arg.Filters,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ReportGeneration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.Format,
		&i.Status,
		&i.Name,
		&i.Filters,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.RowCount,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredReports = `-- name: DeleteExpiredReports :many
DELETE FROM report_generations
WHERE tenant_id = $1
  AND expires_at < now()
  AND status = 'completed'
RETURNING file_path
`

func (q *Queries) DeleteExpiredReports(ctx context.Context, tenantID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, deleteExpiredReports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var file_path pgtype.Text
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReportGeneration = `-- name: DeleteReportGeneration :exec
DELETE FROM report_generations
WHERE id = $1 AND tenant_id = $2
`

type DeleteReportGenerationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteReportGeneration(ctx context.Context, arg DeleteReportGenerationParams) error {
	_, err := q.db.Exec(ctx, deleteReportGeneration, arg.ID, arg.TenantID)
	return err
}

const getReportGeneration = `-- name: GetReportGeneration :one
SELECT id, tenant_id, report_type, format, status, name, filters, file_path, file_size_bytes, checksum_sha256, row_count, error_message, created_by, created_at, completed_at, expires_at FROM report_generations
WHERE id = $1 AND tenant_id = $2
`

type GetReportGenerationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetReportGeneration(ctx context.Context, arg GetReportGenerationParams) (ReportGeneration, error) {
	row := q.db.QueryRow(ctx, getReportGeneration, arg.ID, arg.TenantID)
	var i ReportGeneration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReportType,
		&i.Format,
		&i.Status,
		&i.Name,
		&i.Filters,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.RowCount,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listReportGenerations = `-- name: ListReportGenerations :many
SELECT id, tenant_id, report_type, format, status, name, filters, file_path, file_size_bytes, checksum_sha256, row_count, error_message, created_by, created_at, completed_at, expires_at FROM report_generations
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR report_type = $3)
  AND ($4::text = '' OR format = $4)
  AND (
    $5::timestamptz IS NULL
    OR (created_at, id) < ($5, $6::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListReportGenerationsParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Status          string             `json:"status"`
	ReportType      string             `json:"report_type"`
	Format          string             `json:"format"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListReportGenerations(ctx context.Context, arg ListReportGenerationsParams) ([]ReportGeneration, error) {
	rows, err := q.db.Query(ctx, listReportGenerations,
		arg.TenantID,
		arg.Status,
		arg.ReportType,
		arg.Format,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportGeneration{}
	for rows.Next() {
		var i ReportGeneration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReportType,
			&i.Format,
			&i.Status,
			&i.Name,
			&i.Filters,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.ChecksumSha256,
			&i.RowCount,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE report_generations
SET status = $1,
    file_path = $2,
    file_size_bytes = $3,
    checksum_sha256 = $4,
    row_count = $5,
    error_message = $6,
    completed_at = $7
WHERE id = $8 AND tenant_id = $9
`

type UpdateReportStatusParams struct {
	Status         string             `json:"status"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileSizeBytes  pgtype.Int8        `json:"file_size_bytes"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	RowCount       pgtype.Int4        `json:"row_count"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportStatus,
		arg.Status,
		arg.FilePath,
		arg.FileSizeBytes,
		arg.ChecksumSha256,
		arg.RowCount,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.ID,
		arg.TenantID,
	)
	return err
}
