// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (tenant_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id, role_id) DO NOTHING
`

type AssignUserRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   string      `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}

const countRoleUsers = `-- name: CountRoleUsers :one
SELECT count(*) FROM user_roles
WHERE role_id = $1 AND tenant_id = $2
`

type CountRoleUsersParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CountRoleUsers(ctx context.Context, arg CountRoleUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleUsers, arg.RoleID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*) FROM roles
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
`

type CountRolesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
}

func (q *Queries) CountRoles(ctx context.Context, arg CountRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, name, description, parent_role_id, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, parent_role_id, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	ParentRoleID pgtype.UUID `json:"parent_role_id"`
	IsSystem     bool        `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.ParentRoleID,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permissions (tenant_id, role_id, resource, action, scope)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, role_id, resource, action, scope) DO NOTHING
`

type CreateRolePermissionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleID   pgtype.UUID `json:"role_id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
	Scope    string      `json:"scope"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createRolePermission,
		arg.TenantID,
		arg.RoleID,
		arg.Resource,
		arg.Action,
		arg.Scope,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND tenant_id = $2 AND is_system = false
`

type DeleteRoleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1 AND tenant_id = $2
`

type DeleteRolePermissionsParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRolePermissions(ctx context.Context, arg DeleteRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, arg.RoleID, arg.TenantID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, description, parent_role_id, is_system, created_at, updated_at FROM roles WHERE id = $1 AND tenant_id = $2
`

type GetRoleByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.ID, arg.TenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, tenant_id, name, description, parent_role_id, is_system, created_at, updated_at FROM roles WHERE name = $1 AND tenant_id = $2
`

type GetRoleByNameParams struct {
	Name     string      `json:"name"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.Name, arg.TenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
WITH RECURSIVE role_chain AS (
    -- Base: roles directly assigned to the user
    SELECT r.id, r.parent_role_id
    FROM roles r
    JOIN user_roles ur ON ur.role_id = r.id AND ur.tenant_id = r.tenant_id
    WHERE ur.user_id = $1 AND ur.tenant_id = $2

    UNION

    -- Recursive: walk parent chain
    SELECT r.id, r.parent_role_id
    FROM roles r
    JOIN role_chain rc ON rc.parent_role_id = r.id
    WHERE r.tenant_id = $2
) CYCLE id SET is_cycle USING path
SELECT DISTINCT rp.resource, rp.action, rp.scope
FROM role_permissions rp
JOIN role_chain rc ON rc.id = rp.role_id
WHERE rp.tenant_id = $2
LIMIT 1000
`

type GetUserPermissionsParams struct {
	UserID   string      `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetUserPermissionsRow struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
	Scope    string `json:"scope"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.Resource, &i.Action, &i.Scope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT id, tenant_id, role_id, resource, action, scope FROM role_permissions WHERE role_id = $1 AND tenant_id = $2
LIMIT 1000
`

type ListRolePermissionsParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, arg.RoleID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleID,
			&i.Resource,
			&i.Action,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleUsers = `-- name: ListRoleUsers :many
SELECT ur.user_id, ur.assigned_at
FROM user_roles ur
WHERE ur.role_id = $1 AND ur.tenant_id = $2
ORDER BY ur.assigned_at
LIMIT 1000
`

type ListRoleUsersParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListRoleUsersRow struct {
	UserID     string             `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListRoleUsers(ctx context.Context, arg ListRoleUsersParams) ([]ListRoleUsersRow, error) {
	rows, err := q.db.Query(ctx, listRoleUsers, arg.RoleID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleUsersRow{}
	for rows.Next() {
		var i ListRoleUsersRow
		if err := rows.Scan(&i.UserID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, description, parent_role_id, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 ORDER BY name
LIMIT 100
`

func (q *Queries) ListRoles(ctx context.Context, tenantID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithCount = `-- name: ListRolesWithCount :many
SELECT r.id, r.tenant_id, r.name, r.description, r.parent_role_id, r.is_system, r.created_at, r.updated_at,
       (SELECT count(*) FROM role_permissions rp WHERE rp.role_id = r.id AND rp.tenant_id = r.tenant_id) AS permission_count,
       (SELECT count(*) FROM user_roles ur WHERE ur.role_id = r.id AND ur.tenant_id = r.tenant_id) AS user_count
FROM roles r
WHERE r.tenant_id = $1
  AND ($2::text = '' OR r.name ILIKE '%' || $2 || '%')
  AND (
    ($3::timestamptz IS NULL AND $4::uuid IS NULL)
    OR (r.created_at, r.id) < ($3, $4)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $5
`

type ListRolesWithCountParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Column2  string             `json:"column_2"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Column4  pgtype.UUID        `json:"column_4"`
	Limit    int32              `json:"limit"`
}

type ListRolesWithCountRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	ParentRoleID    pgtype.UUID        `json:"parent_role_id"`
	IsSystem        bool               `json:"is_system"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PermissionCount int64              `json:"permission_count"`
	UserCount       int64              `json:"user_count"`
}

func (q *Queries) ListRolesWithCount(ctx context.Context, arg ListRolesWithCountParams) ([]ListRolesWithCountRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithCount,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesWithCountRow{}
	for rows.Next() {
		var i ListRolesWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PermissionCount,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.description, r.parent_role_id, r.is_system, r.created_at, r.updated_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id AND ur.tenant_id = r.tenant_id
WHERE ur.user_id = $1 AND ur.tenant_id = $2
ORDER BY r.name
LIMIT 100
`

type ListUserRolesParams struct {
	UserID   string      `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListUserRoles(ctx context.Context, arg ListUserRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRole = `-- name: RevokeUserRole :execrows
DELETE FROM user_roles WHERE tenant_id = $1 AND user_id = $2 AND role_id = $3
`

type RevokeUserRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   string      `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRole, arg.TenantID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, parent_role_id = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $5 AND is_system = false
RETURNING id, tenant_id, name, description, parent_role_id, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	ParentRoleID pgtype.UUID `json:"parent_role_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentRoleID,
		arg.TenantID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
