// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTagToEndpoint = `-- name: AssignTagToEndpoint :exec
INSERT INTO endpoint_tags (endpoint_id, tag_id, tenant_id, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint_id, tag_id) DO NOTHING
`

type AssignTagToEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TagID      pgtype.UUID `json:"tag_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Source     string      `json:"source"`
}

func (q *Queries) AssignTagToEndpoint(ctx context.Context, arg AssignTagToEndpointParams) error {
	_, err := q.db.Exec(ctx, assignTagToEndpoint,
		arg.EndpointID,
		arg.TagID,
		arg.TenantID,
		arg.Source,
	)
	return err
}

const bulkAssignTag = `-- name: BulkAssignTag :exec
INSERT INTO endpoint_tags (endpoint_id, tag_id, tenant_id, source)
SELECT unnest($1::UUID[]), $2, $3, $4
ON CONFLICT (endpoint_id, tag_id) DO NOTHING
`

type BulkAssignTagParams struct {
	EndpointIds []pgtype.UUID `json:"endpoint_ids"`
	TagID       pgtype.UUID   `json:"tag_id"`
	TenantID    pgtype.UUID   `json:"tenant_id"`
	Source      string        `json:"source"`
}

func (q *Queries) BulkAssignTag(ctx context.Context, arg BulkAssignTagParams) error {
	_, err := q.db.Exec(ctx, bulkAssignTag,
		arg.EndpointIds,
		arg.TagID,
		arg.TenantID,
		arg.Source,
	)
	return err
}

const countEndpointsByTag = `-- name: CountEndpointsByTag :one
SELECT COUNT(*) FROM endpoint_tags et
WHERE et.tag_id = $1 AND et.tenant_id = $2
`

type CountEndpointsByTagParams struct {
	TagID    pgtype.UUID `json:"tag_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CountEndpointsByTag(ctx context.Context, arg CountEndpointsByTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsByTag, arg.TagID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (tenant_id, key, value, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, description, created_at, updated_at, key, value
`

type CreateTagParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.Description,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND tenant_id = $2
`

type DeleteTagParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.TenantID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, tenant_id, description, created_at, updated_at, key, value FROM tags WHERE id = $1 AND tenant_id = $2
`

type GetTagByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.TenantID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const getTagByKeyValue = `-- name: GetTagByKeyValue :one
SELECT id, tenant_id, description, created_at, updated_at, key, value FROM tags
WHERE tenant_id = $1
  AND lower(key) = lower($2)
  AND lower(value) = lower($3)
`

type GetTagByKeyValueParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
	Value    string      `json:"value"`
}

func (q *Queries) GetTagByKeyValue(ctx context.Context, arg GetTagByKeyValueParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByKeyValue, arg.TenantID, arg.Key, arg.Value)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const listDistinctTagKeys = `-- name: ListDistinctTagKeys :many
SELECT lower(key) AS key, count(*)::bigint AS value_count
FROM tags
WHERE tenant_id = $1
GROUP BY lower(key)
ORDER BY lower(key)
`

type ListDistinctTagKeysRow struct {
	Key        string `json:"key"`
	ValueCount int64  `json:"value_count"`
}

func (q *Queries) ListDistinctTagKeys(ctx context.Context, tenantID pgtype.UUID) ([]ListDistinctTagKeysRow, error) {
	rows, err := q.db.Query(ctx, listDistinctTagKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctTagKeysRow{}
	for rows.Next() {
		var i ListDistinctTagKeysRow
		if err := rows.Scan(&i.Key, &i.ValueCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsByTag = `-- name: ListEndpointsByTag :many
SELECT et.endpoint_id FROM endpoint_tags et
WHERE et.tag_id = $1 AND et.tenant_id = $2
LIMIT 5000
`

type ListEndpointsByTagParams struct {
	TagID    pgtype.UUID `json:"tag_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListEndpointsByTag(ctx context.Context, arg ListEndpointsByTagParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEndpointsByTag, arg.TagID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var endpoint_id pgtype.UUID
		if err := rows.Scan(&endpoint_id); err != nil {
			return nil, err
		}
		items = append(items, endpoint_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.tenant_id, t.description, t.created_at, t.updated_at, t.key, t.value,
    (SELECT count(*) FROM endpoint_tags et WHERE et.tag_id = t.id AND et.tenant_id = t.tenant_id)::bigint AS endpoint_count
FROM tags t
WHERE t.tenant_id = $1
  AND ($2::text = '' OR lower(t.key) = lower($2))
ORDER BY t.key, t.value
LIMIT 1000
`

type ListTagsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	KeyFilter string      `json:"key_filter"`
}

type ListTagsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Key           string             `json:"key"`
	Value         string             `json:"value"`
	EndpointCount int64              `json:"endpoint_count"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.TenantID, arg.KeyFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Key,
			&i.Value,
			&i.EndpointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForEndpoint = `-- name: ListTagsForEndpoint :many
SELECT t.id, t.tenant_id, t.description, t.created_at, t.updated_at, t.key, t.value FROM tags t
JOIN endpoint_tags et ON et.tag_id = t.id
WHERE et.endpoint_id = $1 AND et.tenant_id = $2
ORDER BY t.key, t.value
LIMIT 100
`

type ListTagsForEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListTagsForEndpoint(ctx context.Context, arg ListTagsForEndpointParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForEndpoint, arg.EndpointID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEndpointTagsByKey = `-- name: RemoveEndpointTagsByKey :exec
DELETE FROM endpoint_tags et
USING tags t
WHERE et.tag_id = t.id
  AND et.tenant_id = $1
  AND et.endpoint_id = ANY($2::UUID[])
  AND lower(t.key) = lower($3)
`

type RemoveEndpointTagsByKeyParams struct {
	TenantID    pgtype.UUID   `json:"tenant_id"`
	EndpointIds []pgtype.UUID `json:"endpoint_ids"`
	Key         string        `json:"key"`
}

// Used by AssignTag for keys flagged as exclusive in tag_keys: strips any
// existing values for `key` from each endpoint before assigning the new
// tag, so an endpoint never carries two values for a single-valued key.
func (q *Queries) RemoveEndpointTagsByKey(ctx context.Context, arg RemoveEndpointTagsByKeyParams) error {
	_, err := q.db.Exec(ctx, removeEndpointTagsByKey, arg.TenantID, arg.EndpointIds, arg.Key)
	return err
}

const removeTagFromEndpoint = `-- name: RemoveTagFromEndpoint :exec
DELETE FROM endpoint_tags
WHERE endpoint_id = $1 AND tag_id = $2 AND tenant_id = $3
`

type RemoveTagFromEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	TagID      pgtype.UUID `json:"tag_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RemoveTagFromEndpoint(ctx context.Context, arg RemoveTagFromEndpointParams) error {
	_, err := q.db.Exec(ctx, removeTagFromEndpoint, arg.EndpointID, arg.TagID, arg.TenantID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
    description = $1,
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, description, created_at, updated_at, key, value
`

type UpdateTagParams struct {
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Description, arg.ID, arg.TenantID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}
