// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGeneralSettings = `-- name: GetGeneralSettings :one
SELECT org_name, timezone, date_format, scan_interval_hours
FROM tenant_settings
WHERE tenant_id = $1
`

type GetGeneralSettingsRow struct {
	OrgName           string `json:"org_name"`
	Timezone          string `json:"timezone"`
	DateFormat        string `json:"date_format"`
	ScanIntervalHours int32  `json:"scan_interval_hours"`
}

func (q *Queries) GetGeneralSettings(ctx context.Context, tenantID pgtype.UUID) (GetGeneralSettingsRow, error) {
	row := q.db.QueryRow(ctx, getGeneralSettings, tenantID)
	var i GetGeneralSettingsRow
	err := row.Scan(
		&i.OrgName,
		&i.Timezone,
		&i.DateFormat,
		&i.ScanIntervalHours,
	)
	return i, err
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, audit_retention_days, created_at, updated_at, org_name, timezone, date_format, scan_interval_hours FROM tenant_settings
WHERE tenant_id = $1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID pgtype.UUID) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.AuditRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgName,
		&i.Timezone,
		&i.DateFormat,
		&i.ScanIntervalHours,
	)
	return i, err
}

const listTenantRetentionPolicies = `-- name: ListTenantRetentionPolicies :many
SELECT tenant_id, audit_retention_days
FROM tenant_settings
LIMIT 100
`

type ListTenantRetentionPoliciesRow struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	AuditRetentionDays int32       `json:"audit_retention_days"`
}

func (q *Queries) ListTenantRetentionPolicies(ctx context.Context) ([]ListTenantRetentionPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listTenantRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantRetentionPoliciesRow{}
	for rows.Next() {
		var i ListTenantRetentionPoliciesRow
		if err := rows.Scan(&i.TenantID, &i.AuditRetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGeneralSettings = `-- name: UpdateGeneralSettings :one
INSERT INTO tenant_settings (tenant_id, org_name, timezone, date_format, scan_interval_hours)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id) DO UPDATE SET
  org_name = $2,
  timezone = $3,
  date_format = $4,
  scan_interval_hours = $5,
  updated_at = now()
RETURNING org_name, timezone, date_format, scan_interval_hours
`

type UpdateGeneralSettingsParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	OrgName           string      `json:"org_name"`
	Timezone          string      `json:"timezone"`
	DateFormat        string      `json:"date_format"`
	ScanIntervalHours int32       `json:"scan_interval_hours"`
}

type UpdateGeneralSettingsRow struct {
	OrgName           string `json:"org_name"`
	Timezone          string `json:"timezone"`
	DateFormat        string `json:"date_format"`
	ScanIntervalHours int32  `json:"scan_interval_hours"`
}

func (q *Queries) UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) (UpdateGeneralSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateGeneralSettings,
		arg.TenantID,
		arg.OrgName,
		arg.Timezone,
		arg.DateFormat,
		arg.ScanIntervalHours,
	)
	var i UpdateGeneralSettingsRow
	err := row.Scan(
		&i.OrgName,
		&i.Timezone,
		&i.DateFormat,
		&i.ScanIntervalHours,
	)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (tenant_id, audit_retention_days)
VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE SET
  audit_retention_days = $2,
  updated_at = now()
RETURNING tenant_id, audit_retention_days, created_at, updated_at, org_name, timezone, date_format, scan_interval_hours
`

type UpsertTenantSettingsParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	AuditRetentionDays int32       `json:"audit_retention_days"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings, arg.TenantID, arg.AuditRetentionDays)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.AuditRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgName,
		&i.Timezone,
		&i.DateFormat,
		&i.ScanIntervalHours,
	)
	return i, err
}
