// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_executions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkflowExecutions = `-- name: CountWorkflowExecutions :one
SELECT count(*) FROM workflow_executions
WHERE workflow_id = $1 AND tenant_id = $2
  AND ($3::text = '' OR status = $3)
`

type CountWorkflowExecutionsParams struct {
	WorkflowID   pgtype.UUID `json:"workflow_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	StatusFilter string      `json:"status_filter"`
}

func (q *Queries) CountWorkflowExecutions(ctx context.Context, arg CountWorkflowExecutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowExecutions, arg.WorkflowID, arg.TenantID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (tenant_id, execution_id, node_id, approver_roles, escalation_role, timeout_action, timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, execution_id, node_id, approver_roles, escalation_role, timeout_action, timeout_at, status, acted_by, acted_at, comment, created_at
`

type CreateApprovalRequestParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ExecutionID    pgtype.UUID        `json:"execution_id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	ApproverRoles  []string           `json:"approver_roles"`
	EscalationRole string             `json:"escalation_role"`
	TimeoutAction  string             `json:"timeout_action"`
	TimeoutAt      pgtype.Timestamptz `json:"timeout_at"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest,
		arg.TenantID,
		arg.ExecutionID,
		arg.NodeID,
		arg.ApproverRoles,
		arg.EscalationRole,
		arg.TimeoutAction,
		arg.TimeoutAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.ApproverRoles,
		&i.EscalationRole,
		&i.TimeoutAction,
		&i.TimeoutAt,
		&i.Status,
		&i.ActedBy,
		&i.ActedAt,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createNodeExecution = `-- name: CreateNodeExecution :one
INSERT INTO workflow_node_executions (tenant_id, execution_id, node_id, node_type, status, started_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, execution_id, node_id, node_type, status, output, error_message, started_at, completed_at
`

type CreateNodeExecutionParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExecutionID pgtype.UUID        `json:"execution_id"`
	NodeID      pgtype.UUID        `json:"node_id"`
	NodeType    string             `json:"node_type"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateNodeExecution(ctx context.Context, arg CreateNodeExecutionParams) (WorkflowNodeExecution, error) {
	row := q.db.QueryRow(ctx, createNodeExecution,
		arg.TenantID,
		arg.ExecutionID,
		arg.NodeID,
		arg.NodeType,
		arg.Status,
		arg.StartedAt,
	)
	var i WorkflowNodeExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.NodeType,
		&i.Status,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :one
INSERT INTO workflow_executions (tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, context)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, current_node_id, context, error_message, started_at, completed_at, created_at
`

type CreateWorkflowExecutionParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	WorkflowID        pgtype.UUID `json:"workflow_id"`
	VersionID         pgtype.UUID `json:"version_id"`
	Status            string      `json:"status"`
	TriggeredBy       string      `json:"triggered_by"`
	TriggeredByUserID pgtype.UUID `json:"triggered_by_user_id"`
	Context           []byte      `json:"context"`
}

func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecution,
		arg.TenantID,
		arg.WorkflowID,
		arg.VersionID,
		arg.Status,
		arg.TriggeredBy,
		arg.TriggeredByUserID,
		arg.Context,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.VersionID,
		&i.Status,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.CurrentNodeID,
		&i.Context,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, tenant_id, execution_id, node_id, approver_roles, escalation_role, timeout_action, timeout_at, status, acted_by, acted_at, comment, created_at FROM approval_requests
WHERE execution_id = $1 AND node_id = $2 AND tenant_id = $3
`

type GetApprovalRequestParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      pgtype.UUID `json:"node_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetApprovalRequest(ctx context.Context, arg GetApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, arg.ExecutionID, arg.NodeID, arg.TenantID)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.ApproverRoles,
		&i.EscalationRole,
		&i.TimeoutAction,
		&i.TimeoutAt,
		&i.Status,
		&i.ActedBy,
		&i.ActedAt,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeExecutionByNodeID = `-- name: GetNodeExecutionByNodeID :one
SELECT id, tenant_id, execution_id, node_id, node_type, status, output, error_message, started_at, completed_at FROM workflow_node_executions
WHERE execution_id = $1 AND node_id = $2 AND tenant_id = $3
`

type GetNodeExecutionByNodeIDParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      pgtype.UUID `json:"node_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNodeExecutionByNodeID(ctx context.Context, arg GetNodeExecutionByNodeIDParams) (WorkflowNodeExecution, error) {
	row := q.db.QueryRow(ctx, getNodeExecutionByNodeID, arg.ExecutionID, arg.NodeID, arg.TenantID)
	var i WorkflowNodeExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.NodeType,
		&i.Status,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingApprovalByExecution = `-- name: GetPendingApprovalByExecution :one
SELECT id, tenant_id, execution_id, node_id, approver_roles, escalation_role, timeout_action, timeout_at, status, acted_by, acted_at, comment, created_at FROM approval_requests
WHERE execution_id = $1 AND tenant_id = $2 AND status = 'pending'
`

type GetPendingApprovalByExecutionParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPendingApprovalByExecution(ctx context.Context, arg GetPendingApprovalByExecutionParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getPendingApprovalByExecution, arg.ExecutionID, arg.TenantID)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.ApproverRoles,
		&i.EscalationRole,
		&i.TimeoutAction,
		&i.TimeoutAt,
		&i.Status,
		&i.ActedBy,
		&i.ActedAt,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getRunningExecutionsForWorkflow = `-- name: GetRunningExecutionsForWorkflow :many
SELECT id, tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, current_node_id, context, error_message, started_at, completed_at, created_at FROM workflow_executions
WHERE workflow_id = $1 AND tenant_id = $2 AND status IN ('running', 'paused')
ORDER BY created_at DESC
`

type GetRunningExecutionsForWorkflowParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRunningExecutionsForWorkflow(ctx context.Context, arg GetRunningExecutionsForWorkflowParams) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, getRunningExecutionsForWorkflow, arg.WorkflowID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowExecution{}
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.VersionID,
			&i.Status,
			&i.TriggeredBy,
			&i.TriggeredByUserID,
			&i.CurrentNodeID,
			&i.Context,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowExecution = `-- name: GetWorkflowExecution :one
SELECT id, tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, current_node_id, context, error_message, started_at, completed_at, created_at FROM workflow_executions
WHERE id = $1 AND tenant_id = $2
`

type GetWorkflowExecutionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetWorkflowExecution(ctx context.Context, arg GetWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflowExecution, arg.ID, arg.TenantID)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.VersionID,
		&i.Status,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.CurrentNodeID,
		&i.Context,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNodeExecutions = `-- name: ListNodeExecutions :many
SELECT id, tenant_id, execution_id, node_id, node_type, status, output, error_message, started_at, completed_at FROM workflow_node_executions
WHERE execution_id = $1 AND tenant_id = $2
ORDER BY started_at ASC NULLS LAST
LIMIT 1000
`

type ListNodeExecutionsParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListNodeExecutions(ctx context.Context, arg ListNodeExecutionsParams) ([]WorkflowNodeExecution, error) {
	rows, err := q.db.Query(ctx, listNodeExecutions, arg.ExecutionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNodeExecution{}
	for rows.Next() {
		var i WorkflowNodeExecution
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExecutionID,
			&i.NodeID,
			&i.NodeType,
			&i.Status,
			&i.Output,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutions = `-- name: ListWorkflowExecutions :many
SELECT id, tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, current_node_id, context, error_message, started_at, completed_at, created_at FROM workflow_executions
WHERE workflow_id = $1 AND tenant_id = $2
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListWorkflowExecutionsParams struct {
	WorkflowID   pgtype.UUID `json:"workflow_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	StatusFilter string      `json:"status_filter"`
	PageLimit    int32       `json:"page_limit"`
}

func (q *Queries) ListWorkflowExecutions(ctx context.Context, arg ListWorkflowExecutionsParams) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutions,
		arg.WorkflowID,
		arg.TenantID,
		arg.StatusFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowExecution{}
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.VersionID,
			&i.Status,
			&i.TriggeredBy,
			&i.TriggeredByUserID,
			&i.CurrentNodeID,
			&i.Context,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalRequest = `-- name: UpdateApprovalRequest :one
UPDATE approval_requests
SET status = $3, acted_by = $4, acted_at = $5, comment = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, execution_id, node_id, approver_roles, escalation_role, timeout_action, timeout_at, status, acted_by, acted_at, comment, created_at
`

type UpdateApprovalRequestParams struct {
	ID       pgtype.UUID        `json:"id"`
	TenantID pgtype.UUID        `json:"tenant_id"`
	Status   string             `json:"status"`
	ActedBy  pgtype.UUID        `json:"acted_by"`
	ActedAt  pgtype.Timestamptz `json:"acted_at"`
	Comment  string             `json:"comment"`
}

func (q *Queries) UpdateApprovalRequest(ctx context.Context, arg UpdateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateApprovalRequest,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ActedBy,
		arg.ActedAt,
		arg.Comment,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.ApproverRoles,
		&i.EscalationRole,
		&i.TimeoutAction,
		&i.TimeoutAt,
		&i.Status,
		&i.ActedBy,
		&i.ActedAt,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const updateNodeExecution = `-- name: UpdateNodeExecution :one
UPDATE workflow_node_executions
SET status = $3, output = $4, error_message = $5, completed_at = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, execution_id, node_id, node_type, status, output, error_message, started_at, completed_at
`

type UpdateNodeExecutionParams struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Status       string             `json:"status"`
	Output       []byte             `json:"output"`
	ErrorMessage string             `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateNodeExecution(ctx context.Context, arg UpdateNodeExecutionParams) (WorkflowNodeExecution, error) {
	row := q.db.QueryRow(ctx, updateNodeExecution,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Output,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i WorkflowNodeExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.NodeID,
		&i.NodeType,
		&i.Status,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateWorkflowExecutionStatus = `-- name: UpdateWorkflowExecutionStatus :one
UPDATE workflow_executions
SET status = $3, current_node_id = $4, context = $5, error_message = $6,
    started_at = COALESCE(started_at, $7),
    completed_at = $8
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, workflow_id, version_id, status, triggered_by, triggered_by_user_id, current_node_id, context, error_message, started_at, completed_at, created_at
`

type UpdateWorkflowExecutionStatusParams struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Status        string             `json:"status"`
	CurrentNodeID pgtype.UUID        `json:"current_node_id"`
	Context       []byte             `json:"context"`
	ErrorMessage  string             `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowExecutionStatus(ctx context.Context, arg UpdateWorkflowExecutionStatusParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecutionStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.CurrentNodeID,
		arg.Context,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.VersionID,
		&i.Status,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.CurrentNodeID,
		&i.Context,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
