#!/usr/bin/env bash
# Generates a .env file with per-user port offsets for shared dev server.
# Each developer gets isolated Docker containers, databases, and ports.
#
# Usage:
#   ./scripts/dev-env.sh          # auto-detect from $USER
#   ./scripts/dev-env.sh sandy    # generate for a specific user
#   ./scripts/dev-env.sh --print  # print port table without writing

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

# ── Port offset per developer ──────────────────────────────────
get_offset() {
    case "$1" in
        heramb)  echo 0   ;;
        sandy)   echo 100 ;;
        danish)  echo 200 ;;
        rishab)  echo 300 ;;
        patchiq) echo 400 ;;
        *)
            echo "Unknown user: $1" >&2
            echo "Known users: heramb, sandy, danish, rishab" >&2
            echo "Add yourself to scripts/dev-env.sh get_offset()" >&2
            exit 1
            ;;
    esac
}

# ── Resolve user ───────────────────────────────────────────────
DEV_USER="${1:-$USER}"

if [[ "$DEV_USER" == "--print" ]]; then
    printf "\n%-10s  %-8s  %-8s  %-8s  %-8s\n" "Service" "heramb" "sandy" "danish" "rishab"
    printf "%-10s  %-8s  %-8s  %-8s  %-8s\n" "─────────" "──────" "──────" "──────" "──────"
    for svc in "Postgres:5432" "Valkey:6379" "Zitadel:8085" "MinIO:9000" "MinIO UI:9001" \
               "Grafana:3000" "OTLP gRPC:4317" "OTLP HTTP:4318" \
               "Server:8080" "gRPC:50051" "Hub:8082" "Agent:8090" \
               "Web UI:3001" "Hub UI:3002" "Agent UI:3003"; do
        name="${svc%%:*}"
        base="${svc##*:}"
        printf "%-10s  %-8s  %-8s  %-8s  %-8s\n" \
            "$name" "$base" "$((base+100))" "$((base+200))" "$((base+300))"
    done
    echo ""
    exit 0
fi

OFFSET=$(get_offset "$DEV_USER")

# ── Compute ports ──────────────────────────────────────────────
PG_PORT=$((5432 + OFFSET))
VALKEY_PORT=$((6379 + OFFSET))
ZITADEL_PORT=$((8085 + OFFSET))
MINIO_API_PORT=$((9000 + OFFSET))
MINIO_CONSOLE_PORT=$((9001 + OFFSET))
GRAFANA_PORT=$((3000 + OFFSET))
OTLP_GRPC_PORT=$((4317 + OFFSET))
OTLP_HTTP_PORT=$((4318 + OFFSET))

SERVER_HTTP_PORT=$((8080 + OFFSET))
SERVER_GRPC_PORT=$((50051 + OFFSET))
HUB_HTTP_PORT=$((8082 + OFFSET))
AGENT_HTTP_PORT=$((8090 + OFFSET))

WEB_PORT=$((3001 + OFFSET))
WEB_HUB_PORT=$((3002 + OFFSET))
WEB_AGENT_PORT=$((3003 + OFFSET))

DB_NAME_SERVER="patchiq_dev_${DEV_USER}"
DB_NAME_HUB="patchiq_hub_dev_${DEV_USER}"

# ── Write .env ─────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/dev-env.sh — do not edit manually.
# User: ${DEV_USER} | Offset: +${OFFSET}
# Regenerate: ./scripts/dev-env.sh ${DEV_USER}

# ── Docker Compose isolation ────────────────────────────────
COMPOSE_PROJECT_NAME=patchiq-${DEV_USER}

# ── Infrastructure ports (docker-compose.dev.yml) ───────────
PG_PORT=${PG_PORT}
VALKEY_PORT=${VALKEY_PORT}
ZITADEL_PORT=${ZITADEL_PORT}
MINIO_API_PORT=${MINIO_API_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
GRAFANA_PORT=${GRAFANA_PORT}
OTLP_GRPC_PORT=${OTLP_GRPC_PORT}
OTLP_HTTP_PORT=${OTLP_HTTP_PORT}

# ── Per-user database names ─────────────────────────────────
DB_NAME_SERVER=${DB_NAME_SERVER}
DB_NAME_HUB=${DB_NAME_HUB}

# ── Server (PATCHIQ_ prefix for config overlay) ────────────
PATCHIQ_SERVER_HTTP_PORT=${SERVER_HTTP_PORT}
PATCHIQ_SERVER_GRPC_PORT=${SERVER_GRPC_PORT}
PATCHIQ_DATABASE_URL=postgres://patchiq:patchiq_dev@localhost:${PG_PORT}/${DB_NAME_SERVER}?sslmode=disable
PATCHIQ_WATERMILL_POSTGRES_URL=postgres://patchiq:patchiq_dev@localhost:${PG_PORT}/${DB_NAME_SERVER}?sslmode=disable
PATCHIQ_VALKEY_URL=redis://localhost:${VALKEY_PORT}
PATCHIQ_OTEL_ENDPOINT=localhost:${OTLP_GRPC_PORT}
PATCHIQ_IAM_ZITADEL_DOMAIN=localhost:${ZITADEL_PORT}
PATCHIQ_IAM_ZITADEL_REDIRECT_URI=http://localhost:${SERVER_HTTP_PORT}/api/v1/auth/callback
PATCHIQ_IAM_SESSION_POST_LOGIN_URL=http://localhost:${WEB_PORT}/
PATCHIQ_SERVER_CORS_ORIGINS=http://localhost:${WEB_PORT},http://localhost:${WEB_HUB_PORT},http://localhost:${WEB_AGENT_PORT}

# ── Hub (PATCHIQ_HUB_ prefix for config overlay) ───────────
PATCHIQ_HUB_HUB_HTTP_PORT=${HUB_HTTP_PORT}
PATCHIQ_HUB_DATABASE_URL=postgres://patchiq:patchiq_dev@localhost:${PG_PORT}/${DB_NAME_HUB}?sslmode=disable
PATCHIQ_HUB_WATERMILL_POSTGRES_URL=postgres://patchiq:patchiq_dev@localhost:${PG_PORT}/${DB_NAME_HUB}?sslmode=disable
PATCHIQ_HUB_IAM_ZITADEL_DOMAIN=localhost:${ZITADEL_PORT}
PATCHIQ_HUB_IAM_ZITADEL_REDIRECT_URI=http://localhost:${HUB_HTTP_PORT}/api/v1/auth/callback
PATCHIQ_HUB_IAM_ZITADEL_SERVICE_ACCOUNT_KEY=
PATCHIQ_HUB_IAM_SESSION_POST_LOGIN_URL=http://localhost:${WEB_HUB_PORT}/
PATCHIQ_HUB_SYNC_API_KEY=patchiq-hub-sync-dev-key

# ── Server ↔ Hub sync ────────────────────────────────────────
PATCHIQ_HUB_URL=http://localhost:${HUB_HTTP_PORT}
PATCHIQ_HUB_API_KEY=patchiq-hub-sync-dev-key

# ── Agent (PATCHIQ_AGENT_ prefix) ──────────────────────────
PATCHIQ_AGENT_HTTP_ADDR=127.0.0.1:${AGENT_HTTP_PORT}
PATCHIQ_AGENT_SERVER_ADDRESS=localhost:${SERVER_GRPC_PORT}

# ── Frontend (Vite) ────────────────────────────────────────
VITE_SERVER_PORT=${WEB_PORT}
VITE_HUB_PORT=${WEB_HUB_PORT}
VITE_AGENT_PORT=${WEB_AGENT_PORT}
VITE_API_SERVER_URL=http://localhost:${SERVER_HTTP_PORT}
VITE_API_HUB_URL=http://localhost:${HUB_HTTP_PORT}
VITE_API_AGENT_URL=http://localhost:${AGENT_HTTP_PORT}

# ── Seed / migrate helpers ──────────────────────────────────
PGHOST=localhost
PGPORT=${PG_PORT}
PGUSER=patchiq
PGPASSWORD=patchiq_dev
EOF

echo "Generated .env for ${DEV_USER} (offset +${OFFSET})"
echo ""
echo "  Postgres:   localhost:${PG_PORT}  (DBs: ${DB_NAME_SERVER}, ${DB_NAME_HUB})"
echo "  Valkey:     localhost:${VALKEY_PORT}"
echo "  Zitadel:    localhost:${ZITADEL_PORT}"
echo "  Server:     localhost:${SERVER_HTTP_PORT} (gRPC :${SERVER_GRPC_PORT})"
echo "  Hub:        localhost:${HUB_HTTP_PORT}"
echo "  Agent:      localhost:${AGENT_HTTP_PORT}"
echo "  Web UI:     localhost:${WEB_PORT}"
echo "  Hub UI:     localhost:${WEB_HUB_PORT}"
echo "  Agent UI:   localhost:${WEB_AGENT_PORT}"
echo ""
echo "Next: make dev"
