#!/usr/bin/env bash
# Generates .env.prod for production/client-test deployment.
# Detects the VPN/LAN IP automatically and configures all services.
#
# Usage:
#   ./scripts/prod-env.sh              # auto-detect IP
#   ./scripts/prod-env.sh 10.0.5.13    # explicit IP

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env.prod"

# ── Detect host IP ──────────────────────────────────────────────
if [ -n "${1:-}" ]; then
    PROD_HOST="$1"
else
    # Pick the first non-loopback, non-docker IP
    PROD_HOST=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '^172\.' | head -1)
    if [ -z "$PROD_HOST" ]; then
        echo "Could not auto-detect host IP. Pass it explicitly: $0 <ip>" >&2
        exit 1
    fi
fi

# ── Port assignments (offset +400 to avoid collision with dev users) ──
PG_PORT=5832
VALKEY_PORT=6779
ZITADEL_PORT=8485
MINIO_API_PORT=9400
MINIO_CONSOLE_PORT=9401

SERVER_HTTP_PORT=8480
SERVER_GRPC_PORT=50451
HUB_HTTP_PORT=8482

WEB_PORT=3401
WEB_HUB_PORT=3402
WEB_AGENT_PORT=3403

AGENT_HTTP_PORT=8490

DB_NAME_SERVER="patchiq_dev_production"
DB_NAME_HUB="patchiq_hub_dev_production"

# ── Write .env.prod ─────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/prod-env.sh — do not edit manually.
# Host: ${PROD_HOST} | Production deployment
# Regenerate: ./scripts/prod-env.sh ${PROD_HOST}

COMPOSE_PROJECT_NAME=patchiq-prod

# ── Host IP (used for CORS, Zitadel, redirect URIs) ───────────
PROD_HOST=${PROD_HOST}

# ── Infrastructure ports ──────────────────────────────────────
PG_PORT=${PG_PORT}
VALKEY_PORT=${VALKEY_PORT}
ZITADEL_PORT=${ZITADEL_PORT}
MINIO_API_PORT=${MINIO_API_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}

# ── Database names ────────────────────────────────────────────
DB_NAME_SERVER=${DB_NAME_SERVER}
DB_NAME_HUB=${DB_NAME_HUB}

# ── Backend ports (host-side) ─────────────────────────────────
PATCHIQ_SERVER_HTTP_PORT=${SERVER_HTTP_PORT}
PATCHIQ_SERVER_GRPC_PORT=${SERVER_GRPC_PORT}
PATCHIQ_HUB_HTTP_PORT=${HUB_HTTP_PORT}

# ── Frontend ports ────────────────────────────────────────────
WEB_PORT=${WEB_PORT}
WEB_HUB_PORT=${WEB_HUB_PORT}
WEB_AGENT_PORT=${WEB_AGENT_PORT}

# ── Agent (for local testing) ─────────────────────────────────
PATCHIQ_AGENT_HTTP_ADDR=0.0.0.0:${AGENT_HTTP_PORT}
PATCHIQ_AGENT_SERVER_ADDRESS=${PROD_HOST}:${SERVER_GRPC_PORT}

# ── Seed / migrate helpers ────────────────────────────────────
PGHOST=localhost
PGPORT=${PG_PORT}
PGUSER=patchiq
PGPASSWORD=patchiq

# ── Hub ↔ Server sync ────────────────────────────────────────
PATCHIQ_HUB_SYNC_API_KEY=patchiq-hub-sync-dev-key
PATCHIQ_HUB_URL=http://localhost:${HUB_HTTP_PORT}
PATCHIQ_HUB_API_KEY=patchiq-hub-sync-dev-key
EOF

echo "Generated .env.prod for production deployment"
echo ""
echo "  Host:       ${PROD_HOST}"
echo "  Postgres:   localhost:${PG_PORT}  (DBs: ${DB_NAME_SERVER}, ${DB_NAME_HUB})"
echo "  Valkey:     localhost:${VALKEY_PORT}"
echo "  Zitadel:    http://${PROD_HOST}:${ZITADEL_PORT}"
echo "  Server:     http://${PROD_HOST}:${SERVER_HTTP_PORT} (gRPC :${SERVER_GRPC_PORT})"
echo "  Hub:        http://${PROD_HOST}:${HUB_HTTP_PORT}"
echo ""
echo "  Patch Manager UI:  http://${PROD_HOST}:${WEB_PORT}"
echo "  Hub Manager UI:    http://${PROD_HOST}:${WEB_HUB_PORT}"
echo "  Agent UI:          http://${PROD_HOST}:${WEB_AGENT_PORT}"
echo ""
echo "Next: make prod"
