// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_binaries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentBinary = `-- name: CreateAgentBinary :one
INSERT INTO agent_binaries (os_family, arch, version, download_url, checksum, released_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, os_family, arch, version, download_url, checksum, released_at, created_at
`

type CreateAgentBinaryParams struct {
	OsFamily    string             `json:"os_family"`
	Arch        string             `json:"arch"`
	Version     string             `json:"version"`
	DownloadUrl string             `json:"download_url"`
	Checksum    string             `json:"checksum"`
	ReleasedAt  pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) CreateAgentBinary(ctx context.Context, arg CreateAgentBinaryParams) (AgentBinary, error) {
	row := q.db.QueryRow(ctx, createAgentBinary,
		arg.OsFamily,
		arg.Arch,
		arg.Version,
		arg.DownloadUrl,
		arg.Checksum,
		arg.ReleasedAt,
	)
	var i AgentBinary
	err := row.Scan(
		&i.ID,
		&i.OsFamily,
		&i.Arch,
		&i.Version,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentBinaryByID = `-- name: GetAgentBinaryByID :one
SELECT id, os_family, arch, version, download_url, checksum, released_at, created_at FROM agent_binaries WHERE id = $1
`

func (q *Queries) GetAgentBinaryByID(ctx context.Context, id pgtype.UUID) (AgentBinary, error) {
	row := q.db.QueryRow(ctx, getAgentBinaryByID, id)
	var i AgentBinary
	err := row.Scan(
		&i.ID,
		&i.OsFamily,
		&i.Arch,
		&i.Version,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBinary = `-- name: GetLatestBinary :one
SELECT id, os_family, arch, version, download_url, checksum, released_at, created_at FROM agent_binaries
WHERE os_family = $1 AND arch = $2
ORDER BY released_at DESC
LIMIT 1
`

type GetLatestBinaryParams struct {
	OsFamily string `json:"os_family"`
	Arch     string `json:"arch"`
}

func (q *Queries) GetLatestBinary(ctx context.Context, arg GetLatestBinaryParams) (AgentBinary, error) {
	row := q.db.QueryRow(ctx, getLatestBinary, arg.OsFamily, arg.Arch)
	var i AgentBinary
	err := row.Scan(
		&i.ID,
		&i.OsFamily,
		&i.Arch,
		&i.Version,
		&i.DownloadUrl,
		&i.Checksum,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentBinaries = `-- name: ListAgentBinaries :many
SELECT id, os_family, arch, version, download_url, checksum, released_at, created_at FROM agent_binaries ORDER BY released_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentBinariesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAgentBinaries(ctx context.Context, arg ListAgentBinariesParams) ([]AgentBinary, error) {
	rows, err := q.db.Query(ctx, listAgentBinaries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentBinary{}
	for rows.Next() {
		var i AgentBinary
		if err := rows.Scan(
			&i.ID,
			&i.OsFamily,
			&i.Arch,
			&i.Version,
			&i.DownloadUrl,
			&i.Checksum,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
