// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: binary_fetch.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBinaryFetchState = `-- name: CreateBinaryFetchState :one
INSERT INTO binary_fetch_state (catalog_id, os_distribution, os_version, status, fetch_url)
VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT (catalog_id, os_distribution) DO NOTHING
RETURNING id, catalog_id, os_distribution, status, binary_ref, checksum_sha256, file_size_bytes, fetch_url, error_message, retry_count, last_attempt_at, created_at, updated_at, os_version
`

type CreateBinaryFetchStateParams struct {
	CatalogID      pgtype.UUID `json:"catalog_id"`
	OsDistribution string      `json:"os_distribution"`
	OsVersion      string      `json:"os_version"`
	FetchUrl       pgtype.Text `json:"fetch_url"`
}

func (q *Queries) CreateBinaryFetchState(ctx context.Context, arg CreateBinaryFetchStateParams) (BinaryFetchState, error) {
	row := q.db.QueryRow(ctx, createBinaryFetchState,
		arg.CatalogID,
		arg.OsDistribution,
		arg.OsVersion,
		arg.FetchUrl,
	)
	var i BinaryFetchState
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.OsDistribution,
		&i.Status,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.FileSizeBytes,
		&i.FetchUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsVersion,
	)
	return i, err
}

const getBinaryFetchState = `-- name: GetBinaryFetchState :one
SELECT id, catalog_id, os_distribution, status, binary_ref, checksum_sha256, file_size_bytes, fetch_url, error_message, retry_count, last_attempt_at, created_at, updated_at, os_version FROM binary_fetch_state
WHERE catalog_id = $1 AND os_distribution = $2
`

type GetBinaryFetchStateParams struct {
	CatalogID      pgtype.UUID `json:"catalog_id"`
	OsDistribution string      `json:"os_distribution"`
}

func (q *Queries) GetBinaryFetchState(ctx context.Context, arg GetBinaryFetchStateParams) (BinaryFetchState, error) {
	row := q.db.QueryRow(ctx, getBinaryFetchState, arg.CatalogID, arg.OsDistribution)
	var i BinaryFetchState
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.OsDistribution,
		&i.Status,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.FileSizeBytes,
		&i.FetchUrl,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsVersion,
	)
	return i, err
}

const listPendingBinaryFetches = `-- name: ListPendingBinaryFetches :many
SELECT id, catalog_id, os_distribution, status, binary_ref, checksum_sha256, file_size_bytes, fetch_url, error_message, retry_count, last_attempt_at, created_at, updated_at, os_version FROM binary_fetch_state
WHERE status IN ('pending', 'failed')
AND (retry_count < 3 OR status = 'pending')
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingBinaryFetches(ctx context.Context, limit int32) ([]BinaryFetchState, error) {
	rows, err := q.db.Query(ctx, listPendingBinaryFetches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BinaryFetchState{}
	for rows.Next() {
		var i BinaryFetchState
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.OsDistribution,
			&i.Status,
			&i.BinaryRef,
			&i.ChecksumSha256,
			&i.FileSizeBytes,
			&i.FetchUrl,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBinaryFetchFailed = `-- name: UpdateBinaryFetchFailed :exec
UPDATE binary_fetch_state
SET status = 'failed',
    error_message = $2,
    retry_count = retry_count + 1,
    last_attempt_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateBinaryFetchFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateBinaryFetchFailed(ctx context.Context, arg UpdateBinaryFetchFailedParams) error {
	_, err := q.db.Exec(ctx, updateBinaryFetchFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateBinaryFetchSuccess = `-- name: UpdateBinaryFetchSuccess :exec
UPDATE binary_fetch_state
SET status = 'complete',
    binary_ref = $2,
    checksum_sha256 = $3,
    file_size_bytes = $4,
    last_attempt_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateBinaryFetchSuccessParams struct {
	ID             pgtype.UUID `json:"id"`
	BinaryRef      pgtype.Text `json:"binary_ref"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
}

func (q *Queries) UpdateBinaryFetchSuccess(ctx context.Context, arg UpdateBinaryFetchSuccessParams) error {
	_, err := q.db.Exec(ctx, updateBinaryFetchSuccess,
		arg.ID,
		arg.BinaryRef,
		arg.ChecksumSha256,
		arg.FileSizeBytes,
	)
	return err
}
