// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_entry_syncs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedClients = `-- name: CountApprovedClients :one
SELECT count(*) FROM clients WHERE status = 'approved'
`

func (q *Queries) CountApprovedClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSyncedClientsForCatalogEntry = `-- name: CountSyncedClientsForCatalogEntry :one
SELECT count(*) FROM catalog_entry_syncs
WHERE catalog_id = $1 AND status = 'synced'
`

func (q *Queries) CountSyncedClientsForCatalogEntry(ctx context.Context, catalogID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncedClientsForCatalogEntry, catalogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCatalogStats = `-- name: GetCatalogStats :one
SELECT
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL) AS total_entries,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL AND created_at > now() - interval '7 days') AS new_this_week,
    (SELECT count(*) FROM patch_catalog_cves pcc JOIN patch_catalog pc ON pc.id = pcc.catalog_id WHERE pc.deleted_at IS NULL) AS cves_tracked,
    (SELECT count(DISTINCT ces.catalog_id) FROM catalog_entry_syncs ces JOIN patch_catalog pc ON pc.id = ces.catalog_id WHERE pc.deleted_at IS NULL AND ces.status = 'synced') AS synced_entries,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL) AS total_for_sync_pct,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL AND severity = 'critical') AS critical_count,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL AND severity = 'high') AS high_count,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL AND severity = 'medium') AS medium_count,
    (SELECT count(*) FROM patch_catalog WHERE deleted_at IS NULL AND severity = 'low') AS low_count
`

type GetCatalogStatsRow struct {
	TotalEntries    int64 `json:"total_entries"`
	NewThisWeek     int64 `json:"new_this_week"`
	CvesTracked     int64 `json:"cves_tracked"`
	SyncedEntries   int64 `json:"synced_entries"`
	TotalForSyncPct int64 `json:"total_for_sync_pct"`
	CriticalCount   int64 `json:"critical_count"`
	HighCount       int64 `json:"high_count"`
	MediumCount     int64 `json:"medium_count"`
	LowCount        int64 `json:"low_count"`
}

func (q *Queries) GetCatalogStats(ctx context.Context) (GetCatalogStatsRow, error) {
	row := q.db.QueryRow(ctx, getCatalogStats)
	var i GetCatalogStatsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.NewThisWeek,
		&i.CvesTracked,
		&i.SyncedEntries,
		&i.TotalForSyncPct,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
	)
	return i, err
}

const listApprovedClientsBasic = `-- name: ListApprovedClientsBasic :many
SELECT id, hostname, endpoint_count
FROM clients
WHERE status = 'approved'
ORDER BY hostname
LIMIT 1000
`

type ListApprovedClientsBasicRow struct {
	ID            pgtype.UUID `json:"id"`
	Hostname      string      `json:"hostname"`
	EndpointCount int32       `json:"endpoint_count"`
}

// Separate query for client info (runs with tenant context from middleware).
func (q *Queries) ListApprovedClientsBasic(ctx context.Context) ([]ListApprovedClientsBasicRow, error) {
	rows, err := q.db.Query(ctx, listApprovedClientsBasic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedClientsBasicRow{}
	for rows.Next() {
		var i ListApprovedClientsBasicRow
		if err := rows.Scan(&i.ID, &i.Hostname, &i.EndpointCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncsForCatalogEntry = `-- name: ListSyncsForCatalogEntry :many
SELECT id, catalog_id, client_id, status, synced_at, created_at
FROM catalog_entry_syncs
WHERE catalog_id = $1
ORDER BY synced_at NULLS LAST
LIMIT 1000
`

type ListSyncsForCatalogEntryRow struct {
	ID        pgtype.UUID        `json:"id"`
	CatalogID pgtype.UUID        `json:"catalog_id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	Status    string             `json:"status"`
	SyncedAt  pgtype.Timestamptz `json:"synced_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// No JOIN on clients (RLS blocks it). Client info resolved in handler.
func (q *Queries) ListSyncsForCatalogEntry(ctx context.Context, catalogID pgtype.UUID) ([]ListSyncsForCatalogEntryRow, error) {
	rows, err := q.db.Query(ctx, listSyncsForCatalogEntry, catalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncsForCatalogEntryRow{}
	for rows.Next() {
		var i ListSyncsForCatalogEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.ClientID,
			&i.Status,
			&i.SyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
