// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_sync_history.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClientSyncHistory = `-- name: CountClientSyncHistory :one
SELECT COUNT(*)::bigint
FROM client_sync_history
WHERE tenant_id = $1
  AND client_id = $2
`

type CountClientSyncHistoryParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) CountClientSyncHistory(ctx context.Context, arg CountClientSyncHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClientSyncHistory, arg.TenantID, arg.ClientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getClientEndpointTrend = `-- name: GetClientEndpointTrend :many
SELECT DATE(started_at) AS date, MAX(endpoint_count)::int AS endpoint_count
FROM client_sync_history
WHERE tenant_id = $1
  AND client_id = $2
  AND started_at > now() - make_interval(days => $3::int)
GROUP BY DATE(started_at)
ORDER BY date
LIMIT 365
`

type GetClientEndpointTrendParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ClientID pgtype.UUID `json:"client_id"`
	Days     int32       `json:"days"`
}

type GetClientEndpointTrendRow struct {
	Date          pgtype.Date `json:"date"`
	EndpointCount int32       `json:"endpoint_count"`
}

func (q *Queries) GetClientEndpointTrend(ctx context.Context, arg GetClientEndpointTrendParams) ([]GetClientEndpointTrendRow, error) {
	rows, err := q.db.Query(ctx, getClientEndpointTrend, arg.TenantID, arg.ClientID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClientEndpointTrendRow{}
	for rows.Next() {
		var i GetClientEndpointTrendRow
		if err := rows.Scan(&i.Date, &i.EndpointCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicenseUsageHistory = `-- name: GetLicenseUsageHistory :many
SELECT DATE(csh.started_at) AS date, MAX(csh.endpoint_count)::int AS endpoint_count
FROM client_sync_history csh
JOIN licenses l ON l.client_id = csh.client_id AND l.tenant_id = csh.tenant_id
WHERE l.id = $1
  AND l.tenant_id = $2
  AND csh.started_at > now() - make_interval(days => $3::int)
GROUP BY DATE(csh.started_at)
ORDER BY date
LIMIT 365
`

type GetLicenseUsageHistoryParams struct {
	LicenseID pgtype.UUID `json:"license_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Days      int32       `json:"days"`
}

type GetLicenseUsageHistoryRow struct {
	Date          pgtype.Date `json:"date"`
	EndpointCount int32       `json:"endpoint_count"`
}

func (q *Queries) GetLicenseUsageHistory(ctx context.Context, arg GetLicenseUsageHistoryParams) ([]GetLicenseUsageHistoryRow, error) {
	rows, err := q.db.Query(ctx, getLicenseUsageHistory, arg.LicenseID, arg.TenantID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLicenseUsageHistoryRow{}
	for rows.Next() {
		var i GetLicenseUsageHistoryRow
		if err := rows.Scan(&i.Date, &i.EndpointCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClientSyncHistory = `-- name: InsertClientSyncHistory :one
INSERT INTO client_sync_history (
    tenant_id, client_id, started_at, finished_at, duration_ms,
    entries_delivered, deletes_delivered, endpoint_count, status, error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, client_id, started_at, finished_at, duration_ms, entries_delivered, deletes_delivered, endpoint_count, status, error_message, created_at
`

type InsertClientSyncHistoryParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ClientID         pgtype.UUID        `json:"client_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	DurationMs       pgtype.Int4        `json:"duration_ms"`
	EntriesDelivered int32              `json:"entries_delivered"`
	DeletesDelivered int32              `json:"deletes_delivered"`
	EndpointCount    int32              `json:"endpoint_count"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
}

func (q *Queries) InsertClientSyncHistory(ctx context.Context, arg InsertClientSyncHistoryParams) (ClientSyncHistory, error) {
	row := q.db.QueryRow(ctx, insertClientSyncHistory,
		arg.TenantID,
		arg.ClientID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.EntriesDelivered,
		arg.DeletesDelivered,
		arg.EndpointCount,
		arg.Status,
		arg.ErrorMessage,
	)
	var i ClientSyncHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.EntriesDelivered,
		&i.DeletesDelivered,
		&i.EndpointCount,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listClientSyncHistory = `-- name: ListClientSyncHistory :many
SELECT id, tenant_id, client_id, started_at, finished_at, duration_ms, entries_delivered, deletes_delivered, endpoint_count, status, error_message, created_at
FROM client_sync_history
WHERE tenant_id = $1
  AND client_id = $2
ORDER BY started_at DESC
LIMIT $4 OFFSET $3
`

type ListClientSyncHistoryParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ClientID    pgtype.UUID `json:"client_id"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListClientSyncHistory(ctx context.Context, arg ListClientSyncHistoryParams) ([]ClientSyncHistory, error) {
	rows, err := q.db.Query(ctx, listClientSyncHistory,
		arg.TenantID,
		arg.ClientID,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientSyncHistory{}
	for rows.Next() {
		var i ClientSyncHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.EntriesDelivered,
			&i.DeletesDelivered,
			&i.EndpointCount,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
