// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveClient = `-- name: ApproveClient :one
UPDATE clients
SET status = 'approved', api_key_hash = $2, updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

type ApproveClientParams struct {
	ID         pgtype.UUID `json:"id"`
	ApiKeyHash pgtype.Text `json:"api_key_hash"`
}

func (q *Queries) ApproveClient(ctx context.Context, arg ApproveClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, approveClient, arg.ID, arg.ApiKeyHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const countClients = `-- name: CountClients :one
SELECT count(*) FROM clients
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountClients(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countClients, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingClients = `-- name: CountPendingClients :one
SELECT count(*) FROM clients WHERE status = 'pending'
`

func (q *Queries) CountPendingClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (tenant_id, hostname, version, os, endpoint_count, contact_email, status, bootstrap_token)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

type CreateClientParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Hostname       string      `json:"hostname"`
	Version        pgtype.Text `json:"version"`
	Os             pgtype.Text `json:"os"`
	EndpointCount  int32       `json:"endpoint_count"`
	ContactEmail   pgtype.Text `json:"contact_email"`
	BootstrapToken string      `json:"bootstrap_token"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.TenantID,
		arg.Hostname,
		arg.Version,
		arg.Os,
		arg.EndpointCount,
		arg.ContactEmail,
		arg.BootstrapToken,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const declineClient = `-- name: DeclineClient :one
UPDATE clients
SET status = 'declined', updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

func (q *Queries) DeclineClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, declineClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByAPIKeyHash = `-- name: GetClientByAPIKeyHash :one
SELECT id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary FROM clients WHERE api_key_hash = $1 AND status = 'approved'
`

func (q *Queries) GetClientByAPIKeyHash(ctx context.Context, apiKeyHash pgtype.Text) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByAPIKeyHash, apiKeyHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const getClientByBootstrapToken = `-- name: GetClientByBootstrapToken :one
SELECT id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary FROM clients WHERE bootstrap_token = $1
`

func (q *Queries) GetClientByBootstrapToken(ctx context.Context, bootstrapToken string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByBootstrapToken, bootstrapToken)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary FROM clients
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListClientsParams struct {
	Status      pgtype.Text `json:"status"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Status, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Hostname,
			&i.Version,
			&i.Os,
			&i.EndpointCount,
			&i.ContactEmail,
			&i.Status,
			&i.ApiKeyHash,
			&i.BootstrapToken,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OsSummary,
			&i.EndpointStatusSummary,
			&i.ComplianceSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendClient = `-- name: SuspendClient :one
UPDATE clients
SET status = 'suspended', updated_at = now()
WHERE id = $1 AND status = 'approved'
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

func (q *Queries) SuspendClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, suspendClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET hostname = COALESCE($2, hostname),
    sync_interval = COALESCE($3, sync_interval),
    notes = COALESCE($4, notes),
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

type UpdateClientParams struct {
	ID           pgtype.UUID `json:"id"`
	Hostname     pgtype.Text `json:"hostname"`
	SyncInterval pgtype.Int4 `json:"sync_interval"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Hostname,
		arg.SyncInterval,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const updateClientSummaries = `-- name: UpdateClientSummaries :one
UPDATE clients
SET endpoint_count = $1,
    last_sync_at = now(),
    os_summary = CASE WHEN $2::jsonb = '{}'::jsonb THEN os_summary ELSE $2 END,
    endpoint_status_summary = CASE WHEN $3::jsonb = '{}'::jsonb THEN endpoint_status_summary ELSE $3 END,
    compliance_summary = CASE WHEN $4::jsonb = '{}'::jsonb THEN compliance_summary ELSE $4 END,
    updated_at = now()
WHERE id = $5
RETURNING id, tenant_id, hostname, version, os, endpoint_count, contact_email, status, api_key_hash, bootstrap_token, sync_interval, last_sync_at, notes, created_at, updated_at, os_summary, endpoint_status_summary, compliance_summary
`

type UpdateClientSummariesParams struct {
	EndpointCount         int32       `json:"endpoint_count"`
	OsSummary             []byte      `json:"os_summary"`
	EndpointStatusSummary []byte      `json:"endpoint_status_summary"`
	ComplianceSummary     []byte      `json:"compliance_summary"`
	ID                    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateClientSummaries(ctx context.Context, arg UpdateClientSummariesParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientSummaries,
		arg.EndpointCount,
		arg.OsSummary,
		arg.EndpointStatusSummary,
		arg.ComplianceSummary,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Hostname,
		&i.Version,
		&i.Os,
		&i.EndpointCount,
		&i.ContactEmail,
		&i.Status,
		&i.ApiKeyHash,
		&i.BootstrapToken,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OsSummary,
		&i.EndpointStatusSummary,
		&i.ComplianceSummary,
	)
	return i, err
}

const updateClientSyncTime = `-- name: UpdateClientSyncTime :exec
UPDATE clients
SET last_sync_at = now(), endpoint_count = $2, version = $3, updated_at = now()
WHERE id = $1
`

type UpdateClientSyncTimeParams struct {
	ID            pgtype.UUID `json:"id"`
	EndpointCount int32       `json:"endpoint_count"`
	Version       pgtype.Text `json:"version"`
}

func (q *Queries) UpdateClientSyncTime(ctx context.Context, arg UpdateClientSyncTimeParams) error {
	_, err := q.db.Exec(ctx, updateClientSyncTime, arg.ID, arg.EndpointCount, arg.Version)
	return err
}
