// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cve_feeds.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCVEFeed = `-- name: CreateCVEFeed :one
INSERT INTO cve_feeds (
    cve_id, severity, description, published_at, source,
    cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id,
    cisa_kev_due_date, external_references, nvd_last_modified
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified
`

type CreateCVEFeedParams struct {
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	Source             string             `json:"source"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	CweID              pgtype.Text        `json:"cwe_id"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	ExternalReferences []byte             `json:"external_references"`
	NvdLastModified    pgtype.Timestamptz `json:"nvd_last_modified"`
}

func (q *Queries) CreateCVEFeed(ctx context.Context, arg CreateCVEFeedParams) (CVEFeed, error) {
	row := q.db.QueryRow(ctx, createCVEFeed,
		arg.CveID,
		arg.Severity,
		arg.Description,
		arg.PublishedAt,
		arg.Source,
		arg.CvssV3Score,
		arg.CvssV3Vector,
		arg.AttackVector,
		arg.CweID,
		arg.CisaKevDueDate,
		arg.ExternalReferences,
		arg.NvdLastModified,
	)
	var i CVEFeed
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExploitKnown,
		&i.InKev,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.AttackVector,
		&i.CweID,
		&i.CisaKevDueDate,
		&i.ExternalReferences,
		&i.NvdLastModified,
	)
	return i, err
}

const getCVEFeedByCVEID = `-- name: GetCVEFeedByCVEID :one
SELECT id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified FROM cve_feeds WHERE cve_id = $1
`

func (q *Queries) GetCVEFeedByCVEID(ctx context.Context, cveID string) (CVEFeed, error) {
	row := q.db.QueryRow(ctx, getCVEFeedByCVEID, cveID)
	var i CVEFeed
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExploitKnown,
		&i.InKev,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.AttackVector,
		&i.CweID,
		&i.CisaKevDueDate,
		&i.ExternalReferences,
		&i.NvdLastModified,
	)
	return i, err
}

const getCVEFeedByID = `-- name: GetCVEFeedByID :one
SELECT id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified FROM cve_feeds WHERE id = $1
`

func (q *Queries) GetCVEFeedByID(ctx context.Context, id pgtype.UUID) (CVEFeed, error) {
	row := q.db.QueryRow(ctx, getCVEFeedByID, id)
	var i CVEFeed
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExploitKnown,
		&i.InKev,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.AttackVector,
		&i.CweID,
		&i.CisaKevDueDate,
		&i.ExternalReferences,
		&i.NvdLastModified,
	)
	return i, err
}

const listCVEFeeds = `-- name: ListCVEFeeds :many
SELECT id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified FROM cve_feeds ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCVEFeedsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCVEFeeds(ctx context.Context, arg ListCVEFeedsParams) ([]CVEFeed, error) {
	rows, err := q.db.Query(ctx, listCVEFeeds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CVEFeed{}
	for rows.Next() {
		var i CVEFeed
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExploitKnown,
			&i.InKev,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.AttackVector,
			&i.CweID,
			&i.CisaKevDueDate,
			&i.ExternalReferences,
			&i.NvdLastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEFeedsUpdatedSince = `-- name: ListCVEFeedsUpdatedSince :many
SELECT id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified FROM cve_feeds WHERE updated_at > $1
ORDER BY updated_at ASC
LIMIT $2
`

type ListCVEFeedsUpdatedSinceParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListCVEFeedsUpdatedSince(ctx context.Context, arg ListCVEFeedsUpdatedSinceParams) ([]CVEFeed, error) {
	rows, err := q.db.Query(ctx, listCVEFeedsUpdatedSince, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CVEFeed{}
	for rows.Next() {
		var i CVEFeed
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExploitKnown,
			&i.InKev,
			&i.CvssV3Score,
			&i.CvssV3Vector,
			&i.AttackVector,
			&i.CweID,
			&i.CisaKevDueDate,
			&i.ExternalReferences,
			&i.NvdLastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCVEFeed = `-- name: UpdateCVEFeed :one
UPDATE cve_feeds
SET severity = $2, description = $3, published_at = $4, source = $5, updated_at = now()
WHERE id = $1
RETURNING id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified
`

type UpdateCVEFeedParams struct {
	ID          pgtype.UUID        `json:"id"`
	Severity    string             `json:"severity"`
	Description pgtype.Text        `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Source      string             `json:"source"`
}

func (q *Queries) UpdateCVEFeed(ctx context.Context, arg UpdateCVEFeedParams) (CVEFeed, error) {
	row := q.db.QueryRow(ctx, updateCVEFeed,
		arg.ID,
		arg.Severity,
		arg.Description,
		arg.PublishedAt,
		arg.Source,
	)
	var i CVEFeed
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExploitKnown,
		&i.InKev,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.AttackVector,
		&i.CweID,
		&i.CisaKevDueDate,
		&i.ExternalReferences,
		&i.NvdLastModified,
	)
	return i, err
}

const upsertCVEFeed = `-- name: UpsertCVEFeed :one
INSERT INTO cve_feeds (
    cve_id, severity, description, published_at, source,
    cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id,
    cisa_kev_due_date, external_references, nvd_last_modified,
    exploit_known, in_kev
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (cve_id) DO UPDATE SET
    severity           = COALESCE(NULLIF(EXCLUDED.severity, ''), cve_feeds.severity),
    description        = COALESCE(EXCLUDED.description, cve_feeds.description),
    published_at       = COALESCE(EXCLUDED.published_at, cve_feeds.published_at),
    source             = COALESCE(NULLIF(EXCLUDED.source, ''), cve_feeds.source),
    cvss_v3_score      = COALESCE(EXCLUDED.cvss_v3_score, cve_feeds.cvss_v3_score),
    cvss_v3_vector     = COALESCE(NULLIF(EXCLUDED.cvss_v3_vector, ''), cve_feeds.cvss_v3_vector),
    attack_vector      = COALESCE(NULLIF(EXCLUDED.attack_vector, ''), cve_feeds.attack_vector),
    cwe_id             = COALESCE(NULLIF(EXCLUDED.cwe_id, ''), cve_feeds.cwe_id),
    cisa_kev_due_date  = COALESCE(EXCLUDED.cisa_kev_due_date, cve_feeds.cisa_kev_due_date),
    external_references = CASE
        WHEN EXCLUDED.external_references IS NOT NULL AND EXCLUDED.external_references != '[]'::jsonb
        THEN EXCLUDED.external_references
        ELSE cve_feeds.external_references
    END,
    nvd_last_modified  = COALESCE(EXCLUDED.nvd_last_modified, cve_feeds.nvd_last_modified),
    exploit_known      = EXCLUDED.exploit_known OR cve_feeds.exploit_known,
    in_kev             = EXCLUDED.in_kev OR cve_feeds.in_kev,
    updated_at         = now()
RETURNING id, cve_id, severity, description, published_at, source, created_at, updated_at, exploit_known, in_kev, cvss_v3_score, cvss_v3_vector, attack_vector, cwe_id, cisa_kev_due_date, external_references, nvd_last_modified
`

type UpsertCVEFeedParams struct {
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	Source             string             `json:"source"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	CweID              pgtype.Text        `json:"cwe_id"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	ExternalReferences []byte             `json:"external_references"`
	NvdLastModified    pgtype.Timestamptz `json:"nvd_last_modified"`
	ExploitKnown       bool               `json:"exploit_known"`
	InKev              bool               `json:"in_kev"`
}

func (q *Queries) UpsertCVEFeed(ctx context.Context, arg UpsertCVEFeedParams) (CVEFeed, error) {
	row := q.db.QueryRow(ctx, upsertCVEFeed,
		arg.CveID,
		arg.Severity,
		arg.Description,
		arg.PublishedAt,
		arg.Source,
		arg.CvssV3Score,
		arg.CvssV3Vector,
		arg.AttackVector,
		arg.CweID,
		arg.CisaKevDueDate,
		arg.ExternalReferences,
		arg.NvdLastModified,
		arg.ExploitKnown,
		arg.InKev,
	)
	var i CVEFeed
	err := row.Scan(
		&i.ID,
		&i.CveID,
		&i.Severity,
		&i.Description,
		&i.PublishedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExploitKnown,
		&i.InKev,
		&i.CvssV3Score,
		&i.CvssV3Vector,
		&i.AttackVector,
		&i.CweID,
		&i.CisaKevDueDate,
		&i.ExternalReferences,
		&i.NvdLastModified,
	)
	return i, err
}
