// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_sources.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeedSourceByID = `-- name: GetFeedSourceByID :one
SELECT id, name, display_name, enabled, sync_interval_seconds, created_at, updated_at, auth_type, severity_filter, os_filter, severity_mapping, url FROM feed_sources WHERE id = $1
`

func (q *Queries) GetFeedSourceByID(ctx context.Context, id pgtype.UUID) (FeedSource, error) {
	row := q.db.QueryRow(ctx, getFeedSourceByID, id)
	var i FeedSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.SyncIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthType,
		&i.SeverityFilter,
		&i.OsFilter,
		&i.SeverityMapping,
		&i.Url,
	)
	return i, err
}

const getFeedSourceByName = `-- name: GetFeedSourceByName :one
SELECT id, name, display_name, enabled, sync_interval_seconds, created_at, updated_at, auth_type, severity_filter, os_filter, severity_mapping, url FROM feed_sources WHERE name = $1
`

func (q *Queries) GetFeedSourceByName(ctx context.Context, name string) (FeedSource, error) {
	row := q.db.QueryRow(ctx, getFeedSourceByName, name)
	var i FeedSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.SyncIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthType,
		&i.SeverityFilter,
		&i.OsFilter,
		&i.SeverityMapping,
		&i.Url,
	)
	return i, err
}

const getFeedSourceWithSyncStateByID = `-- name: GetFeedSourceWithSyncStateByID :one
SELECT fs.id, fs.name, fs.display_name, fs.enabled, fs.sync_interval_seconds,
       fs.url, fs.auth_type, fs.severity_filter, fs.os_filter, fs.severity_mapping,
       fs.created_at, fs.updated_at,
       fss.last_sync_at, fss.next_sync_at, fss.status, fss.error_count,
       fss.last_error, fss.entries_ingested, fss.cursor
FROM feed_sources fs
LEFT JOIN feed_sync_state fss ON fss.feed_source_id = fs.id
WHERE fs.id = $1
`

type GetFeedSourceWithSyncStateByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	DisplayName         string             `json:"display_name"`
	Enabled             bool               `json:"enabled"`
	SyncIntervalSeconds int32              `json:"sync_interval_seconds"`
	Url                 string             `json:"url"`
	AuthType            string             `json:"auth_type"`
	SeverityFilter      []string           `json:"severity_filter"`
	OsFilter            []string           `json:"os_filter"`
	SeverityMapping     []byte             `json:"severity_mapping"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastSyncAt          pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt          pgtype.Timestamptz `json:"next_sync_at"`
	Status              pgtype.Text        `json:"status"`
	ErrorCount          pgtype.Int4        `json:"error_count"`
	LastError           pgtype.Text        `json:"last_error"`
	EntriesIngested     pgtype.Int8        `json:"entries_ingested"`
	Cursor              pgtype.Text        `json:"cursor"`
}

func (q *Queries) GetFeedSourceWithSyncStateByID(ctx context.Context, id pgtype.UUID) (GetFeedSourceWithSyncStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getFeedSourceWithSyncStateByID, id)
	var i GetFeedSourceWithSyncStateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.SyncIntervalSeconds,
		&i.Url,
		&i.AuthType,
		&i.SeverityFilter,
		&i.OsFilter,
		&i.SeverityMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.Status,
		&i.ErrorCount,
		&i.LastError,
		&i.EntriesIngested,
		&i.Cursor,
	)
	return i, err
}

const getFeedSyncState = `-- name: GetFeedSyncState :one
SELECT id, feed_source_id, last_sync_at, next_sync_at, cursor, entries_ingested, error_count, last_error, status, created_at, updated_at FROM feed_sync_state WHERE feed_source_id = $1
`

func (q *Queries) GetFeedSyncState(ctx context.Context, feedSourceID pgtype.UUID) (FeedSyncState, error) {
	row := q.db.QueryRow(ctx, getFeedSyncState, feedSourceID)
	var i FeedSyncState
	err := row.Scan(
		&i.ID,
		&i.FeedSourceID,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.Cursor,
		&i.EntriesIngested,
		&i.ErrorCount,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledFeedSources = `-- name: ListEnabledFeedSources :many
SELECT id, name, display_name, enabled, sync_interval_seconds, created_at, updated_at, auth_type, severity_filter, os_filter, severity_mapping, url FROM feed_sources WHERE enabled = true ORDER BY name
LIMIT 100
`

func (q *Queries) ListEnabledFeedSources(ctx context.Context) ([]FeedSource, error) {
	rows, err := q.db.Query(ctx, listEnabledFeedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSource{}
	for rows.Next() {
		var i FeedSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.SyncIntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthType,
			&i.SeverityFilter,
			&i.OsFilter,
			&i.SeverityMapping,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedSources = `-- name: ListFeedSources :many
SELECT id, name, display_name, enabled, sync_interval_seconds, created_at, updated_at, auth_type, severity_filter, os_filter, severity_mapping, url FROM feed_sources ORDER BY name
LIMIT 100
`

func (q *Queries) ListFeedSources(ctx context.Context) ([]FeedSource, error) {
	rows, err := q.db.Query(ctx, listFeedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSource{}
	for rows.Next() {
		var i FeedSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.SyncIntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthType,
			&i.SeverityFilter,
			&i.OsFilter,
			&i.SeverityMapping,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedSourcesWithSyncState = `-- name: ListFeedSourcesWithSyncState :many
SELECT
    fs.id,
    fs.name,
    fs.display_name,
    fs.enabled,
    fs.sync_interval_seconds,
    fs.url,
    fs.auth_type,
    fss.last_sync_at,
    fss.next_sync_at,
    fss.status,
    fss.error_count,
    fss.last_error,
    fss.entries_ingested,
    fss.cursor
FROM feed_sources fs
LEFT JOIN feed_sync_state fss ON fss.feed_source_id = fs.id
ORDER BY fs.name
LIMIT 100
`

type ListFeedSourcesWithSyncStateRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	DisplayName         string             `json:"display_name"`
	Enabled             bool               `json:"enabled"`
	SyncIntervalSeconds int32              `json:"sync_interval_seconds"`
	Url                 string             `json:"url"`
	AuthType            string             `json:"auth_type"`
	LastSyncAt          pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt          pgtype.Timestamptz `json:"next_sync_at"`
	Status              pgtype.Text        `json:"status"`
	ErrorCount          pgtype.Int4        `json:"error_count"`
	LastError           pgtype.Text        `json:"last_error"`
	EntriesIngested     pgtype.Int8        `json:"entries_ingested"`
	Cursor              pgtype.Text        `json:"cursor"`
}

func (q *Queries) ListFeedSourcesWithSyncState(ctx context.Context) ([]ListFeedSourcesWithSyncStateRow, error) {
	rows, err := q.db.Query(ctx, listFeedSourcesWithSyncState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedSourcesWithSyncStateRow{}
	for rows.Next() {
		var i ListFeedSourcesWithSyncStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Enabled,
			&i.SyncIntervalSeconds,
			&i.Url,
			&i.AuthType,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.Status,
			&i.ErrorCount,
			&i.LastError,
			&i.EntriesIngested,
			&i.Cursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedSource = `-- name: UpdateFeedSource :one
UPDATE feed_sources
SET enabled = COALESCE($1, enabled),
    sync_interval_seconds = COALESCE($2, sync_interval_seconds),
    url = COALESCE($3, url),
    auth_type = COALESCE($4, auth_type),
    severity_filter = COALESCE($5, severity_filter),
    os_filter = COALESCE($6, os_filter),
    severity_mapping = COALESCE($7, severity_mapping),
    updated_at = now()
WHERE id = $8
RETURNING id, name, display_name, enabled, sync_interval_seconds, created_at, updated_at, auth_type, severity_filter, os_filter, severity_mapping, url
`

type UpdateFeedSourceParams struct {
	Enabled             pgtype.Bool `json:"enabled"`
	SyncIntervalSeconds pgtype.Int4 `json:"sync_interval_seconds"`
	Url                 pgtype.Text `json:"url"`
	AuthType            pgtype.Text `json:"auth_type"`
	SeverityFilter      []string    `json:"severity_filter"`
	OsFilter            []string    `json:"os_filter"`
	SeverityMapping     []byte      `json:"severity_mapping"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFeedSource(ctx context.Context, arg UpdateFeedSourceParams) (FeedSource, error) {
	row := q.db.QueryRow(ctx, updateFeedSource,
		arg.Enabled,
		arg.SyncIntervalSeconds,
		arg.Url,
		arg.AuthType,
		arg.SeverityFilter,
		arg.OsFilter,
		arg.SeverityMapping,
		arg.ID,
	)
	var i FeedSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Enabled,
		&i.SyncIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthType,
		&i.SeverityFilter,
		&i.OsFilter,
		&i.SeverityMapping,
		&i.Url,
	)
	return i, err
}

const updateFeedSourceEnabled = `-- name: UpdateFeedSourceEnabled :exec
UPDATE feed_sources SET enabled = $2, updated_at = now() WHERE id = $1
`

type UpdateFeedSourceEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdateFeedSourceEnabled(ctx context.Context, arg UpdateFeedSourceEnabledParams) error {
	_, err := q.db.Exec(ctx, updateFeedSourceEnabled, arg.ID, arg.Enabled)
	return err
}

const updateFeedSyncStateError = `-- name: UpdateFeedSyncStateError :exec
UPDATE feed_sync_state
SET status = 'error',
    error_count = error_count + 1,
    last_error = $2,
    updated_at = now()
WHERE feed_source_id = $1
`

type UpdateFeedSyncStateErrorParams struct {
	FeedSourceID pgtype.UUID `json:"feed_source_id"`
	LastError    pgtype.Text `json:"last_error"`
}

func (q *Queries) UpdateFeedSyncStateError(ctx context.Context, arg UpdateFeedSyncStateErrorParams) error {
	_, err := q.db.Exec(ctx, updateFeedSyncStateError, arg.FeedSourceID, arg.LastError)
	return err
}

const updateFeedSyncStateStart = `-- name: UpdateFeedSyncStateStart :exec
UPDATE feed_sync_state SET status = 'syncing', updated_at = now() WHERE feed_source_id = $1
`

func (q *Queries) UpdateFeedSyncStateStart(ctx context.Context, feedSourceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateFeedSyncStateStart, feedSourceID)
	return err
}

const updateFeedSyncStateSuccess = `-- name: UpdateFeedSyncStateSuccess :exec
UPDATE feed_sync_state
SET status = 'idle',
    last_sync_at = now(),
    next_sync_at = $2,
    cursor = $3,
    entries_ingested = entries_ingested + $4,
    error_count = 0,
    last_error = NULL,
    updated_at = now()
WHERE feed_source_id = $1
`

type UpdateFeedSyncStateSuccessParams struct {
	FeedSourceID    pgtype.UUID        `json:"feed_source_id"`
	NextSyncAt      pgtype.Timestamptz `json:"next_sync_at"`
	Cursor          string             `json:"cursor"`
	EntriesIngested int64              `json:"entries_ingested"`
}

func (q *Queries) UpdateFeedSyncStateSuccess(ctx context.Context, arg UpdateFeedSyncStateSuccessParams) error {
	_, err := q.db.Exec(ctx, updateFeedSyncStateSuccess,
		arg.FeedSourceID,
		arg.NextSyncAt,
		arg.Cursor,
		arg.EntriesIngested,
	)
	return err
}
