// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_sync_history.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedSyncHistory = `-- name: CountFeedSyncHistory :one
SELECT count(*) FROM feed_sync_history WHERE feed_source_id = $1
`

func (q *Queries) CountFeedSyncHistory(ctx context.Context, feedSourceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedSyncHistory, feedSourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedSyncHistory = `-- name: CreateFeedSyncHistory :one
INSERT INTO feed_sync_history (feed_source_id, started_at, finished_at, duration_ms,
    new_entries, updated_entries, total_scanned, error_count, status, error_message, log_output)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, feed_source_id, started_at, finished_at, duration_ms, new_entries, updated_entries, total_scanned, error_count, status, error_message, log_output, created_at
`

type CreateFeedSyncHistoryParams struct {
	FeedSourceID   pgtype.UUID        `json:"feed_source_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
	NewEntries     int32              `json:"new_entries"`
	UpdatedEntries int32              `json:"updated_entries"`
	TotalScanned   int32              `json:"total_scanned"`
	ErrorCount     int32              `json:"error_count"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	LogOutput      pgtype.Text        `json:"log_output"`
}

func (q *Queries) CreateFeedSyncHistory(ctx context.Context, arg CreateFeedSyncHistoryParams) (FeedSyncHistory, error) {
	row := q.db.QueryRow(ctx, createFeedSyncHistory,
		arg.FeedSourceID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.NewEntries,
		arg.UpdatedEntries,
		arg.TotalScanned,
		arg.ErrorCount,
		arg.Status,
		arg.ErrorMessage,
		arg.LogOutput,
	)
	var i FeedSyncHistory
	err := row.Scan(
		&i.ID,
		&i.FeedSourceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.NewEntries,
		&i.UpdatedEntries,
		&i.TotalScanned,
		&i.ErrorCount,
		&i.Status,
		&i.ErrorMessage,
		&i.LogOutput,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedErrorRate = `-- name: GetFeedErrorRate :one
SELECT
    count(*) FILTER (WHERE status = 'failed') AS failed_count,
    count(*) AS total_count
FROM feed_sync_history
WHERE feed_source_id = $1 AND started_at > now() - interval '30 days'
`

type GetFeedErrorRateRow struct {
	FailedCount int64 `json:"failed_count"`
	TotalCount  int64 `json:"total_count"`
}

func (q *Queries) GetFeedErrorRate(ctx context.Context, feedSourceID pgtype.UUID) (GetFeedErrorRateRow, error) {
	row := q.db.QueryRow(ctx, getFeedErrorRate, feedSourceID)
	var i GetFeedErrorRateRow
	err := row.Scan(&i.FailedCount, &i.TotalCount)
	return i, err
}

const getFeedNewThisWeek = `-- name: GetFeedNewThisWeek :one
SELECT count(*)::bigint AS new_this_week
FROM patch_catalog
WHERE feed_source_id = $1
  AND created_at > now() - interval '7 days'
  AND deleted_at IS NULL
`

func (q *Queries) GetFeedNewThisWeek(ctx context.Context, feedSourceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFeedNewThisWeek, feedSourceID)
	var new_this_week int64
	err := row.Scan(&new_this_week)
	return new_this_week, err
}

const listFeedSyncHistory = `-- name: ListFeedSyncHistory :many
SELECT id, feed_source_id, started_at, finished_at, duration_ms,
       new_entries, updated_entries, total_scanned, error_count,
       status, error_message, log_output, created_at
FROM feed_sync_history
WHERE feed_source_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListFeedSyncHistoryParams struct {
	FeedSourceID pgtype.UUID `json:"feed_source_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListFeedSyncHistory(ctx context.Context, arg ListFeedSyncHistoryParams) ([]FeedSyncHistory, error) {
	rows, err := q.db.Query(ctx, listFeedSyncHistory, arg.FeedSourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSyncHistory{}
	for rows.Next() {
		var i FeedSyncHistory
		if err := rows.Scan(
			&i.ID,
			&i.FeedSourceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.NewEntries,
			&i.UpdatedEntries,
			&i.TotalScanned,
			&i.ErrorCount,
			&i.Status,
			&i.ErrorMessage,
			&i.LogOutput,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFeedSyncStatus = `-- name: ListRecentFeedSyncStatus :many
SELECT status, started_at
FROM feed_sync_history
WHERE feed_source_id = $1
ORDER BY started_at DESC
LIMIT 30
`

type ListRecentFeedSyncStatusRow struct {
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ListRecentFeedSyncStatus(ctx context.Context, feedSourceID pgtype.UUID) ([]ListRecentFeedSyncStatusRow, error) {
	rows, err := q.db.Query(ctx, listRecentFeedSyncStatus, feedSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentFeedSyncStatusRow{}
	for rows.Next() {
		var i ListRecentFeedSyncStatusRow
		if err := rows.Scan(&i.Status, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
