// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hub_config.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHubConfig = `-- name: DeleteHubConfig :exec
DELETE FROM hub_config
WHERE tenant_id = $1 AND key = $2
`

type DeleteHubConfigParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

func (q *Queries) DeleteHubConfig(ctx context.Context, arg DeleteHubConfigParams) error {
	_, err := q.db.Exec(ctx, deleteHubConfig, arg.TenantID, arg.Key)
	return err
}

const getHubConfig = `-- name: GetHubConfig :one
SELECT id, tenant_id, key, value, updated_by, created_at, updated_at FROM hub_config
WHERE tenant_id = $1 AND key = $2
`

type GetHubConfigParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

func (q *Queries) GetHubConfig(ctx context.Context, arg GetHubConfigParams) (HubConfig, error) {
	row := q.db.QueryRow(ctx, getHubConfig, arg.TenantID, arg.Key)
	var i HubConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHubConfigByTenant = `-- name: ListHubConfigByTenant :many
SELECT id, tenant_id, key, value, updated_by, created_at, updated_at FROM hub_config
WHERE tenant_id = $1
ORDER BY key
LIMIT 100
`

func (q *Queries) ListHubConfigByTenant(ctx context.Context, tenantID pgtype.UUID) ([]HubConfig, error) {
	rows, err := q.db.Query(ctx, listHubConfigByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubConfig{}
	for rows.Next() {
		var i HubConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Key,
			&i.Value,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHubConfig = `-- name: UpsertHubConfig :one
INSERT INTO hub_config (tenant_id, key, value, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING id, tenant_id, key, value, updated_by, created_at, updated_at
`

type UpsertHubConfigParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertHubConfig(ctx context.Context, arg UpsertHubConfigParams) (HubConfig, error) {
	row := q.db.QueryRow(ctx, upsertHubConfig,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.UpdatedBy,
	)
	var i HubConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
