// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: licenses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignLicenseToClient = `-- name: AssignLicenseToClient :one
UPDATE licenses
SET client_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, client_id, license_key, tier, max_endpoints, issued_at, expires_at, revoked_at, customer_name, customer_email, notes, created_at, updated_at, organization_id
`

type AssignLicenseToClientParams struct {
	ID       pgtype.UUID `json:"id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) AssignLicenseToClient(ctx context.Context, arg AssignLicenseToClientParams) (License, error) {
	row := q.db.QueryRow(ctx, assignLicenseToClient, arg.ID, arg.ClientID)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.LicenseKey,
		&i.Tier,
		&i.MaxEndpoints,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const countLicenses = `-- name: CountLicenses :one
SELECT count(*) FROM licenses
WHERE ($1::text IS NULL OR tier = $1)
  AND ($2::text IS NULL
       OR ($2 = 'active' AND revoked_at IS NULL AND expires_at > now())
       OR ($2 = 'expired' AND revoked_at IS NULL AND expires_at <= now())
       OR ($2 = 'revoked' AND revoked_at IS NOT NULL))
`

type CountLicensesParams struct {
	Tier         pgtype.Text `json:"tier"`
	StatusFilter pgtype.Text `json:"status_filter"`
}

func (q *Queries) CountLicenses(ctx context.Context, arg CountLicensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLicenses, arg.Tier, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLicense = `-- name: CreateLicense :one
INSERT INTO licenses (tenant_id, license_key, tier, max_endpoints, issued_at, expires_at, customer_name, customer_email, client_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, client_id, license_key, tier, max_endpoints, issued_at, expires_at, revoked_at, customer_name, customer_email, notes, created_at, updated_at, organization_id
`

type CreateLicenseParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	LicenseKey    string             `json:"license_key"`
	Tier          string             `json:"tier"`
	MaxEndpoints  int32              `json:"max_endpoints"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CustomerName  string             `json:"customer_name"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	ClientID      pgtype.UUID        `json:"client_id"`
	Notes         pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateLicense(ctx context.Context, arg CreateLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, createLicense,
		arg.TenantID,
		arg.LicenseKey,
		arg.Tier,
		arg.MaxEndpoints,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.ClientID,
		arg.Notes,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.LicenseKey,
		&i.Tier,
		&i.MaxEndpoints,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getLicenseByID = `-- name: GetLicenseByID :one
SELECT l.id, l.tenant_id, l.client_id, l.license_key, l.tier, l.max_endpoints, l.issued_at, l.expires_at, l.revoked_at, l.customer_name, l.customer_email, l.notes, l.created_at, l.updated_at, l.organization_id, c.hostname AS client_hostname, c.endpoint_count AS client_endpoint_count
FROM licenses l
LEFT JOIN clients c ON c.id = l.client_id
WHERE l.id = $1
`

type GetLicenseByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ClientID            pgtype.UUID        `json:"client_id"`
	LicenseKey          string             `json:"license_key"`
	Tier                string             `json:"tier"`
	MaxEndpoints        int32              `json:"max_endpoints"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CustomerName        string             `json:"customer_name"`
	CustomerEmail       pgtype.Text        `json:"customer_email"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	ClientHostname      pgtype.Text        `json:"client_hostname"`
	ClientEndpointCount pgtype.Int4        `json:"client_endpoint_count"`
}

func (q *Queries) GetLicenseByID(ctx context.Context, id pgtype.UUID) (GetLicenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getLicenseByID, id)
	var i GetLicenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.LicenseKey,
		&i.Tier,
		&i.MaxEndpoints,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.ClientHostname,
		&i.ClientEndpointCount,
	)
	return i, err
}

const listLicenses = `-- name: ListLicenses :many
SELECT l.id, l.tenant_id, l.client_id, l.license_key, l.tier, l.max_endpoints, l.issued_at, l.expires_at, l.revoked_at, l.customer_name, l.customer_email, l.notes, l.created_at, l.updated_at, l.organization_id, c.hostname AS client_hostname, c.endpoint_count AS client_endpoint_count
FROM licenses l
LEFT JOIN clients c ON c.id = l.client_id
WHERE ($1::text IS NULL OR l.tier = $1)
  AND ($2::text IS NULL
       OR ($2 = 'active' AND l.revoked_at IS NULL AND l.expires_at > now())
       OR ($2 = 'expired' AND l.revoked_at IS NULL AND l.expires_at <= now())
       OR ($2 = 'revoked' AND l.revoked_at IS NOT NULL))
ORDER BY l.created_at DESC
LIMIT $4 OFFSET $3
`

type ListLicensesParams struct {
	Tier         pgtype.Text `json:"tier"`
	StatusFilter pgtype.Text `json:"status_filter"`
	QueryOffset  int32       `json:"query_offset"`
	QueryLimit   int32       `json:"query_limit"`
}

type ListLicensesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ClientID            pgtype.UUID        `json:"client_id"`
	LicenseKey          string             `json:"license_key"`
	Tier                string             `json:"tier"`
	MaxEndpoints        int32              `json:"max_endpoints"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CustomerName        string             `json:"customer_name"`
	CustomerEmail       pgtype.Text        `json:"customer_email"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	ClientHostname      pgtype.Text        `json:"client_hostname"`
	ClientEndpointCount pgtype.Int4        `json:"client_endpoint_count"`
}

func (q *Queries) ListLicenses(ctx context.Context, arg ListLicensesParams) ([]ListLicensesRow, error) {
	rows, err := q.db.Query(ctx, listLicenses,
		arg.Tier,
		arg.StatusFilter,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLicensesRow{}
	for rows.Next() {
		var i ListLicensesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.LicenseKey,
			&i.Tier,
			&i.MaxEndpoints,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.ClientHostname,
			&i.ClientEndpointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewLicense = `-- name: RenewLicense :one
UPDATE licenses
SET tier = COALESCE($1::text, tier),
    max_endpoints = COALESCE($2::int, max_endpoints),
    expires_at = $3,
    revoked_at = NULL,
    updated_at = now()
WHERE id = $4
RETURNING id, tenant_id, client_id, license_key, tier, max_endpoints, issued_at, expires_at, revoked_at, customer_name, customer_email, notes, created_at, updated_at, organization_id
`

type RenewLicenseParams struct {
	NewTier         pgtype.Text        `json:"new_tier"`
	NewMaxEndpoints pgtype.Int4        `json:"new_max_endpoints"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) RenewLicense(ctx context.Context, arg RenewLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, renewLicense,
		arg.NewTier,
		arg.NewMaxEndpoints,
		arg.ExpiresAt,
		arg.ID,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.LicenseKey,
		&i.Tier,
		&i.MaxEndpoints,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const revokeLicense = `-- name: RevokeLicense :one
UPDATE licenses
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, tenant_id, client_id, license_key, tier, max_endpoints, issued_at, expires_at, revoked_at, customer_name, customer_email, notes, created_at, updated_at, organization_id
`

func (q *Queries) RevokeLicense(ctx context.Context, id pgtype.UUID) (License, error) {
	row := q.db.QueryRow(ctx, revokeLicense, id)
	var i License
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.LicenseKey,
		&i.Tier,
		&i.MaxEndpoints,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}
