// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package_aliases.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePackageAlias = `-- name: DeletePackageAlias :exec
DELETE FROM package_aliases WHERE id = $1
`

func (q *Queries) DeletePackageAlias(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePackageAlias, id)
	return err
}

const getPackageAlias = `-- name: GetPackageAlias :one
SELECT id, feed_product, os_family, os_distribution, os_package_name, confidence, created_at, updated_at FROM package_aliases
WHERE feed_product = $1 AND os_family = $2 AND os_distribution = $3
`

type GetPackageAliasParams struct {
	FeedProduct    string `json:"feed_product"`
	OsFamily       string `json:"os_family"`
	OsDistribution string `json:"os_distribution"`
}

func (q *Queries) GetPackageAlias(ctx context.Context, arg GetPackageAliasParams) (PackageAlias, error) {
	row := q.db.QueryRow(ctx, getPackageAlias, arg.FeedProduct, arg.OsFamily, arg.OsDistribution)
	var i PackageAlias
	err := row.Scan(
		&i.ID,
		&i.FeedProduct,
		&i.OsFamily,
		&i.OsDistribution,
		&i.OsPackageName,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackageAliases = `-- name: ListPackageAliases :many
SELECT id, feed_product, os_family, os_distribution, os_package_name, confidence, created_at, updated_at FROM package_aliases
ORDER BY feed_product, os_family, os_distribution
LIMIT $1 OFFSET $2
`

type ListPackageAliasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPackageAliases(ctx context.Context, arg ListPackageAliasesParams) ([]PackageAlias, error) {
	rows, err := q.db.Query(ctx, listPackageAliases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageAlias{}
	for rows.Next() {
		var i PackageAlias
		if err := rows.Scan(
			&i.ID,
			&i.FeedProduct,
			&i.OsFamily,
			&i.OsDistribution,
			&i.OsPackageName,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageAliasesByProduct = `-- name: ListPackageAliasesByProduct :many
SELECT id, feed_product, os_family, os_distribution, os_package_name, confidence, created_at, updated_at FROM package_aliases
WHERE feed_product = $1
ORDER BY os_family, os_distribution
LIMIT 1000
`

func (q *Queries) ListPackageAliasesByProduct(ctx context.Context, feedProduct string) ([]PackageAlias, error) {
	rows, err := q.db.Query(ctx, listPackageAliasesByProduct, feedProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageAlias{}
	for rows.Next() {
		var i PackageAlias
		if err := rows.Scan(
			&i.ID,
			&i.FeedProduct,
			&i.OsFamily,
			&i.OsDistribution,
			&i.OsPackageName,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageAliasById = `-- name: UpdatePackageAliasById :one
UPDATE package_aliases
SET feed_product = $2,
    os_family = $3,
    os_distribution = $4,
    os_package_name = $5,
    confidence = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, feed_product, os_family, os_distribution, os_package_name, confidence, created_at, updated_at
`

type UpdatePackageAliasByIdParams struct {
	ID             pgtype.UUID `json:"id"`
	FeedProduct    string      `json:"feed_product"`
	OsFamily       string      `json:"os_family"`
	OsDistribution string      `json:"os_distribution"`
	OsPackageName  string      `json:"os_package_name"`
	Confidence     string      `json:"confidence"`
}

func (q *Queries) UpdatePackageAliasById(ctx context.Context, arg UpdatePackageAliasByIdParams) (PackageAlias, error) {
	row := q.db.QueryRow(ctx, updatePackageAliasById,
		arg.ID,
		arg.FeedProduct,
		arg.OsFamily,
		arg.OsDistribution,
		arg.OsPackageName,
		arg.Confidence,
	)
	var i PackageAlias
	err := row.Scan(
		&i.ID,
		&i.FeedProduct,
		&i.OsFamily,
		&i.OsDistribution,
		&i.OsPackageName,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPackageAlias = `-- name: UpsertPackageAlias :one
INSERT INTO package_aliases (feed_product, os_family, os_distribution, os_package_name, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (feed_product, os_family, os_distribution) DO UPDATE SET
    os_package_name = EXCLUDED.os_package_name,
    confidence = EXCLUDED.confidence,
    updated_at = now()
RETURNING id, feed_product, os_family, os_distribution, os_package_name, confidence, created_at, updated_at
`

type UpsertPackageAliasParams struct {
	FeedProduct    string `json:"feed_product"`
	OsFamily       string `json:"os_family"`
	OsDistribution string `json:"os_distribution"`
	OsPackageName  string `json:"os_package_name"`
	Confidence     string `json:"confidence"`
}

func (q *Queries) UpsertPackageAlias(ctx context.Context, arg UpsertPackageAliasParams) (PackageAlias, error) {
	row := q.db.QueryRow(ctx, upsertPackageAlias,
		arg.FeedProduct,
		arg.OsFamily,
		arg.OsDistribution,
		arg.OsPackageName,
		arg.Confidence,
	)
	var i PackageAlias
	err := row.Scan(
		&i.ID,
		&i.FeedProduct,
		&i.OsFamily,
		&i.OsDistribution,
		&i.OsPackageName,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
