// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patch_catalog_cves.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCVEsForCatalogEntry = `-- name: CountCVEsForCatalogEntry :one
SELECT count(*) FROM patch_catalog_cves WHERE catalog_id = $1
`

func (q *Queries) CountCVEsForCatalogEntry(ctx context.Context, catalogID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCVEsForCatalogEntry, catalogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const linkCatalogCVE = `-- name: LinkCatalogCVE :exec
INSERT INTO patch_catalog_cves (catalog_id, cve_id)
VALUES ($1, $2)
ON CONFLICT (catalog_id, cve_id) DO NOTHING
`

type LinkCatalogCVEParams struct {
	CatalogID pgtype.UUID `json:"catalog_id"`
	CveID     pgtype.UUID `json:"cve_id"`
}

func (q *Queries) LinkCatalogCVE(ctx context.Context, arg LinkCatalogCVEParams) error {
	_, err := q.db.Exec(ctx, linkCatalogCVE, arg.CatalogID, arg.CveID)
	return err
}

const listCVEsForCatalogEntry = `-- name: ListCVEsForCatalogEntry :many
SELECT cf.id, cf.cve_id, cf.severity, cf.description, cf.published_at, cf.source,
       cf.cvss_v3_score, cf.exploit_known, cf.in_kev,
       cf.cvss_v3_vector, cf.attack_vector, cf.cwe_id, cf.cisa_kev_due_date,
       cf.nvd_last_modified, cf.external_references
FROM cve_feeds cf
JOIN patch_catalog_cves pcc ON pcc.cve_id = cf.id
WHERE pcc.catalog_id = $1
ORDER BY cf.severity, cf.cve_id
LIMIT 1000
`

type ListCVEsForCatalogEntryRow struct {
	ID                 pgtype.UUID        `json:"id"`
	CveID              string             `json:"cve_id"`
	Severity           string             `json:"severity"`
	Description        pgtype.Text        `json:"description"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	Source             string             `json:"source"`
	CvssV3Score        pgtype.Numeric     `json:"cvss_v3_score"`
	ExploitKnown       bool               `json:"exploit_known"`
	InKev              bool               `json:"in_kev"`
	CvssV3Vector       pgtype.Text        `json:"cvss_v3_vector"`
	AttackVector       pgtype.Text        `json:"attack_vector"`
	CweID              pgtype.Text        `json:"cwe_id"`
	CisaKevDueDate     pgtype.Date        `json:"cisa_kev_due_date"`
	NvdLastModified    pgtype.Timestamptz `json:"nvd_last_modified"`
	ExternalReferences []byte             `json:"external_references"`
}

func (q *Queries) ListCVEsForCatalogEntry(ctx context.Context, catalogID pgtype.UUID) ([]ListCVEsForCatalogEntryRow, error) {
	rows, err := q.db.Query(ctx, listCVEsForCatalogEntry, catalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCVEsForCatalogEntryRow{}
	for rows.Next() {
		var i ListCVEsForCatalogEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.CveID,
			&i.Severity,
			&i.Description,
			&i.PublishedAt,
			&i.Source,
			&i.CvssV3Score,
			&i.ExploitKnown,
			&i.InKev,
			&i.CvssV3Vector,
			&i.AttackVector,
			&i.CweID,
			&i.CisaKevDueDate,
			&i.NvdLastModified,
			&i.ExternalReferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogCVELinks = `-- name: ListCatalogCVELinks :many
SELECT pcc.catalog_id, cf.cve_id
FROM patch_catalog_cves pcc
JOIN cve_feeds cf ON pcc.cve_id = cf.id
WHERE pcc.catalog_id = ANY($1::uuid[])
ORDER BY pcc.catalog_id, cf.cve_id
`

type ListCatalogCVELinksRow struct {
	CatalogID pgtype.UUID `json:"catalog_id"`
	CveID     string      `json:"cve_id"`
}

func (q *Queries) ListCatalogCVELinks(ctx context.Context, catalogIds []pgtype.UUID) ([]ListCatalogCVELinksRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCVELinks, catalogIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogCVELinksRow{}
	for rows.Next() {
		var i ListCatalogCVELinksRow
		if err := rows.Scan(&i.CatalogID, &i.CveID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAllCatalogCVEs = `-- name: UnlinkAllCatalogCVEs :exec
DELETE FROM patch_catalog_cves WHERE catalog_id = $1
`

func (q *Queries) UnlinkAllCatalogCVEs(ctx context.Context, catalogID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlinkAllCatalogCVEs, catalogID)
	return err
}
