// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patch_catalog.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogEntries = `-- name: CountCatalogEntries :one
SELECT count(*) FROM patch_catalog
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR os_family = $1)
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
`

type CountCatalogEntriesParams struct {
	OsFamily pgtype.Text `json:"os_family"`
	Severity pgtype.Text `json:"severity"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountCatalogEntries(ctx context.Context, arg CountCatalogEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogEntries, arg.OsFamily, arg.Severity, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCatalogEntriesEnriched = `-- name: CountCatalogEntriesEnriched :one
SELECT count(*)
FROM patch_catalog pc
WHERE pc.deleted_at IS NULL
  AND ($1::text IS NULL OR pc.os_family = $1)
  AND ($2::text IS NULL OR pc.severity = $2)
  AND ($3::text IS NULL OR pc.name ILIKE '%' || $3 || '%')
  AND ($4::uuid IS NULL OR pc.feed_source_id = $4)
  AND ($5::text IS NULL
       OR ($5 = '7d' AND pc.release_date > now() - interval '7 days')
       OR ($5 = '30d' AND pc.release_date > now() - interval '30 days')
       OR ($5 = '90d' AND pc.release_date > now() - interval '90 days'))
  AND ($6::text IS NULL
       OR ($6 = 'cve' AND pc.name ILIKE 'CVE-%')
       OR ($6 = 'patch' AND pc.name NOT ILIKE 'CVE-%'))
`

type CountCatalogEntriesEnrichedParams struct {
	OsFamily     pgtype.Text `json:"os_family"`
	Severity     pgtype.Text `json:"severity"`
	Search       pgtype.Text `json:"search"`
	FeedSourceID pgtype.UUID `json:"feed_source_id"`
	DateRange    pgtype.Text `json:"date_range"`
	EntryType    pgtype.Text `json:"entry_type"`
}

func (q *Queries) CountCatalogEntriesEnriched(ctx context.Context, arg CountCatalogEntriesEnrichedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogEntriesEnriched,
		arg.OsFamily,
		arg.Severity,
		arg.Search,
		arg.FeedSourceID,
		arg.DateRange,
		arg.EntryType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCatalogEntry = `-- name: CreateCatalogEntry :one
INSERT INTO patch_catalog (name, vendor, os_family, version, severity, release_date, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args
`

type CreateCatalogEntryParams struct {
	Name        string             `json:"name"`
	Vendor      string             `json:"vendor"`
	OsFamily    string             `json:"os_family"`
	Version     string             `json:"version"`
	Severity    string             `json:"severity"`
	ReleaseDate pgtype.Timestamptz `json:"release_date"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateCatalogEntry(ctx context.Context, arg CreateCatalogEntryParams) (PatchCatalog, error) {
	row := q.db.QueryRow(ctx, createCatalogEntry,
		arg.Name,
		arg.Vendor,
		arg.OsFamily,
		arg.Version,
		arg.Severity,
		arg.ReleaseDate,
		arg.Description,
	)
	var i PatchCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.OsFamily,
		&i.Version,
		&i.Severity,
		&i.ReleaseDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FeedSourceID,
		&i.SourceUrl,
		&i.InstallerType,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.Product,
		&i.OsPackageName,
		&i.SilentArgs,
	)
	return i, err
}

const getCatalogEntryByID = `-- name: GetCatalogEntryByID :one
SELECT id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args FROM patch_catalog WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCatalogEntryByID(ctx context.Context, id pgtype.UUID) (PatchCatalog, error) {
	row := q.db.QueryRow(ctx, getCatalogEntryByID, id)
	var i PatchCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.OsFamily,
		&i.Version,
		&i.Severity,
		&i.ReleaseDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FeedSourceID,
		&i.SourceUrl,
		&i.InstallerType,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.Product,
		&i.OsPackageName,
		&i.SilentArgs,
	)
	return i, err
}

const listCatalogEntries = `-- name: ListCatalogEntries :many
SELECT id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args FROM patch_catalog
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR os_family = $1)
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListCatalogEntriesParams struct {
	OsFamily    pgtype.Text `json:"os_family"`
	Severity    pgtype.Text `json:"severity"`
	Search      pgtype.Text `json:"search"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListCatalogEntries(ctx context.Context, arg ListCatalogEntriesParams) ([]PatchCatalog, error) {
	rows, err := q.db.Query(ctx, listCatalogEntries,
		arg.OsFamily,
		arg.Severity,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatchCatalog{}
	for rows.Next() {
		var i PatchCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Vendor,
			&i.OsFamily,
			&i.Version,
			&i.Severity,
			&i.ReleaseDate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FeedSourceID,
			&i.SourceUrl,
			&i.InstallerType,
			&i.BinaryRef,
			&i.ChecksumSha256,
			&i.Product,
			&i.OsPackageName,
			&i.SilentArgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogEntriesDeletedSince = `-- name: ListCatalogEntriesDeletedSince :many
SELECT id FROM patch_catalog
WHERE deleted_at > $1
LIMIT 10000
`

func (q *Queries) ListCatalogEntriesDeletedSince(ctx context.Context, deletedAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCatalogEntriesDeletedSince, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogEntriesEnriched = `-- name: ListCatalogEntriesEnriched :many
SELECT pc.id, pc.name, pc.vendor, pc.os_family, pc.version, pc.severity, pc.release_date, pc.description, pc.created_at, pc.updated_at, pc.deleted_at, pc.feed_source_id, pc.source_url, pc.installer_type, pc.binary_ref, pc.checksum_sha256, pc.product, pc.os_package_name, pc.silent_args,
       fs.name AS feed_source_name,
       (SELECT count(*) FROM patch_catalog_cves WHERE catalog_id = pc.id) AS cve_count,
       (SELECT count(*) FROM catalog_entry_syncs WHERE catalog_id = pc.id AND status = 'synced') AS synced_count
FROM patch_catalog pc
LEFT JOIN feed_sources fs ON fs.id = pc.feed_source_id
WHERE pc.deleted_at IS NULL
  AND ($1::text IS NULL OR pc.os_family = $1)
  AND ($2::text IS NULL OR pc.severity = $2)
  AND ($3::text IS NULL OR pc.name ILIKE '%' || $3 || '%')
  AND ($4::uuid IS NULL OR pc.feed_source_id = $4)
  AND ($5::text IS NULL
       OR ($5 = '7d' AND pc.release_date > now() - interval '7 days')
       OR ($5 = '30d' AND pc.release_date > now() - interval '30 days')
       OR ($5 = '90d' AND pc.release_date > now() - interval '90 days'))
  AND ($6::text IS NULL
       OR ($6 = 'cve' AND pc.name ILIKE 'CVE-%')
       OR ($6 = 'patch' AND pc.name NOT ILIKE 'CVE-%'))
ORDER BY pc.created_at DESC
LIMIT $8 OFFSET $7
`

type ListCatalogEntriesEnrichedParams struct {
	OsFamily     pgtype.Text `json:"os_family"`
	Severity     pgtype.Text `json:"severity"`
	Search       pgtype.Text `json:"search"`
	FeedSourceID pgtype.UUID `json:"feed_source_id"`
	DateRange    pgtype.Text `json:"date_range"`
	EntryType    pgtype.Text `json:"entry_type"`
	QueryOffset  int32       `json:"query_offset"`
	QueryLimit   int32       `json:"query_limit"`
}

type ListCatalogEntriesEnrichedRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Vendor         string             `json:"vendor"`
	OsFamily       string             `json:"os_family"`
	Version        string             `json:"version"`
	Severity       string             `json:"severity"`
	ReleaseDate    pgtype.Timestamptz `json:"release_date"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	FeedSourceID   pgtype.UUID        `json:"feed_source_id"`
	SourceUrl      string             `json:"source_url"`
	InstallerType  string             `json:"installer_type"`
	BinaryRef      string             `json:"binary_ref"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	Product        string             `json:"product"`
	OsPackageName  string             `json:"os_package_name"`
	SilentArgs     string             `json:"silent_args"`
	FeedSourceName pgtype.Text        `json:"feed_source_name"`
	CveCount       int64              `json:"cve_count"`
	SyncedCount    int64              `json:"synced_count"`
}

func (q *Queries) ListCatalogEntriesEnriched(ctx context.Context, arg ListCatalogEntriesEnrichedParams) ([]ListCatalogEntriesEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listCatalogEntriesEnriched,
		arg.OsFamily,
		arg.Severity,
		arg.Search,
		arg.FeedSourceID,
		arg.DateRange,
		arg.EntryType,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogEntriesEnrichedRow{}
	for rows.Next() {
		var i ListCatalogEntriesEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Vendor,
			&i.OsFamily,
			&i.Version,
			&i.Severity,
			&i.ReleaseDate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FeedSourceID,
			&i.SourceUrl,
			&i.InstallerType,
			&i.BinaryRef,
			&i.ChecksumSha256,
			&i.Product,
			&i.OsPackageName,
			&i.SilentArgs,
			&i.FeedSourceName,
			&i.CveCount,
			&i.SyncedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogEntriesUpdatedSince = `-- name: ListCatalogEntriesUpdatedSince :many
SELECT id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args FROM patch_catalog
WHERE updated_at > $1 AND deleted_at IS NULL
LIMIT 10000
`

func (q *Queries) ListCatalogEntriesUpdatedSince(ctx context.Context, updatedAt pgtype.Timestamptz) ([]PatchCatalog, error) {
	rows, err := q.db.Query(ctx, listCatalogEntriesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatchCatalog{}
	for rows.Next() {
		var i PatchCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Vendor,
			&i.OsFamily,
			&i.Version,
			&i.Severity,
			&i.ReleaseDate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FeedSourceID,
			&i.SourceUrl,
			&i.InstallerType,
			&i.BinaryRef,
			&i.ChecksumSha256,
			&i.Product,
			&i.OsPackageName,
			&i.SilentArgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCatalogEntry = `-- name: SoftDeleteCatalogEntry :exec
UPDATE patch_catalog SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCatalogEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCatalogEntry, id)
	return err
}

const updateCatalogEntry = `-- name: UpdateCatalogEntry :one
UPDATE patch_catalog
SET name = $2, vendor = $3, os_family = $4, version = $5, severity = $6,
    release_date = $7, description = $8, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args
`

type UpdateCatalogEntryParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Vendor      string             `json:"vendor"`
	OsFamily    string             `json:"os_family"`
	Version     string             `json:"version"`
	Severity    string             `json:"severity"`
	ReleaseDate pgtype.Timestamptz `json:"release_date"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) UpdateCatalogEntry(ctx context.Context, arg UpdateCatalogEntryParams) (PatchCatalog, error) {
	row := q.db.QueryRow(ctx, updateCatalogEntry,
		arg.ID,
		arg.Name,
		arg.Vendor,
		arg.OsFamily,
		arg.Version,
		arg.Severity,
		arg.ReleaseDate,
		arg.Description,
	)
	var i PatchCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.OsFamily,
		&i.Version,
		&i.Severity,
		&i.ReleaseDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FeedSourceID,
		&i.SourceUrl,
		&i.InstallerType,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.Product,
		&i.OsPackageName,
		&i.SilentArgs,
	)
	return i, err
}

const updateCatalogEntryBinaryRef = `-- name: UpdateCatalogEntryBinaryRef :exec
UPDATE patch_catalog
SET binary_ref = $2, checksum_sha256 = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCatalogEntryBinaryRefParams struct {
	ID             pgtype.UUID `json:"id"`
	BinaryRef      string      `json:"binary_ref"`
	ChecksumSha256 string      `json:"checksum_sha256"`
}

func (q *Queries) UpdateCatalogEntryBinaryRef(ctx context.Context, arg UpdateCatalogEntryBinaryRefParams) error {
	_, err := q.db.Exec(ctx, updateCatalogEntryBinaryRef, arg.ID, arg.BinaryRef, arg.ChecksumSha256)
	return err
}

const upsertCatalogEntryFromFeed = `-- name: UpsertCatalogEntryFromFeed :one
INSERT INTO patch_catalog (name, vendor, os_family, version, severity, release_date, description, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (feed_source_id, vendor, name, version)
    WHERE feed_source_id IS NOT NULL AND deleted_at IS NULL
DO UPDATE SET
    severity = EXCLUDED.severity,
    release_date = EXCLUDED.release_date,
    description = EXCLUDED.description,
    os_family = EXCLUDED.os_family,
    source_url = EXCLUDED.source_url,
    installer_type = EXCLUDED.installer_type,
    binary_ref = EXCLUDED.binary_ref,
    checksum_sha256 = EXCLUDED.checksum_sha256,
    product = EXCLUDED.product,
    os_package_name = EXCLUDED.os_package_name,
    silent_args = EXCLUDED.silent_args,
    updated_at = now()
RETURNING id, name, vendor, os_family, version, severity, release_date, description, created_at, updated_at, deleted_at, feed_source_id, source_url, installer_type, binary_ref, checksum_sha256, product, os_package_name, silent_args
`

type UpsertCatalogEntryFromFeedParams struct {
	Name           string             `json:"name"`
	Vendor         string             `json:"vendor"`
	OsFamily       string             `json:"os_family"`
	Version        string             `json:"version"`
	Severity       string             `json:"severity"`
	ReleaseDate    pgtype.Timestamptz `json:"release_date"`
	Description    pgtype.Text        `json:"description"`
	FeedSourceID   pgtype.UUID        `json:"feed_source_id"`
	SourceUrl      string             `json:"source_url"`
	InstallerType  string             `json:"installer_type"`
	BinaryRef      string             `json:"binary_ref"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	Product        string             `json:"product"`
	OsPackageName  string             `json:"os_package_name"`
	SilentArgs     string             `json:"silent_args"`
}

func (q *Queries) UpsertCatalogEntryFromFeed(ctx context.Context, arg UpsertCatalogEntryFromFeedParams) (PatchCatalog, error) {
	row := q.db.QueryRow(ctx, upsertCatalogEntryFromFeed,
		arg.Name,
		arg.Vendor,
		arg.OsFamily,
		arg.Version,
		arg.Severity,
		arg.ReleaseDate,
		arg.Description,
		arg.FeedSourceID,
		arg.SourceUrl,
		arg.InstallerType,
		arg.BinaryRef,
		arg.ChecksumSha256,
		arg.Product,
		arg.OsPackageName,
		arg.SilentArgs,
	)
	var i PatchCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Vendor,
		&i.OsFamily,
		&i.Version,
		&i.Severity,
		&i.ReleaseDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FeedSourceID,
		&i.SourceUrl,
		&i.InstallerType,
		&i.BinaryRef,
		&i.ChecksumSha256,
		&i.Product,
		&i.OsPackageName,
		&i.SilentArgs,
	)
	return i, err
}
