/**
 * Dev-only mock data for all API endpoints.
 * Used by the Vite devMockPlugin when VITE_MOCK=true.
 */

const TENANT_ID = '00000000-0000-0000-0000-000000000001';
const ago = (mins: number) => new Date(Date.now() - mins * 60_000).toISOString();

// ─── Endpoints ────────────────────────────────────────────────────────────────

export const mockEndpoints = {
  data: [
    {
      id: 'ep-001',
      tenant_id: TENANT_ID,
      hostname: 'prod-web-01',
      os_family: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      agent_version: '1.4.2',
      status: 'active',
      last_seen: ago(2),
      created_at: ago(20160),
      updated_at: ago(2),
      package_count: 312,
      last_scan: ago(30),
      vulnerable_cve_count: 7,
    },
    {
      id: 'ep-002',
      tenant_id: TENANT_ID,
      hostname: 'prod-web-02',
      os_family: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      agent_version: '1.4.2',
      status: 'active',
      last_seen: ago(5),
      created_at: ago(20160),
      updated_at: ago(5),
      package_count: 308,
      last_scan: ago(45),
      vulnerable_cve_count: 7,
    },
    {
      id: 'ep-003',
      tenant_id: TENANT_ID,
      hostname: 'prod-db-01',
      os_family: 'linux',
      os_version: 'RHEL 9.2',
      agent_version: '1.4.1',
      status: 'active',
      last_seen: ago(1),
      created_at: ago(15000),
      updated_at: ago(1),
      package_count: 287,
      last_scan: ago(20),
      vulnerable_cve_count: 3,
    },
    {
      id: 'ep-004',
      tenant_id: TENANT_ID,
      hostname: 'prod-db-02',
      os_family: 'linux',
      os_version: 'RHEL 9.2',
      agent_version: '1.4.1',
      status: 'active',
      last_seen: ago(3),
      created_at: ago(15000),
      updated_at: ago(3),
      package_count: 291,
      last_scan: ago(25),
      vulnerable_cve_count: 3,
    },
    {
      id: 'ep-005',
      tenant_id: TENANT_ID,
      hostname: 'dev-build-01',
      os_family: 'linux',
      os_version: 'Debian 12',
      agent_version: '1.4.2',
      status: 'active',
      last_seen: ago(10),
      created_at: ago(5000),
      updated_at: ago(10),
      package_count: 445,
      last_scan: ago(60),
      vulnerable_cve_count: 14,
    },
    {
      id: 'ep-006',
      tenant_id: TENANT_ID,
      hostname: 'staging-app-01',
      os_family: 'linux',
      os_version: 'Ubuntu 20.04 LTS',
      agent_version: '1.3.9',
      status: 'inactive',
      last_seen: ago(2880),
      created_at: ago(8000),
      updated_at: ago(2880),
      package_count: 198,
      last_scan: ago(2880),
      vulnerable_cve_count: 21,
    },
    {
      id: 'ep-007',
      tenant_id: TENANT_ID,
      hostname: 'prod-cache-01',
      os_family: 'linux',
      os_version: 'Ubuntu 22.04 LTS',
      agent_version: '1.4.2',
      status: 'active',
      last_seen: ago(1),
      created_at: ago(7000),
      updated_at: ago(1),
      package_count: 156,
      last_scan: ago(15),
      vulnerable_cve_count: 2,
    },
    {
      id: 'ep-008',
      tenant_id: TENANT_ID,
      hostname: 'win-dev-01',
      os_family: 'windows',
      os_version: 'Windows Server 2022',
      agent_version: '1.4.0',
      status: 'active',
      last_seen: ago(8),
      created_at: ago(4000),
      updated_at: ago(8),
      package_count: 67,
      last_scan: ago(120),
      vulnerable_cve_count: 5,
    },
  ],
  next_cursor: null,
  total_count: 8,
};

export const mockEndpoint = (id: string) =>
  mockEndpoints.data.find((e) => e.id === id) ?? mockEndpoints.data[0];

export const mockEndpointPackages = (id: string) => ({
  data: [
    {
      id: `pkg-${id}-1`,
      package_name: 'openssl',
      version: '3.0.2-0ubuntu1.14',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-2`,
      package_name: 'openssh-server',
      version: '1:8.9p1-3ubuntu0.6',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-3`,
      package_name: 'curl',
      version: '7.81.0-1ubuntu1.15',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-4`,
      package_name: 'nginx',
      version: '1.18.0-6ubuntu14.4',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-5`,
      package_name: 'python3',
      version: '3.10.6-1~22.04',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-6`,
      package_name: 'git',
      version: '1:2.34.1-1ubuntu1.10',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-7`,
      package_name: 'libssl3',
      version: '3.0.2-0ubuntu1.14',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
    {
      id: `pkg-${id}-8`,
      package_name: 'systemd',
      version: '249.11-0ubuntu3.12',
      arch: 'amd64',
      source: 'apt',
      release: null,
    },
  ],
  total_count: 312,
});

// ─── Groups ───────────────────────────────────────────────────────────────────

export const mockGroups = {
  data: [
    {
      id: 'grp-001',
      tenant_id: TENANT_ID,
      name: 'Production Web',
      description: 'All production web servers',
      endpoint_count: 2,
      created_at: ago(20000),
      updated_at: ago(500),
    },
    {
      id: 'grp-002',
      tenant_id: TENANT_ID,
      name: 'Production Database',
      description: 'PostgreSQL and cache nodes',
      endpoint_count: 3,
      created_at: ago(18000),
      updated_at: ago(300),
    },
    {
      id: 'grp-003',
      tenant_id: TENANT_ID,
      name: 'Development',
      description: 'Development and build machines',
      endpoint_count: 2,
      created_at: ago(10000),
      updated_at: ago(1440),
    },
    {
      id: 'grp-004',
      tenant_id: TENANT_ID,
      name: 'Staging',
      description: 'Staging environment',
      endpoint_count: 1,
      created_at: ago(8000),
      updated_at: ago(2880),
    },
  ],
  next_cursor: null,
  total_count: 4,
};

// ─── Patches ─────────────────────────────────────────────────────────────────

export const mockPatches = {
  data: [
    {
      id: 'pat-001',
      tenant_id: TENANT_ID,
      name: 'openssl',
      version: '3.0.11',
      severity: 'critical',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'OpenSSL security update fixing heap buffer overflow in RSA implementation',
      cve_count: 3,
      affected_endpoint_count: 6,
      created_at: ago(1440),
      updated_at: ago(1440),
    },
    {
      id: 'pat-002',
      tenant_id: TENANT_ID,
      name: 'openssh-server',
      version: '9.5p1',
      severity: 'high',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'OpenSSH server update addressing remote code execution vulnerability',
      cve_count: 2,
      affected_endpoint_count: 5,
      created_at: ago(2880),
      updated_at: ago(2880),
    },
    {
      id: 'pat-003',
      tenant_id: TENANT_ID,
      name: 'curl',
      version: '8.4.0',
      severity: 'high',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'curl security update fixing cookie injection and SOCKS5 heap overflow',
      cve_count: 2,
      affected_endpoint_count: 8,
      created_at: ago(4320),
      updated_at: ago(4320),
    },
    {
      id: 'pat-004',
      tenant_id: TENANT_ID,
      name: 'nginx',
      version: '1.24.0',
      severity: 'medium',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'nginx HTTP server security and stability update',
      cve_count: 1,
      affected_endpoint_count: 4,
      created_at: ago(5760),
      updated_at: ago(5760),
    },
    {
      id: 'pat-005',
      tenant_id: TENANT_ID,
      name: 'python3',
      version: '3.10.12',
      severity: 'medium',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'Python runtime security fixes for path traversal and regex DoS',
      cve_count: 2,
      affected_endpoint_count: 7,
      created_at: ago(7200),
      updated_at: ago(7200),
    },
    {
      id: 'pat-006',
      tenant_id: TENANT_ID,
      name: 'linux-kernel',
      version: '6.2.0-39',
      severity: 'critical',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'Linux kernel privilege escalation and remote code execution patches',
      cve_count: 5,
      affected_endpoint_count: 6,
      created_at: ago(720),
      updated_at: ago(720),
    },
    {
      id: 'pat-007',
      tenant_id: TENANT_ID,
      name: 'glibc',
      version: '2.37-3',
      severity: 'high',
      os_family: 'linux',
      os_distribution: 'debian',
      status: 'available',
      description: 'GNU C Library buffer overflow in nscd and tunables',
      cve_count: 2,
      affected_endpoint_count: 1,
      created_at: ago(3600),
      updated_at: ago(3600),
    },
    {
      id: 'pat-008',
      tenant_id: TENANT_ID,
      name: 'systemd',
      version: '253.6',
      severity: 'low',
      os_family: 'linux',
      os_distribution: 'ubuntu',
      status: 'available',
      description: 'systemd stability and minor security improvements',
      cve_count: 1,
      affected_endpoint_count: 6,
      created_at: ago(10000),
      updated_at: ago(10000),
    },
  ],
  next_cursor: null,
  total_count: 8,
};

export const mockPatchDetail = (id: string) => {
  const patch = mockPatches.data.find((p) => p.id === id) ?? mockPatches.data[0];
  return {
    ...patch,
    file_size: 2_450_000,
    package_url: `https://archive.ubuntu.com/pool/${patch.name}_${patch.version}_amd64.deb`,
    checksum_sha256: 'a1b2c3d4e5f6789012345678901234567890abcdefabcdefabcdefabcdef1234',
    source_repo: 'Ubuntu Main',
    cves: [
      { id: 'cve-link-001', cve_id: 'CVE-2023-44487', cvss_v3_score: 7.5, severity: 'high' },
      { id: 'cve-link-002', cve_id: 'CVE-2023-5363', cvss_v3_score: 9.1, severity: 'critical' },
    ],
    remediation: {
      endpoints_affected: 6,
      endpoints_patched: 1,
      endpoints_pending: 4,
      endpoints_failed: 1,
    },
    affected_endpoints: {
      count: 6,
      items: mockEndpoints.data
        .slice(0, 3)
        .map((e) => ({ endpoint_id: e.id, hostname: e.hostname, status: 'pending' })),
      has_more: true,
    },
  };
};

// ─── CVEs ─────────────────────────────────────────────────────────────────────

export const mockCVEs = {
  data: [
    {
      id: 'cve-001',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-44487',
      severity: 'high',
      description:
        'HTTP/2 Rapid Reset Attack — allows remote attackers to cause denial of service via stream cancellation.',
      published_at: ago(14400),
      created_at: ago(14400),
      updated_at: ago(1440),
      cvss_v3_score: 7.5,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H',
      cisa_kev_due_date: ago(-20160),
      exploit_available: true,
      nvd_last_modified: ago(2880),
      affected_endpoint_count: 5,
      patch_available: true,
    },
    {
      id: 'cve-002',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-5363',
      severity: 'critical',
      description:
        'OpenSSL AES-SIV implementation incorrectly handles empty associated data entries, leading to data integrity issues.',
      published_at: ago(10080),
      created_at: ago(10080),
      updated_at: ago(720),
      cvss_v3_score: 9.1,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
      cisa_kev_due_date: null,
      exploit_available: false,
      nvd_last_modified: ago(1440),
      affected_endpoint_count: 6,
      patch_available: true,
    },
    {
      id: 'cve-003',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-38408',
      severity: 'critical',
      description: 'OpenSSH ssh-agent remote code execution via maliciously crafted extension.',
      published_at: ago(20000),
      created_at: ago(20000),
      updated_at: ago(5000),
      cvss_v3_score: 9.8,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      cisa_kev_due_date: ago(-10080),
      exploit_available: true,
      nvd_last_modified: ago(5000),
      affected_endpoint_count: 5,
      patch_available: true,
    },
    {
      id: 'cve-004',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-38545',
      severity: 'critical',
      description:
        'curl SOCKS5 heap-based buffer overflow when server requests extremely long hostname.',
      published_at: ago(8640),
      created_at: ago(8640),
      updated_at: ago(1440),
      cvss_v3_score: 9.8,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      cisa_kev_due_date: null,
      exploit_available: true,
      nvd_last_modified: ago(2880),
      affected_endpoint_count: 8,
      patch_available: true,
    },
    {
      id: 'cve-005',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-4863',
      severity: 'critical',
      description:
        'WebP heap buffer overflow in libwebp allows remote code execution via crafted WebP file.',
      published_at: ago(17280),
      created_at: ago(17280),
      updated_at: ago(4320),
      cvss_v3_score: 8.8,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
      cisa_kev_due_date: ago(-7200),
      exploit_available: true,
      nvd_last_modified: ago(4320),
      affected_endpoint_count: 3,
      patch_available: true,
    },
    {
      id: 'cve-006',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-4911',
      severity: 'high',
      description:
        'glibc Looney Tunables: local privilege escalation via buffer overflow in GNU C Library dynamic loader.',
      published_at: ago(21600),
      created_at: ago(21600),
      updated_at: ago(5760),
      cvss_v3_score: 7.8,
      cvss_v3_vector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
      cisa_kev_due_date: null,
      exploit_available: true,
      nvd_last_modified: ago(5760),
      affected_endpoint_count: 1,
      patch_available: true,
    },
    {
      id: 'cve-007',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-32629',
      severity: 'high',
      description: 'Ubuntu kernel overlayfs privilege escalation vulnerability.',
      published_at: ago(25000),
      created_at: ago(25000),
      updated_at: ago(8000),
      cvss_v3_score: 7.8,
      cvss_v3_vector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',
      cisa_kev_due_date: null,
      exploit_available: false,
      nvd_last_modified: ago(8000),
      affected_endpoint_count: 6,
      patch_available: false,
    },
    {
      id: 'cve-008',
      tenant_id: TENANT_ID,
      cve_id: 'CVE-2023-2650',
      severity: 'medium',
      description:
        'OpenSSL denial of service via excessive time parsing specially crafted ASN.1 object identifiers.',
      published_at: ago(30000),
      created_at: ago(30000),
      updated_at: ago(10000),
      cvss_v3_score: 6.5,
      cvss_v3_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H',
      cisa_kev_due_date: null,
      exploit_available: false,
      nvd_last_modified: ago(10000),
      affected_endpoint_count: 6,
      patch_available: true,
    },
  ],
  next_cursor: null,
  total_count: 8,
};

export const mockCVEDetail = (id: string) => {
  const cve = mockCVEs.data.find((c) => c.id === id || c.cve_id === id) ?? mockCVEs.data[0];
  return {
    ...cve,
    affected_endpoints: {
      count: cve.affected_endpoint_count,
      items: mockEndpoints.data.slice(0, cve.affected_endpoint_count).map((e) => ({
        endpoint_id: e.id,
        hostname: e.hostname,
        os_family: e.os_family,
        status: 'affected',
      })),
      has_more: false,
    },
    patches: cve.patch_available
      ? [{ id: 'pat-001', name: 'openssl', version: '3.0.11', severity: cve.severity }]
      : [],
  };
};

// ─── Policies ─────────────────────────────────────────────────────────────────

export const mockPolicies = {
  data: [
    {
      id: 'pol-001',
      tenant_id: TENANT_ID,
      name: 'Critical Security Patches',
      description: 'Auto-deploy all critical severity patches to production',
      selection_mode: 'by_severity',
      min_severity: 'critical',
      enabled: true,
      schedule_type: 'recurring',
      cron_expression: '0 2 * * 0',
      target_selector: { eq: { key: 'env', value: 'prod' } },
      created_at: ago(10000),
      updated_at: ago(500),
    },
    {
      id: 'pol-002',
      tenant_id: TENANT_ID,
      name: 'Weekly Web Server Updates',
      description: 'Weekly patch cycle for all web servers',
      selection_mode: 'all_available',
      min_severity: 'medium',
      enabled: true,
      schedule_type: 'recurring',
      cron_expression: '0 3 * * 6',
      target_selector: { eq: { key: 'role', value: 'web' } },
      created_at: ago(8000),
      updated_at: ago(1440),
    },
    {
      id: 'pol-003',
      tenant_id: TENANT_ID,
      name: 'Dev Environment Full Update',
      description: 'Apply all available patches to dev machines',
      selection_mode: 'all_available',
      min_severity: 'low',
      enabled: true,
      schedule_type: 'manual',
      cron_expression: null,
      target_selector: { eq: { key: 'env', value: 'dev' } },
      created_at: ago(5000),
      updated_at: ago(2880),
    },
    {
      id: 'pol-004',
      tenant_id: TENANT_ID,
      name: 'OpenSSL CVE Response',
      description: 'Emergency response for OpenSSL CVEs',
      selection_mode: 'by_cve_list',
      cve_ids: ['CVE-2023-5363', 'CVE-2023-2650'],
      enabled: false,
      schedule_type: 'manual',
      cron_expression: null,
      target_selector: { exists: { key: 'env' } },
      created_at: ago(2000),
      updated_at: ago(200),
    },
  ],
  next_cursor: null,
  total_count: 4,
};

export const mockPolicyDetail = (id: string) =>
  mockPolicies.data.find((p) => p.id === id) ?? mockPolicies.data[0];

// ─── Deployments ──────────────────────────────────────────────────────────────

export const mockDeployments = {
  data: [
    {
      id: 'dep-001aabbcc',
      tenant_id: TENANT_ID,
      policy_id: 'pol-001',
      status: 'completed',
      target_count: 6,
      completed_count: 6,
      success_count: 5,
      failed_count: 1,
      created_at: ago(720),
      updated_at: ago(680),
      started_at: ago(715),
    },
    {
      id: 'dep-002ddeeff',
      tenant_id: TENANT_ID,
      policy_id: 'pol-002',
      status: 'running',
      target_count: 2,
      completed_count: 1,
      success_count: 1,
      failed_count: 0,
      created_at: ago(30),
      updated_at: ago(5),
      started_at: ago(28),
    },
    {
      id: 'dep-003gghhii',
      tenant_id: TENANT_ID,
      policy_id: 'pol-003',
      status: 'failed',
      target_count: 2,
      completed_count: 2,
      success_count: 1,
      failed_count: 1,
      created_at: ago(4320),
      updated_at: ago(4290),
      started_at: ago(4318),
    },
    {
      id: 'dep-004jjkkll',
      tenant_id: TENANT_ID,
      policy_id: 'pol-001',
      status: 'completed',
      target_count: 6,
      completed_count: 6,
      success_count: 6,
      failed_count: 0,
      created_at: ago(10080),
      updated_at: ago(10000),
      started_at: ago(10078),
    },
    {
      id: 'dep-005mmnnoo',
      tenant_id: TENANT_ID,
      policy_id: 'pol-002',
      status: 'cancelled',
      target_count: 2,
      completed_count: 1,
      success_count: 1,
      failed_count: 0,
      created_at: ago(20160),
      updated_at: ago(20100),
      started_at: ago(20158),
    },
  ],
  next_cursor: null,
  total_count: 5,
};

export const mockDeploymentDetail = (id: string) => {
  const dep = mockDeployments.data.find((d) => d.id === id) ?? mockDeployments.data[0];
  return {
    ...dep,
    targets: mockEndpoints.data.slice(0, dep.target_count).map((e, i) => ({
      id: `tgt-${dep.id}-${i}`,
      deployment_id: dep.id,
      endpoint_id: e.id,
      hostname: e.hostname,
      patch_id: 'pat-001',
      patch_name: 'openssl',
      status: i < dep.success_count ? 'success' : i < dep.completed_count ? 'failed' : 'pending',
      error_message:
        i === dep.success_count && dep.failed_count > 0
          ? 'Package manager lock timeout after 300s'
          : null,
      started_at: dep.started_at,
      completed_at: dep.status === 'running' && i >= dep.completed_count ? null : dep.updated_at,
      output:
        i < dep.success_count
          ? 'Reading package lists...\nBuilding dependency tree...\nThe following packages will be upgraded: openssl\n1 upgraded, 0 newly installed, 0 to remove.\nGet:1 http://archive.ubuntu.com openssl 3.0.11 [1,185 kB]\nFetched 1,185 kB in 2s\n(Reading database...\nPreparing to unpack .../openssl_3.0.11_amd64.deb ...\nUnpacking openssl (3.0.11) over (3.0.2) ...\nSetting up openssl (3.0.11) ...\nProcessing triggers for man-db (2.10.2-1) ...'
          : null,
    })),
    waves: [
      {
        id: `wave-${dep.id}-1`,
        deployment_id: dep.id,
        wave_number: 1,
        status: 'completed',
        percentage: 30,
        target_count: 2,
        success_count: 2,
        failed_count: 0,
        delay_after_minutes: 60,
        started_at: dep.started_at,
        completed_at: dep.updated_at,
      },
      {
        id: `wave-${dep.id}-2`,
        deployment_id: dep.id,
        wave_number: 2,
        status: dep.status === 'running' ? 'running' : 'completed',
        percentage: 70,
        target_count: dep.target_count - 2,
        success_count: dep.success_count > 2 ? dep.success_count - 2 : 0,
        failed_count: dep.failed_count,
        delay_after_minutes: 0,
        started_at: dep.status !== 'created' ? dep.updated_at : null,
        completed_at: dep.status === 'completed' ? dep.updated_at : null,
      },
    ],
  };
};

// ─── Dashboard ────────────────────────────────────────────────────────────────

export const mockDashboardSummary = {
  total_endpoints: 8,
  active_endpoints: 7,
  endpoints_degraded: 1,
  total_patches: 8,
  critical_patches: 2,
  patches_high: 3,
  patches_medium: 2,
  patches_low: 1,
  total_cves: 8,
  critical_cves: 4,
  unpatched_cves: 6,
  pending_deployments: 1,
  compliance_rate: 72,
  active_deployments: [
    { id: 'dep-002ddeeff', name: 'Weekly Web Server Updates', status: 'running', progress_pct: 50 },
  ],
  overdue_sla_count: 2,
  failed_deployments_count: 1,
  failed_trend_7d: [1, 0, 0, 1, 0, 0, 1],
  workflows_running_count: 1,
  workflows_running: [{ id: 'wf-001', name: 'Auto-Deploy Critical', current_stage: 'Approval' }],
  hub_sync_status: 'synced',
  hub_last_sync_at: ago(25),
  hub_url: 'https://hub.xpatch.io',
};

// ─── Hub Sync ─────────────────────────────────────────────────────────────────

export const mockHubSyncStatus = {
  id: 'sync-001',
  hub_url: 'https://hub.xpatch.io',
  status: 'synced',
  last_sync_at: ago(25),
  next_sync_at: new Date(Date.now() + 3_575 * 60_000).toISOString(),
  sync_interval: 60,
  entries_received: 18_432,
  last_entry_count: 147,
  last_error: null,
  created_at: ago(20160),
  updated_at: ago(25),
};

// ─── Compliance ───────────────────────────────────────────────────────────────

export const mockComplianceSummary = {
  frameworks: [
    {
      framework_id: 'nist-800-53',
      name: 'NIST 800-53',
      score: 74,
      total_cves: 15,
      compliant: 11,
      at_risk: 3,
      non_compliant: 1,
      evaluated_at: ago(120),
    },
    {
      framework_id: 'pci-dss-4',
      name: 'PCI DSS 4.0',
      score: 68,
      total_cves: 12,
      compliant: 8,
      at_risk: 2,
      non_compliant: 2,
      evaluated_at: ago(120),
    },
    {
      framework_id: 'cis-level1',
      name: 'CIS Benchmark L1',
      score: 81,
      total_cves: 10,
      compliant: 8,
      at_risk: 2,
      non_compliant: 0,
      evaluated_at: ago(120),
    },
  ],
};

export const mockFrameworkDetail = (id: string) => ({
  framework_id: id,
  name:
    id === 'nist-800-53' ? 'NIST 800-53' : id === 'pci-dss-4' ? 'PCI DSS 4.0' : 'CIS Benchmark L1',
  description: 'Security and privacy controls for federal information systems and organizations.',
  score: 74,
  total_cves: 15,
  compliant: 11,
  at_risk: 3,
  non_compliant: 1,
  evaluated_at: ago(120),
  endpoint_scores: mockEndpoints.data.slice(0, 5).map((e, i) => ({
    endpoint_id: e.id,
    hostname: e.hostname,
    score: [81, 74, 92, 68, 55][i] ?? 70,
    total_cves: [8, 10, 5, 12, 14][i] ?? 8,
    compliant_cves: [7, 7, 5, 8, 8][i] ?? 6,
    at_risk_cves: [1, 2, 0, 2, 4][i] ?? 1,
    non_compliant_cves: [0, 1, 0, 2, 2][i] ?? 1,
    late_remediation_cves: 0,
    evaluated_at: ago(120),
  })),
});

// ─── Audit ────────────────────────────────────────────────────────────────────

export const mockAuditEvents = {
  data: [
    {
      id: 'aud-001',
      tenant_id: TENANT_ID,
      actor_id: 'dev-user',
      actor_type: 'user',
      resource_type: 'deployment',
      resource_id: 'dep-002ddeeff',
      action: 'create',
      payload: { policy_id: 'pol-001', target_count: 2 },
      created_at: ago(30),
    },
    {
      id: 'aud-002',
      tenant_id: TENANT_ID,
      actor_id: 'dev-user',
      actor_type: 'user',
      resource_type: 'policy',
      resource_id: 'pol-004',
      action: 'update',
      payload: { field: 'enabled', old: true, new: false },
      created_at: ago(200),
    },
    {
      id: 'aud-003',
      tenant_id: TENANT_ID,
      actor_id: 'system',
      actor_type: 'system',
      resource_type: 'cve',
      resource_id: 'cve-001',
      action: 'ingest',
      payload: { source: 'nvd', count: 147 },
      created_at: ago(480),
    },
    {
      id: 'aud-004',
      tenant_id: TENANT_ID,
      actor_id: 'system',
      actor_type: 'system',
      resource_type: 'deployment',
      resource_id: 'dep-001aabbcc',
      action: 'complete',
      payload: { success: 5, failed: 1 },
      created_at: ago(680),
    },
    {
      id: 'aud-005',
      tenant_id: TENANT_ID,
      actor_id: 'dev-user',
      actor_type: 'user',
      resource_type: 'group',
      resource_id: 'grp-001',
      action: 'update',
      payload: { added_endpoints: ['ep-002'] },
      created_at: ago(1000),
    },
    {
      id: 'aud-006',
      tenant_id: TENANT_ID,
      actor_id: 'system',
      actor_type: 'system',
      resource_type: 'hub_sync',
      resource_id: 'sync-001',
      action: 'sync',
      payload: { entries: 147 },
      created_at: ago(1500),
    },
    {
      id: 'aud-007',
      tenant_id: TENANT_ID,
      actor_id: 'dev-user',
      actor_type: 'user',
      resource_type: 'policy',
      resource_id: 'pol-001',
      action: 'create',
      payload: { name: 'Critical Security Patches' },
      created_at: ago(10000),
    },
  ],
  next_cursor: null,
  total_count: 7,
};

// ─── Notifications ────────────────────────────────────────────────────────────

export const mockNotificationChannels = [
  {
    id: 'nc-001',
    tenant_id: TENANT_ID,
    name: 'Security Team Slack',
    channel_type: 'slack',
    enabled: true,
    created_at: ago(10000),
    updated_at: ago(5000),
  },
  {
    id: 'nc-002',
    tenant_id: TENANT_ID,
    name: 'Ops Email',
    channel_type: 'email',
    enabled: true,
    created_at: ago(8000),
    updated_at: ago(4000),
  },
  {
    id: 'nc-003',
    tenant_id: TENANT_ID,
    name: 'PagerDuty Webhook',
    channel_type: 'webhook',
    enabled: false,
    created_at: ago(5000),
    updated_at: ago(2000),
  },
];

export const mockNotificationPreferences = [
  {
    id: 'np-001',
    trigger_type: 'deployment_completed',
    enabled: true,
    channel_ids: ['nc-001', 'nc-002'],
    digest_frequency: 'realtime',
  },
  {
    id: 'np-002',
    trigger_type: 'deployment_failed',
    enabled: true,
    channel_ids: ['nc-001', 'nc-002', 'nc-003'],
    digest_frequency: 'realtime',
  },
  {
    id: 'np-003',
    trigger_type: 'critical_cve_discovered',
    enabled: true,
    channel_ids: ['nc-001'],
    digest_frequency: 'realtime',
  },
  {
    id: 'np-004',
    trigger_type: 'agent_disconnected',
    enabled: true,
    channel_ids: ['nc-002'],
    digest_frequency: 'daily',
  },
  {
    id: 'np-005',
    trigger_type: 'deployment_started',
    enabled: false,
    channel_ids: [],
    digest_frequency: 'realtime',
  },
  {
    id: 'np-006',
    trigger_type: 'compliance_threshold_breach',
    enabled: true,
    channel_ids: ['nc-001', 'nc-002'],
    digest_frequency: 'daily',
  },
];

export const mockNotificationHistory = {
  data: [
    {
      id: 'nh-001',
      trigger_type: 'deployment_completed',
      channel_id: 'nc-001',
      user_id: 'dev-user',
      status: 'sent',
      payload: { deployment_id: 'dep-001aabbcc' },
      error_message: null,
      created_at: ago(680),
    },
    {
      id: 'nh-002',
      trigger_type: 'critical_cve_discovered',
      channel_id: 'nc-001',
      user_id: 'dev-user',
      status: 'sent',
      payload: { cve_id: 'CVE-2023-5363' },
      error_message: null,
      created_at: ago(10080),
    },
    {
      id: 'nh-003',
      trigger_type: 'deployment_failed',
      channel_id: 'nc-003',
      user_id: 'dev-user',
      status: 'failed',
      payload: { deployment_id: 'dep-003gghhii' },
      error_message: 'Webhook endpoint returned 503',
      created_at: ago(4290),
    },
  ],
  next_cursor: null,
  total_count: 3,
};

// ─── Roles ────────────────────────────────────────────────────────────────────

export const mockRoles = {
  data: [
    {
      id: 'role-001',
      tenant_id: TENANT_ID,
      name: 'Super Admin',
      description: 'Full access to all resources',
      parent_role_id: null,
      is_system: true,
      permission_count: 48,
      created_at: ago(30000),
      updated_at: ago(30000),
    },
    {
      id: 'role-002',
      tenant_id: TENANT_ID,
      name: 'IT Manager',
      description: 'Manage endpoints, groups, and deployments',
      parent_role_id: null,
      is_system: true,
      permission_count: 32,
      created_at: ago(30000),
      updated_at: ago(30000),
    },
    {
      id: 'role-003',
      tenant_id: TENANT_ID,
      name: 'Security Analyst',
      description: 'View CVEs, compliance, and audit logs',
      parent_role_id: null,
      is_system: true,
      permission_count: 18,
      created_at: ago(30000),
      updated_at: ago(30000),
    },
    {
      id: 'role-004',
      tenant_id: TENANT_ID,
      name: 'Operator',
      description: 'Run deployments and manage policies',
      parent_role_id: 'role-002',
      is_system: true,
      permission_count: 24,
      created_at: ago(30000),
      updated_at: ago(30000),
    },
    {
      id: 'role-005',
      tenant_id: TENANT_ID,
      name: 'Prod Deploy Only',
      description: 'Custom role — deploy to production only',
      parent_role_id: null,
      is_system: false,
      permission_count: 8,
      created_at: ago(5000),
      updated_at: ago(500),
    },
  ],
  next_cursor: null,
  total_count: 5,
};

export const mockRolePermissions = [
  {
    id: 'perm-001',
    tenant_id: TENANT_ID,
    role_id: 'role-001',
    resource: 'endpoints',
    action: 'read',
    scope: '*',
  },
  {
    id: 'perm-002',
    tenant_id: TENANT_ID,
    role_id: 'role-001',
    resource: 'endpoints',
    action: 'write',
    scope: '*',
  },
  {
    id: 'perm-003',
    tenant_id: TENANT_ID,
    role_id: 'role-001',
    resource: 'deployments',
    action: 'read',
    scope: '*',
  },
  {
    id: 'perm-004',
    tenant_id: TENANT_ID,
    role_id: 'role-001',
    resource: 'deployments',
    action: 'write',
    scope: '*',
  },
];

export const mockUserRoles = [
  {
    id: 'role-001',
    tenant_id: TENANT_ID,
    name: 'Super Admin',
    description: 'Full access to all resources',
    parent_role_id: null,
    is_system: true,
    permission_count: 48,
    created_at: ago(30000),
    updated_at: ago(30000),
  },
];

// ─── License ──────────────────────────────────────────────────────────────────

export const mockLicenseStatus = {
  license_id: 'lic-xpatch-pro-2024',
  tier: 'professional',
  customer_name: 'Acme Corp',
  issued_at: ago(43200),
  expires_at: new Date(Date.now() + 320 * 24 * 60 * 60_000).toISOString(),
  days_remaining: 320,
  grace_period_days: 30,
  in_grace_period: false,
  endpoint_usage: { current: 8, limit: 500 },
  features: {
    rbac: true,
    compliance: true,
    workflows: true,
    notifications: true,
    api_access: true,
    audit_export: true,
    ai_assistant: false,
    msp_mode: false,
  },
};

// ─── Settings ─────────────────────────────────────────────────────────────────

export const mockServerSettings = {
  version: '1.4.2',
  uptime_seconds: 86_400,
  database_status: 'healthy',
  go_version: 'go1.25.8',
  build_commit: 'a2158fd',
};
